# ac
# Autogenerated from man page /usr/share/man/man8/ac.8
# using Darwin man parser
complete -c ac -s d --description 'Display the connect times in 24 hour chunks.'
complete -c ac -s p --description 'Display individual user totals.'
complete -c ac -s w --description 'Read raw connect time data from file, instead o… [See Man Page]'

