# accept
# Autogenerated from man page /usr/share/man/man8/accept.8.gz
# using Deroffing man parser
complete -c accept -s E --description 'Forces encryption when connecting to the server.'
complete -c accept -s U --description 'Sets the username that is sent when connecting to the server.'
complete -c accept -s h --description 'Chooses an alternate server.'
complete -c accept -s r --description 'Sets the reason string that is shown for a prin… [See Man Page]'

