# addremoveuser
# Autogenerated from man page /usr/share/man/man1/addremoveuser.1
# using Darwin man parser
complete -c addremoveuser -s a --description 'Description of -a flag.'
complete -c addremoveuser -s b --description 'Description of -b flag \\" Ends the list Pp .'

