# afhash
# Autogenerated from man page /usr/share/man/man1/afhash.1
# using Darwin man parser
complete -c afhash -s h --description 'print help text.'
complete -c afhash -s w --description 'write hash code to audio file.'
complete -c afhash -s x --description 'print hash code from audio file (if present).'
complete -c afhash -s c --description 'compare hash codes from two audio files El.'

