# afmtodit
# Autogenerated from man page /usr/share/man/man1/afmtodit.1
# using Deroffing man parser
complete -c afmtodit -s a --description 'Use  n as the slant parameter in the font file;… [See Man Page]'
complete -c afmtodit -s d --description 'The device description file is  desc_file rathe… [See Man Page]'
complete -c afmtodit -s e --description 'The PostScript font should be reencoded to use … [See Man Page]'
complete -c afmtodit -s i --description 'Generate an italic correction for each characte… [See Man Page]'
complete -c afmtodit -s m --description 'Prevent negative left italic correction values.'
complete -c afmtodit -s n --description 'Don\'t output a  ligatures command for this font.'
complete -c afmtodit -s s --description 'The font is special.'
complete -c afmtodit -s v --description 'Print version.'
complete -c afmtodit -o i50 --description 'for italic fonts.'
complete -c afmtodit -o i0 --description 'to improve spacing with eqn (1).'
complete -c afmtodit -s x --description 'Don\'t use the built-in Adobe Glyph List.  FILES.'

