# agentxtrap
# Autogenerated from man page /usr/share/man/man1/agentxtrap.1
# using Deroffing man parser
complete -c agentxtrap -s c --description 'if the  -c option is present then the notificat… [See Man Page]'
complete -c agentxtrap -s U --description 'if the  -U option is present then that value, p… [See Man Page]'
complete -c agentxtrap -s x --description 'if the  -x option is present then contact the A… [See Man Page]'
complete -c agentxtrap -s d -s D -s m -s M --description 'options are supported.'

