# allmemory
# Autogenerated from man page /usr/share/man/man1/allmemory.1
# using Darwin man parser
complete -c allmemory -s f --description 'Display a per-segment residency information bre… [See Man Page]'
complete -c allmemory -o sections --description 'Display a per-section residency information bre… [See Man Page]'
complete -c allmemory -s v --description 'Display information on address space layouts of… [See Man Page]'
complete -c allmemory -o vf --description 'Filter the address space output from the \\fB-v\\… [See Man Page]'
complete -c allmemory -s p --description 'Display detailed total residency information fo… [See Man Page]'
complete -c allmemory -s F --description 'Display summary information on per-process priv… [See Man Page]'
complete -c allmemory -o FD --description 'Display per-segment information on per-process … [See Man Page]'
complete -c allmemory -o purge --description 'Displays the NoVolatile resident column for all processes.'
complete -c allmemory -s n --description 'Do NOT display collected data (i. e.'
complete -c allmemory -o noframework --description 'Do NOT display data collected on frameworks.'
complete -c allmemory -o noprocess --description 'Do NOT display data collected on processes.'
complete -c allmemory -o proc --description 'Display data about the process with the specified pid/name.'
complete -c allmemory -o 32bit --description 'Display data only for 32-bit processes.'
complete -c allmemory -o 64bit --description 'Display data only for 64-bit processes.'
complete -c allmemory -s d --description 'Load and display the data from the default save… [See Man Page]'
complete -c allmemory -s i --description 'Load and display the data from a previous run o… [See Man Page]'
complete -c allmemory -s o --description 'Specify a directory in which to store the data … [See Man Page]'
complete -c allmemory -o ff --description 'Only displays frameworks for which the differen… [See Man Page]'
complete -c allmemory -o pf --description 'Only displays processes for which the differenc… [See Man Page]'
complete -c allmemory -o no32v64 --description 'Do not compare 32-bit processes and frameworks … [See Man Page]'

