# amt
# Autogenerated from man page /usr/share/man/man8/amt.8
# using Darwin man parser
complete -c amt -s m --description 'Skip the memory test.'
complete -c amt -s p --description 'Skip the privileged instructions test.'
complete -c amt -s q --description 'Suppress the screen output.'
complete -c amt -s s --description 'Skip the memory separation and protection test.'

