# appletviewer
# Autogenerated from man page /usr/share/man/man1/appletviewer.1
# using Deroffing man parser
complete -c appletviewer -o debug --description 'Starts the applet viewer in the Java debugger, … [See Man Page]'
complete -c appletviewer -o encoding --description 'Specifies the input . SM HTML file encoding name.'
complete -c appletviewer -s J --description 'Passes the string option through as a single ar… [See Man Page]'

