# apply
# Autogenerated from man page /usr/share/man/man1/apply.1
# using Darwin man parser
complete -c apply -s '#' --description 'Normally arguments are taken singly; the option… [See Man Page]'
complete -c apply -s a --description 'The use of the character % as a magic character… [See Man Page]'
complete -c apply -s d --description 'Display the commands that would have been execu… [See Man Page]'

