# applesingle
# Autogenerated from man page /usr/share/man/man1/applesingle.1
# using Darwin man parser
complete -c applesingle -s f --description 'perform the operation even if the output file already exists.'
complete -c applesingle -s h --description 'display version and usage, then quit.'
complete -c applesingle -s v --description 'be verbose.'
complete -c applesingle -s V --description 'display version, then quit.'
complete -c applesingle -s c --description 'For decode, read encoded data from the standand input.'
complete -c applesingle -s C --description 'create output files in dir.'
complete -c applesingle -s o --description 'Use name for output, overriding any stored or default name.'
complete -c applesingle -s s --description 'override the default suffix for the given encoding.'
complete -c applesingle -s R --description 'don\'t use BinHex runlength compression when encoding.'
complete -c applesingle -s t --description 'Specify MacBinary encoding type.'

