# apt
# Autogenerated from man page /usr/share/man/man1/apt.1
# using Deroffing man parser
complete -c apt -s s --description 'Specify the directory root under which processo… [See Man Page]'
complete -c apt -o nocompile --description 'Do not compile sources files to class files. if t.'
complete -c apt -o print --description 'Print out textual representation of specified t… [See Man Page]'
complete -c apt -o 'A[' --description 'Options to pass to annotation processors -- the… [See Man Page]'
complete -c apt -o factorypath --description 'Specify where to find annotation processor fact… [See Man Page]'
complete -c apt -o factory --description 'Name of annotation processor factory to use;  b… [See Man Page]'
complete -c apt -s d --description 'Specify where to place processor and javac gene… [See Man Page]'
complete -c apt -o cp --description 'or . if t.'
complete -c apt -o classpath --description 'Specify where to find user class files and anno… [See Man Page]'

