# arch
# Autogenerated from man page /usr/share/man/man1/arch.1
# using Darwin man parser
complete -c arch -o 32 --description 'Add the native 32-bit architecture to the list … [See Man Page]'
complete -c arch -o 64 --description 'Add the native 64-bit architecture to the list … [See Man Page]'
complete -c arch -s c --description 'Clears the environment that will be passed to t… [See Man Page]'
complete -c arch -s d --description 'Deletes the named environment variable from the… [See Man Page]'
complete -c arch -s e --description 'Assigns the given value to the named environmen… [See Man Page]'
complete -c arch -s h --description 'Prints a usage message and exits.'

