# asctl
# Autogenerated from man page /usr/share/man/man1/asctl.1
# using Darwin man parser
complete -c asctl -s p --description 'By default, asctl displays paths relative to th… [See Man Page]'
complete -c asctl -s l --description 'Write internal logging information to a temporary file.'

