# at
# Autogenerated from man page /usr/share/man/man1/at.1
# using Darwin man parser
complete -c at -s b --description 'Is an alias for at batch.'
complete -c at -s c --description 'Cat the jobs listed on the command line to standard output.'
complete -c at -s d --description 'Is an alias for at atrm (this option is depreca… [See Man Page]'
complete -c at -s f --description 'Read the job from file rather than standard input.'
complete -c at -s l --description 'With no arguments, list all jobs for the invoking user.'
complete -c at -s m --description 'Send mail to the user when the job has complete… [See Man Page]'
complete -c at -s q --description 'Use the specified queue.'
complete -c at -s r --description 'Remove the specified jobs.'
complete -c at -s t --description 'Specify the job time using the \\*[Px] time format.'
complete -c at -s v --description 'For at atq, shows completed but not yet deleted… [See Man Page]'

