# audit
# Autogenerated from man page /usr/share/man/man8/audit.8
# using Darwin man parser
complete -c audit -s e --description 'Forces the audit system to immediately remove a… [See Man Page]'
complete -c audit -s i --description 'Initializes and starts auditing.'
complete -c audit -s n --description 'Forces the audit system to close the existing a… [See Man Page]'
complete -c audit -s s --description 'Specifies that the audit system should [re]sync… [See Man Page]'
complete -c audit -s t --description 'Specifies that the audit system should terminate.'

