# auditd
# Autogenerated from man page /usr/share/man/man8/auditd.8
# using Darwin man parser
complete -c auditd -s d --description 'Starts the daemon in debug mode \\[em] it will not daemonize.'
complete -c auditd -s l --description 'This option is for when auditd is configured to… [See Man Page]'

