# auditreduce
# Autogenerated from man page /usr/share/man/man1/auditreduce.1
# using Darwin man parser
complete -c auditreduce -s A --description 'Select all records.'
complete -c auditreduce -s a --description 'Select records that occurred after or on the given datetime.'
complete -c auditreduce -s b --description 'Select records that occurred before the given datetime.'
complete -c auditreduce -s c --description 'Select records matching the given audit classes… [See Man Page]'
complete -c auditreduce -s d --description 'Select records that occurred on a given date.'
complete -c auditreduce -s e --description 'Select records with the given effective user ID or name.'
complete -c auditreduce -s f --description 'Select records with the given effective group ID or name.'
complete -c auditreduce -s g --description 'Select records with the given real group ID or name.'
complete -c auditreduce -s j --description 'Select records having a subject token with matching ID.'
complete -c auditreduce -s m --description 'Select records with the given event name or number.'
complete -c auditreduce -s o --description '-tag -width ".'
complete -c auditreduce -s r --description 'Select records with the given real user ID or name.'
complete -c auditreduce -s u --description 'Select records with the given audit ID.'
complete -c auditreduce -s v --description 'Invert sense of matching, to select records that do not match.'

