# authopen
# Autogenerated from man page /usr/share/man/man1/authopen.1
# using Darwin man parser
complete -c authopen -o stdoutpipe --description 'specifies that STDOUT_FILENO has been dup2()\'d … [See Man Page]'
complete -c authopen -o extauth --description 'specifies that authopen should read one Authori… [See Man Page]'
complete -c authopen -s w --description 'instructs authopen to open filename read/write and truncate it.'
complete -c authopen -s a --description 'append to filename rather than truncating it (t… [See Man Page]'
complete -c authopen -s c --description 'create the file if it doesn\'t exist.  m requires c Ns.'
complete -c authopen -s m --description 'specify the mode bits if a file is created.'
complete -c authopen -s o --description 'numerically specify the flags that should be pa… [See Man Page]'
complete -c authopen -s x --description 'require that the file being created not exist.'

