# automator
# Autogenerated from man page /usr/share/man/man1/automator.1
# using Darwin man parser
complete -c automator -s D --description 'Set variable name to value for this run of workflow.'
complete -c automator -s i --description 'Set input as the input to workflow If input is … [See Man Page]'
complete -c automator -s v --description 'Run in verbose mode.  El Pp.'

