# automountd
# Autogenerated from man page /usr/share/man/man8/automountd.8
# using Darwin man parser
complete -c automountd -s v --description 'Log to syslogd 8 more detailed information abou… [See Man Page]'
complete -c automountd -s n --description 'Disable browsing of all maps.'
complete -c automountd -s T --description 'Increase by 1 the logging level for messages pr… [See Man Page]'
complete -c automountd -s o --description 'Apply the options specified by opts to all mounts by default.'
complete -c automountd -s D --description 'Set the environment value specified by name to … [See Man Page]'

