# auvaltool
# Autogenerated from man page /usr/share/man/man1/auvaltool.1
# using Darwin man parser
complete -c auvaltool -s h --description 'print help text.'
complete -c auvaltool -s a --description 'lists all available AudioUnits of any type.'
complete -c auvaltool -s s --description 'lists all available AudioUnits of type \'TYPE\'.'
complete -c auvaltool -s v --description 'opens the AudioUnit specified by the TYPE SUBT … [See Man Page]'
complete -c auvaltool -o vt --description 'iterates through all of the AU\'s of specified TYPE and MANU.'
complete -c auvaltool -o de --description 'execution is terminated when first error is encountered.'
complete -c auvaltool -o dw --description 'execution is terminated when first warning is encountered.'
complete -c auvaltool -s c --description 'continue validating when an error occurs in batch mode.'
complete -c auvaltool -s q --description 'quiet - does no printing except for errors or warnings.'
complete -c auvaltool -o qp --description 'doesn\'t print parameter or Factory Presets information.'
complete -c auvaltool -s o --description 'only runs a basic open and initialize test.'
complete -c auvaltool -s r --description 'repeat the whole process of validation N times.'
complete -c auvaltool -s w --description 'wait after finished - good for profiling memory… [See Man Page]'
complete -c auvaltool -o vers --description 'The version is printed to stdout.'
complete -c auvaltool -o versh --description 'The version is printed to stdout in hexadecimal.'
complete -c auvaltool -s f --description 'Each line in the file should contain one complete command.  El.'

