# awacsd
# Autogenerated from man page /usr/share/man/man8/awacsd.8
# using Darwin man parser
complete -c awacsd -s f --description 'Do not filter packets.'
complete -c awacsd -s u --description 'Do not attempt UDP hole punching.'
complete -c awacsd -s h --description 'Do not attempt TLS hostname verification.'
complete -c awacsd -s d --description 'Log verbose debugging messages to the specified file.'
complete -c awacsd -s t --description 'Set keepalive timer to specified number of seconds.'

