# bchunk
# Autogenerated from man page /usr/local/share/man/man1/bchunk.1
# using Deroffing man parser
complete -c bchunk -s v --description 'Makes binchunker print some more unnecessary me… [See Man Page]'
complete -c bchunk -s w --description 'Makes binchunker write audio tracks in WAV format.'
complete -c bchunk -s s --description 'Makes binchunker swap byte order in the samples… [See Man Page]'
complete -c bchunk -s p --description 'Makes binchunker go into PSX mode and truncate … [See Man Page]'
complete -c bchunk -s r --description 'Makes binchunker output MODE2/2352 tracks in ra… [See Man Page]'

