# bluetoothaudiod
# Autogenerated from man page /usr/share/man/man1/bluetoothaudiod.1
# using Darwin man parser
complete -c bluetoothaudiod -s a --description 'Description of -a flag.'
complete -c bluetoothaudiod -s b --description 'Description of -b flag \\" Ends the list Pp .'

