# caffeinate
# Autogenerated from man page /usr/share/man/man8/caffeinate.8
# using Darwin man parser
complete -c caffeinate -s d --description 'Create an assertion to prevent the display from sleeping.'
complete -c caffeinate -s i --description 'Create an assertion to prevent the system from idle sleeping.'
complete -c caffeinate -s m --description 'Create an assertion to prevent the disk from idle sleeping.'
complete -c caffeinate -s s --description 'Create an assertion to prevent the system from sleeping.'
complete -c caffeinate -s u --description 'Create an assertion to declare that user is active.'
complete -c caffeinate -s t --description 'Specifies the timeout value in seconds for whic… [See Man Page]'
complete -c caffeinate -s w --description 'Waits for the process with the specified pid to exit.'

