# cal
# Autogenerated from man page /usr/share/man/man1/cal.1
# using Darwin man parser
complete -c cal -s J --description 'Display Julian Calendar, if combined with the e… [See Man Page]'
complete -c cal -s e --description 'Display date of easter (for western churches).'
complete -c cal -s j --description 'Display Julian days (days one-based, numbered from January 1).'
complete -c cal -s m --description 'Display the specified month.'
complete -c cal -s o --description 'Display date of orthodox easter (Greek and Russ… [See Man Page]'
complete -c cal -s p --description 'Print the country codes and switching days from… [See Man Page]'
complete -c cal -s s --description 'Assume the switch from Julian to Gregorian Cale… [See Man Page]'
complete -c cal -s w --description 'Print the number of the week below each week column.'
complete -c cal -s y --description 'Display a calendar for the specified year.'

