# CallHistoryTool
# Autogenerated from man page /usr/share/man/man1/CallHistoryTool.1
# using Darwin man parser
complete -c CallHistoryTool -s a --description 'Description of -a flag.'
complete -c CallHistoryTool -s b --description 'Description of -b flag \\" Ends the list Pp .'

