# cap_mkdb
# Autogenerated from man page /usr/share/man/man1/cap_mkdb.1
# using Darwin man parser
complete -c cap_mkdb -s f --description 'Specify a different database basename.'
complete -c cap_mkdb -s v --description 'Print out the number of capability records in the database.'

