# cat
# Autogenerated from man page /usr/share/man/man1/cat.1
# using Darwin man parser
complete -c cat -s b --description 'Number the non-blank output lines, starting at 1.'
complete -c cat -s e --description 'Display non-printing characters (see the v opti… [See Man Page]'
complete -c cat -s n --description 'Number the output lines, starting at 1.'
complete -c cat -s s --description 'Squeeze multiple adjacent empty lines, causing … [See Man Page]'
complete -c cat -s t --description 'Display non-printing characters (see the v opti… [See Man Page]'
complete -c cat -s u --description 'Disable output buffering.'
complete -c cat -s v --description 'Display non-printing characters so they are visible.'

