# cc_fips_test
# Autogenerated from man page /usr/share/man/man1/cc_fips_test.1
# using Darwin man parser
complete -c cc_fips_test -s a --description 'Description of -a flag.'
complete -c cc_fips_test -s b --description 'Description of -b flag \\" Ends the list Pp .'

