# cd9660
# Autogenerated from man page /usr/share/man/man8/cd9660.util.8
# using Darwin man parser
complete -c cd9660 -s m --description 'mount.'
complete -c cd9660 -s p --description 'probe for mounting.'
complete -c cd9660 -s u --description 'unmount El Pp mountflags above are either: -bul… [See Man Page]'

