# cfilutil
# Autogenerated from man page /usr/share/man/man1/cfilutil.1
# using Darwin man parser
complete -c cfilutil -s a --description 'Auto start filtering with given offset.'
complete -c cfilutil -s h --description 'Display this help.'
complete -c cfilutil -s i --description 'Interactive mode.'
complete -c cfilutil -s k --description 'Peek mode with increment.'
complete -c cfilutil -s l --description 'Pass loopback traffic.'
complete -c cfilutil -s m --description 'Maximum dump length.'
complete -c cfilutil -s p --description 'Pass mode (all or after given offset if it is > 0).'
complete -c cfilutil -s q --description 'Decrease verbosity.'
complete -c cfilutil -s r --description 'Random drop rate.'
complete -c cfilutil -s s --description 'display content filter statistics (all, sock, filt, cfil).'
complete -c cfilutil -s t --description 'Pass delay in microseconds.'
complete -c cfilutil -s u --description 'NECP filter control unit.'
complete -c cfilutil -s v --description 'Increase verbosity.'

