# chat
# Autogenerated from man page /usr/share/man/man8/chat.8
# using Deroffing man parser
complete -c chat -s f --description 'Read the chat script from the chat file.'
complete -c chat -s t --description 'Set the timeout for the expected string to be received.'
complete -c chat -s r --description 'Set the file for output of the report strings.'
complete -c chat -s e --description 'Start with the echo option turned on.'
complete -c chat -s E --description 'Enables environment variable substituion within… [See Man Page]'
complete -c chat -s v --description 'Request that the chat script be executed in a verbose mode.'
complete -c chat -s V --description 'Request that the chat script be executed in a s… [See Man Page]'
complete -c chat -s s --description 'Use stderr.'
complete -c chat -s S --description 'Do not use the SYSLOG.'
complete -c chat -s T --description 'Pass in an arbitary string, usually a phone num… [See Man Page]'
complete -c chat -s U --description 'Pass in a second string, usually a phone number… [See Man Page]'

