# chflags
# Autogenerated from man page /usr/share/man/man1/chflags.1
# using Darwin man parser
complete -c chflags -s f --description 'Do not display a diagnostic message if chflags … [See Man Page]'
complete -c chflags -s H --description 'If the R option is specified, symbolic links on… [See Man Page]'
complete -c chflags -s h --description 'If the file is a symbolic link, change the file… [See Man Page]'
complete -c chflags -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chflags -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chflags -s R --description 'Change the file flags for the file hierarchies … [See Man Page]'
complete -c chflags -s v --description 'Cause chflags to be verbose, showing filenames … [See Man Page]'

