# chgrp
# Autogenerated from man page /usr/share/man/man1/chgrp.1
# using Darwin man parser
complete -c chgrp -s f --description 'The force option ignores errors, except for usa… [See Man Page]'
complete -c chgrp -s H --description 'If the R option is specified, symbolic links on… [See Man Page]'
complete -c chgrp -s h --description 'If the file is a symbolic link, the group ID of… [See Man Page]'
complete -c chgrp -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chgrp -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chgrp -s R --description 'Change the group ID for the file hierarchies ro… [See Man Page]'
complete -c chgrp -s v --description 'Cause chgrp chgrp to be verbose, showing files … [See Man Page]'

