# chkpasswd
# Autogenerated from man page /usr/share/man/man8/chkpasswd.8
# using Darwin man parser
complete -c chkpasswd -s c --description 'The supplied password is compared verbatim with… [See Man Page]'
complete -c chkpasswd -s i --description 'Specify the system against which to check the p… [See Man Page]'
complete -c chkpasswd -s l --description 'Specify a location; varies based on infosystem … [See Man Page]'

