# chmod
# Autogenerated from man page /usr/share/man/man1/chmod.1
# using Darwin man parser
complete -c chmod -s f --description 'Do not display a diagnostic message if chmod ch… [See Man Page]'
complete -c chmod -s H --description 'If the R option is specified, symbolic links on… [See Man Page]'
complete -c chmod -s h --description 'If the file is a symbolic link, change the mode… [See Man Page]'
complete -c chmod -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chmod -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chmod -s R --description 'Change the modes of the file hierarchies rooted… [See Man Page]'
complete -c chmod -s v --description 'Cause chmod chmod to be verbose, showing filena… [See Man Page]'
complete -c chmod -s a --description 'The -a mode is used to delete ACL entries.'
complete -c chmod -s E --description 'Reads the ACL information from stdin, as a sequ… [See Man Page]'
complete -c chmod -s C --description 'Returns false if any of the named files have AC… [See Man Page]'
complete -c chmod -s i --description 'Removes the \'inherited\' bit from all entries in… [See Man Page]'
complete -c chmod -s I --description 'Removes all inherited entries from the named file(s) ACL(s).'
complete -c chmod -s N --description 'Removes the ACL from the named file(s).'

