# chown
# Autogenerated from man page /usr/share/man/man8/chown.8
# using Darwin man parser
complete -c chown -s f --description 'Don\'t report any failure to change file owner o… [See Man Page]'
complete -c chown -s H --description 'If the R option is specified, symbolic links on… [See Man Page]'
complete -c chown -s h --description 'If the file is a symbolic link, change the user… [See Man Page]'
complete -c chown -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chown -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chown -s R --description 'Change the user ID and/or the group ID for the … [See Man Page]'
complete -c chown -s v --description 'Cause chown chown to be verbose, showing files … [See Man Page]'

