# chpass
# Autogenerated from man page /usr/share/man/man1/chpass.1
# using Darwin man parser
complete -c chpass -s l --description 'If not specified, chpass will perform a search … [See Man Page]'
complete -c chpass -s u --description 'The user name to use when authenticating to the… [See Man Page]'
complete -c chpass -s s --description 'Attempt to change the user\'s shell to newshell.'

