# cmp
# Autogenerated from man page /usr/share/man/man1/cmp.1
# using Deroffing man parser
complete -c cmp -s b -l print-bytes --description 'Print differing bytes.'
complete -c cmp -s i -l ignore-initial --description 'Skip the first SKIP bytes of input.'
complete -c cmp -s l -l verbose --description 'Output byte numbers and values of all differing bytes.'
complete -c cmp -s n -l bytes --description 'Compare at most LIMIT bytes.'
complete -c cmp -s s -l quiet -l silent --description 'Output nothing; yield exit status only.'
complete -c cmp -s v -l version --description 'Output version info.'
complete -c cmp -l help --description 'Output this help.'

