# colldef
# Autogenerated from man page /usr/share/man/man1/colldef.1
# using Darwin man parser
complete -c colldef -s I --description 'Set directory name where charmap files can be f… [See Man Page]'
complete -c colldef -s o --description 'Set output file name, LC_COLLATE by default.'

