# column
# Autogenerated from man page /usr/share/man/man1/column.1
# using Darwin man parser
complete -c column -s c --description 'Output is formatted for a display columns wide.'
complete -c column -s s --description 'Specify a set of characters to be used to delim… [See Man Page]'
complete -c column -s t --description 'Determine the number of columns the input conta… [See Man Page]'
complete -c column -s x --description 'Fill columns before filling rows.'

