# comm
# Autogenerated from man page /usr/share/man/man1/comm.1
# using Darwin man parser
complete -c comm -s 1 --description 'Suppress printing of column 1.'
complete -c comm -s 2 --description 'Suppress printing of column 2.'
complete -c comm -s 3 --description 'Suppress printing of column 3.'
complete -c comm -s i --description 'Case insensitive comparison of lines.'

