# compress
# Autogenerated from man page /usr/share/man/man1/compress.1
# using Darwin man parser
complete -c compress -s b --description 'The code size (see below) is limited to bits, w… [See Man Page]'
complete -c compress -s c --description 'Compressed or uncompressed output is written to… [See Man Page]'
complete -c compress -s f --description 'Files are overwritten without prompting for confirmation.'
complete -c compress -s v --description 'Print the percentage reduction of each file.'

