# corelist
# Autogenerated from man page /usr/share/man/man1/corelist.1
# using Type1
complete -c corelist -s a --description 'lists all versions of the given module (or the … [See Man Page]'
complete -c corelist -s d --description 'finds the first perl version where a module has… [See Man Page]'
complete -c corelist -l diff --description 'Given two versions of perl, this prints a human… [See Man Page]'
complete -c corelist -s '?' -o help --description 'help! help! help! to see more help, try --man.'
complete -c corelist -o man --description 'all of the help.'
complete -c corelist -s v --description 'lists all of the perl release versions we got the CoreList for.'
complete -c corelist -s r --description 'lists all of the perl releases and when they were released .'
complete -c corelist -l feature -s f --description 'lists the first version bundle of each named feature given.'

