# corelist5
# Autogenerated from man page /usr/share/man/man1/corelist5.18.1
# using Type1
complete -c corelist5 -s r --description 'lists all of the perl releases and when they were released .'
complete -c corelist5 -l feature -s f --description 'lists the first version bundle of each named feature given.'

