# cp
# Autogenerated from man page /usr/share/man/man1/cp.1
# using Darwin man parser
complete -c cp -s a --description 'Same as pPR options.'
complete -c cp -s f --description 'For each existing destination pathname, remove … [See Man Page]'
complete -c cp -s H --description 'If the R option is specified, symbolic links on… [See Man Page]'
complete -c cp -s i --description 'Cause cp cp to write a prompt to the standard e… [See Man Page]'
complete -c cp -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c cp -s n --description 'Do not overwrite an existing file.'
complete -c cp -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c cp -s p --description 'Cause cp cp to preserve the following attribute… [See Man Page]'
complete -c cp -s R --description 'If source_file designates a directory, cp cp co… [See Man Page]'
complete -c cp -s v --description 'Cause cp cp to be verbose, showing files as they are copied.'
complete -c cp -s X --description 'Do not copy Extended Attributes (EAs) or resource forks.'

