# createhomedir
# Autogenerated from man page /usr/share/man/man1/createhomedir.1
# using Darwin man parser
complete -c createhomedir -s s --description 'creates home directories for server home paths only (default).'
complete -c createhomedir -s c --description 'creates home directories for local home paths only.'
complete -c createhomedir -s b --description 'creates home directories for both server and local home paths.'
complete -c createhomedir -s a --description 'creates home directories for users defined in a… [See Man Page]'
complete -c createhomedir -s l --description 'creates home directories for users defined in t… [See Man Page]'
complete -c createhomedir -s n --description 'creates home directories for users defined in a… [See Man Page]'
complete -c createhomedir -s u --description 'creates a home directory for a specific user de… [See Man Page]'
complete -c createhomedir -s i --description 'reads username list from standard input and cre… [See Man Page]'
complete -c createhomedir -s h --description 'usage help.  \\" Ends the list Pp .'

