# cron
# Autogenerated from man page /usr/share/man/man8/cron.8
# using Darwin man parser
complete -c cron -s s --description 'Enable special handling of situations when the … [See Man Page]'
complete -c cron -s o --description 'Disable the special handling of situations when… [See Man Page]'
complete -c cron -s x --description 'Enable writing of debugging information to standard output.'

