# csdiagnose
# Autogenerated from man page /usr/share/man/man1/csdiagnose.1
# using Darwin man parser
complete -c csdiagnose -s h --description 'Show this help information.'
complete -c csdiagnose -s f --description 'Specify an output path which will hold the file… [See Man Page]'
complete -c csdiagnose -s v --description 'Verbose mode, which prints every command it invokes.'

