# csgather
# Autogenerated from man page /usr/share/man/man1/csgather.1
# using Darwin man parser
complete -c csgather -s G --description 'Gather all CoreStorage metadata and write into … [See Man Page]'
complete -c csgather -s o --description 'Specify the output file generated by the -r option.'
complete -c csgather -s r --description 'Find out the CoreStorage logical volume identif… [See Man Page]'

