# csplit
# Autogenerated from man page /usr/share/man/man1/csplit.1
# using Darwin man parser
complete -c csplit -s f --description 'Give created files names beginning with prefix.'
complete -c csplit -s k --description 'Do not remove output files if an error occurs o… [See Man Page]'
complete -c csplit -s n --description 'Use number of decimal digits after the prefix t… [See Man Page]'
complete -c csplit -s s --description 'Do not write the size of each output file to st… [See Man Page]'

