# csreq
# Autogenerated from man page /usr/share/man/man1/csreq.1
# using Darwin man parser
complete -c csreq -s b --description 'Requests that the requirement read be written i… [See Man Page]'
complete -c csreq -s r --description 'Specifies the input requirement.'
complete -c csreq -s t --description 'Requests that the requirement read be written a… [See Man Page]'
complete -c csreq -s v --description 'Increases the verbosity of output.'

