# csunique
# Autogenerated from man page /usr/share/man/man8/csunique.8
# using Darwin man parser
complete -c csunique -s v --description 'Output verbose progress information of each ste… [See Man Page]'
complete -c csunique -s n --description 'Operates in "dry run" mode; no changes are made… [See Man Page]'
complete -c csunique -s I --description 'Specifies an additional class of UUID objects t… [See Man Page]'
complete -c csunique -s X --description 'Specifies a class of UUID objects that should not be modified.'

