# ctags
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/ctags.1
# using Darwin man parser
complete -c ctags -s a --description 'append to tags file.'
complete -c ctags -s B --description 'use backward searching patterns ?. ?.'
complete -c ctags -s d --description 'create tags for #defines that don\'t take argume… [See Man Page]'
complete -c ctags -s F --description 'use forward searching patterns /. / (the default).'
complete -c ctags -s f --description 'Places the tag descriptions in a file called tags_file.'
complete -c ctags -s t --description 'create tags for typedefs, structs, unions, and enums.'
complete -c ctags -s u --description 'update the specified files in the tags file, th… [See Man Page]'
complete -c ctags -s v --description 'An index of the form expected by vgrind 1 is pr… [See Man Page]'
complete -c ctags -s w --description 'suppress warning diagnostics.'
complete -c ctags -s x --description 'ctags produces a list of object names, the line… [See Man Page]'

