# cu
# Autogenerated from man page /usr/share/man/man1/cu.1
# using Deroffing man parser
complete -c cu -s e -l parity --description 'Use even parity.'
complete -c cu -s o --description 'Use odd parity.'
complete -c cu -s h -l halfduplex --description 'Echo characters locally (half-duplex mode).'
complete -c cu -l nostop --description 'Turn off XON/XOFF handling (it is on by default).'
complete -c cu -s E -l escape --description 'Set the escape character.   Initially  ~ (tilde).'
complete -c cu -s z -l system --description 'The system to call.'
complete -c cu -s c -l phone --description 'The phone number to call.'
complete -c cu -s p -l port --description 'Name the port to use.'
complete -c cu -s a --description 'Equivalent to  --port port.'
complete -c cu -s l -l line --description 'Name the line to use by giving a device name.'
complete -c cu -s s -l speed --description 'The speed (baud rate) to use.'
complete -c cu -s '#' --description 'Where # is a number, equivalent to  --speed #.'
complete -c cu -s n -l prompt --description 'Prompt for the phone number to use.'
complete -c cu -s d --description 'Enter debugging mode.   Equivalent to  --debug all.'
complete -c cu -s x -l debug --description 'Turn on particular debugging types.'
complete -c cu -s I -l config --description 'Set configuration file to use.'
complete -c cu -s v -l version --description 'Report version information and exit.'
complete -c cu -l help --description 'Print a help message and exit.'

