# cupsd
# Autogenerated from man page /usr/share/man/man8/cupsd.8.gz
# using Deroffing man parser
complete -c cupsd -s c --description 'Uses the named configuration file.'
complete -c cupsd -s f --description 'Run  cupsd in the foreground; the default is to… [See Man Page]'
complete -c cupsd -s F --description 'Run  cupsd in the foreground but detach the pro… [See Man Page]'
complete -c cupsd -s h --description 'Shows the program usage.'
complete -c cupsd -s l --description 'This option is passed to  cupsd when it is run … [See Man Page]'
complete -c cupsd -s t --description 'Test the configuration file for syntax errors.  FILES.'

