# cups-lpd
# Autogenerated from man page /usr/share/man/man8/cups-lpd.8.gz
# using Deroffing man parser
complete -c cups-lpd -s h --description 'Sets the CUPS server (and port) to use.'
complete -c cups-lpd -s n --description 'Disables reverse address lookups; normally  cup… [See Man Page]'
complete -c cups-lpd -s o --description 'Inserts options for all print queues.'

