# cupsctl
# Autogenerated from man page /usr/share/man/man8/cupsctl.8.gz
# using Deroffing man parser
complete -c cupsctl -s E --description 'Enables encryption on the connection to the scheduler.'
complete -c cupsctl -s U --description 'Specifies an alternate username to use when aut… [See Man Page]'
complete -c cupsctl -s h --description 'Specifies the server address.'
complete -c cupsctl -l '[no-]debug-logging' --description 'Enables (disables) debug logging to the error_log file.'
complete -c cupsctl -l '[no-]remote-admin' --description 'Enables (disables) remote administration.'
complete -c cupsctl -l '[no-]remote-any' --description 'Enables (disables) printing from any address, e. g.'
complete -c cupsctl -l '[no-]share-printers' --description 'Enables (disables) sharing of local printers wi… [See Man Page]'
complete -c cupsctl -l '[no-]user-cancel-any' --description 'Allows (prevents) users to cancel jobs owned by others.'

