# cups-config
# Autogenerated from man page /usr/share/man/man1/cups-config.1.gz
# using Deroffing man parser
complete -c cups-config -l api-version --description 'Reports the current API version (major. minor).'
complete -c cups-config -l build --description 'Reports a system-specific build number.'
complete -c cups-config -l cflags --description 'Reports the necessary compiler options.'
complete -c cups-config -l datadir --description 'Reports the default CUPS data directory.'
complete -c cups-config -l help --description 'Reports the program usage message.'
complete -c cups-config -l image --description 'When used with --libs, adds the CUPS imaging li… [See Man Page]'
complete -c cups-config -l ldflags --description 'Reports the necessary linker options.'
complete -c cups-config -l libs --description 'Reports the necessary libraries to link to.'
complete -c cups-config -l serverbin --description 'Reports the default CUPS binary directory, wher… [See Man Page]'
complete -c cups-config -l serverroot --description 'Reports the default CUPS configuration file directory.'
complete -c cups-config -l static --description 'When used with --libs, reports the static libra… [See Man Page]'
complete -c cups-config -l version --description 'Reports the full version number of the CUPS ins… [See Man Page]'

