# cupsaddsmb
# Autogenerated from man page /usr/share/man/man8/cupsaddsmb.8.gz
# using Deroffing man parser
complete -c cupsaddsmb -s H --description 'Specifies the SAMBA server which defaults to the CUPS server.'
complete -c cupsaddsmb -s U --description 'Specifies the SAMBA print admin username which … [See Man Page]'
complete -c cupsaddsmb -s a --description 'Exports all known printers.'
complete -c cupsaddsmb -s h --description 'Specifies a different CUPS server to use.'
complete -c cupsaddsmb -s v --description 'Specifies that verbose information should be shown.'

