# curl-config
# Autogenerated from man page /usr/share/man/man1/curl-config.1
# using Deroffing man parser
complete -c curl-config -l ca --description 'Displays the built-in path to the CA cert bundl… [See Man Page]'
complete -c curl-config -l cc --description 'Displays the compiler used to build libcurl.'
complete -c curl-config -l cflags --description 'Set of compiler options (CFLAGS) to use when co… [See Man Page]'
complete -c curl-config -l checkfor --description 'Specify the oldest possible libcurl version str… [See Man Page]'
complete -c curl-config -l configure --description 'Displays the arguments given to configure when building curl.'
complete -c curl-config -l feature --description 'Lists what particular main features the install… [See Man Page]'
complete -c curl-config -l help --description 'Displays the available options.'
complete -c curl-config -l libs --description 'Shows the complete set of libs and other linker… [See Man Page]'
complete -c curl-config -l prefix --description 'This is the prefix used when libcurl was installed.'
complete -c curl-config -l protocols --description 'Lists what particular protocols the installed l… [See Man Page]'
complete -c curl-config -l static-libs --description 'Shows the complete set of libs and other linker… [See Man Page]'
complete -c curl-config -l version --description 'Outputs version information about the installed libcurl.'
complete -c curl-config -l vernum --description 'Outputs version information about the installed… [See Man Page]'

