# cut
# Autogenerated from man page /usr/share/man/man1/cut.1
# using Darwin man parser
complete -c cut -s b --description 'The list specifies byte positions.'
complete -c cut -s c --description 'The list specifies character positions.'
complete -c cut -s d --description 'Use delim as the field delimiter character inst… [See Man Page]'
complete -c cut -s f --description 'The list specifies fields, separated in the inp… [See Man Page]'
complete -c cut -s n --description 'Do not split multi-byte characters.'
complete -c cut -s s --description 'Suppress lines with no field delimiter characters.'

