# date
# Autogenerated from man page /usr/share/man/man1/date.1
# using Darwin man parser
complete -c date -s d --description 'Set the kernel\'s value for daylight saving time.'
complete -c date -s f --description 'Use input_fmt as the format string to parse the… [See Man Page]'
complete -c date -s j --description 'Do not try to set the date.'
complete -c date -s n --description 'By default, if the timed 8 daemon is running, d… [See Man Page]'
complete -c date -s r --description 'Print the date and time represented by seconds,… [See Man Page]'
complete -c date -s t --description 'Set the system\'s value for minutes west of GMT.'
complete -c date -s u --description 'Display or set the date in UTC (Coordinated Universal) time.'
complete -c date -s v --description 'Adjust (i. e.'

