# db_archive
# Autogenerated from man page /usr/share/man/man1/db_archive.1
# using Darwin man parser
complete -c db_archive -s a --description 'Write all pathnames as absolute pathnames, inst… [See Man Page]'
complete -c db_archive -s d --description 'Remove log files that are no longer needed; no … [See Man Page]'
complete -c db_archive -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_archive -s l --description 'Write out the pathnames of all the database log… [See Man Page]'
complete -c db_archive -s P --description 'Specify an environment password.'
complete -c db_archive -s s --description 'Write the pathnames of all the database files t… [See Man Page]'
complete -c db_archive -s V --description 'Write the library version number to the standar… [See Man Page]'
complete -c db_archive -s v --description 'Run in verbose mode, listing the checkpoints in… [See Man Page]'

