# db_checkpoint
# Autogenerated from man page /usr/share/man/man1/db_checkpoint.1
# using Darwin man parser
complete -c db_checkpoint -s 1 --description 'Checkpoint the log once, regardless of whether … [See Man Page]'
complete -c db_checkpoint -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_checkpoint -s k --description 'Checkpoint the database at least as often as ev… [See Man Page]'
complete -c db_checkpoint -s L --description 'Log the execution of the db_checkpoint utility … [See Man Page]'
complete -c db_checkpoint -s P --description 'Specify an environment password.'
complete -c db_checkpoint -s p --description 'Checkpoint the database at least every min minu… [See Man Page]'
complete -c db_checkpoint -s V --description 'Write the library version number to the standar… [See Man Page]'
complete -c db_checkpoint -s v --description 'Write the time of each checkpoint attempt to th… [See Man Page]'

