# db_dump
# Autogenerated from man page /usr/share/man/man1/db_dump.1
# using Darwin man parser
complete -c db_dump -s d --description 'Dump the specified database in a format helpful… [See Man Page]'
complete -c db_dump -s f --description 'Write to the specified file instead of to the standard output.'
complete -c db_dump -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_dump -s k --description 'Dump record numbers from Queue and Recno databases as keys.'
complete -c db_dump -s l --description 'List the databases stored in the file.'
complete -c db_dump -s N --description 'Do not acquire shared region mutexes while running.'
complete -c db_dump -s P --description 'Specify an environment password.'
complete -c db_dump -s p --description 'If characters in either the key or data items a… [See Man Page]'
complete -c db_dump -s R --description 'Aggressively salvage data from a possibly corrupt file.'
complete -c db_dump -s r --description 'Salvage data from a possibly corrupt file.'
complete -c db_dump -s s --description 'Specify a single database to dump.'
complete -c db_dump -s V --description 'Write the library version number to the standar… [See Man Page]'

