# db_deadlock
# Autogenerated from man page /usr/share/man/man1/db_deadlock.1
# using Darwin man parser
complete -c db_deadlock -s a --description 'When a deadlock is detected, abort the locker: … [See Man Page]'
complete -c db_deadlock -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_deadlock -s L --description 'Log the execution of the db_deadlock utility to… [See Man Page]'
complete -c db_deadlock -s t --description 'Check the database environment every sec second… [See Man Page]'
complete -c db_deadlock -s V --description 'Write the library version number to the standar… [See Man Page]'
complete -c db_deadlock -s v --description 'Run in verbose mode, generating messages each t… [See Man Page]'

