# db_load
# Autogenerated from man page /usr/share/man/man1/db_load.1
# using Darwin man parser
complete -c db_load -s c --description 'Specify configuration options ignoring any valu… [See Man Page]'
complete -c db_load -s f --description 'Read from the specified input file instead of f… [See Man Page]'
complete -c db_load -s h --description 'Specify a home directory for the database environment.'
complete -c db_load -s n --description 'Do not overwrite existing keys in the database … [See Man Page]'
complete -c db_load -s P --description 'Specify an environment password.'
complete -c db_load -s T --description 'The -T option allows non-Berkeley DB applicatio… [See Man Page]'
complete -c db_load -s t --description 'Specify the underlying access method.'
complete -c db_load -s V --description 'Write the library version number to the standar… [See Man Page]'

