# db_printlog
# Autogenerated from man page /usr/share/man/man1/db_printlog.1
# using Darwin man parser
complete -c db_printlog -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_printlog -s N --description 'Do not acquire shared region mutexes while running.'
complete -c db_printlog -s P --description 'Specify an environment password.'
complete -c db_printlog -s r --description 'Read the log files in reverse order.'
complete -c db_printlog -s V --description 'Write the library version number to the standar… [See Man Page]'

