# db_recover
# Autogenerated from man page /usr/share/man/man1/db_recover.1
# using Darwin man parser
complete -c db_recover -s c --description 'Perform catastrophic recovery instead of normal recovery.'
complete -c db_recover -s e --description 'Retain the environment after running recovery.'
complete -c db_recover -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_recover -s P --description 'Specify an environment password.'
complete -c db_recover -s t --description 'Recover to the time specified rather than to th… [See Man Page]'
complete -c db_recover -s V --description 'Write the library version number to the standar… [See Man Page]'
complete -c db_recover -s v --description 'Run in verbose mode.'

