# db_stat
# Autogenerated from man page /usr/share/man/man1/db_stat.1
# using Darwin man parser
complete -c db_stat -s C --description 'Display internal information about the lock region.'
complete -c db_stat -s c --description 'Display lock region statistics, as described in… [See Man Page]'
complete -c db_stat -s d --description 'Display database statistics for the specified f… [See Man Page]'
complete -c db_stat -s e --description 'Display current environment statistics.'
complete -c db_stat -s f --description 'Display only those database statistics that can… [See Man Page]'
complete -c db_stat -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_stat -s l --description 'Display log region statistics, as described in … [See Man Page]'
complete -c db_stat -s M --description 'Display internal information about the shared m… [See Man Page]'
complete -c db_stat -s m --description 'Display shared memory buffer pool statistics, a… [See Man Page]'
complete -c db_stat -s N --description 'Do not acquire shared region mutexes while running.'
complete -c db_stat -s P --description 'Specify an environment password.'
complete -c db_stat -s r --description 'Display replication statistics, as described in… [See Man Page]'
complete -c db_stat -s s --description 'Display statistics for the specified database c… [See Man Page]'
complete -c db_stat -s t --description 'Display transaction region statistics, as descr… [See Man Page]'
complete -c db_stat -s V --description 'Write the library version number to the standar… [See Man Page]'
complete -c db_stat -s Z --description 'Reset the statistics after reporting them; vali… [See Man Page]'

