# db_upgrade
# Autogenerated from man page /usr/share/man/man1/db_upgrade.1
# using Darwin man parser
complete -c db_upgrade -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_upgrade -s N --description 'Do not acquire shared region mutexes while running.'
complete -c db_upgrade -s P --description 'Specify an environment password.'
complete -c db_upgrade -s s --description 'This flag is only meaningful when upgrading dat… [See Man Page]'
complete -c db_upgrade -s V --description 'Write the library version number to the standar… [See Man Page]'

