# db_verify
# Autogenerated from man page /usr/share/man/man1/db_verify.1
# using Darwin man parser
complete -c db_verify -s h --description 'Specify a home directory for the database envir… [See Man Page]'
complete -c db_verify -s o --description 'Skip the database checks for btree and duplicat… [See Man Page]'
complete -c db_verify -s N --description 'Do not acquire shared region mutexes while running.'
complete -c db_verify -s P --description 'Specify an environment password.'
complete -c db_verify -s q --description 'Suppress the printing of any error descriptions… [See Man Page]'
complete -c db_verify -s V --description 'Write the library version number to the standar… [See Man Page]'

