# ddns-confgen
# Autogenerated from man page /usr/share/man/man8/ddns-confgen.8
# using Deroffing man parser
complete -c ddns-confgen -s a --description 'Specifies the algorithm to use for the TSIG key.'
complete -c ddns-confgen -s h --description 'Prints a short summary of the options and argum… [See Man Page]'
complete -c ddns-confgen -s k --description 'Specifies the key name of the DDNS authentication key.'
complete -c ddns-confgen -s q --description 'Quiet mode: Print only the key, with no explana… [See Man Page]'
complete -c ddns-confgen -s r --description 'Specifies a source of random data for generatin… [See Man Page]'
complete -c ddns-confgen -s s --description 'Single host mode: The example named.'
complete -c ddns-confgen -s z --description 'zone mode: The example named.'

