# defaults
# Autogenerated from man page /usr/share/man/man1/defaults.1
# using Darwin man parser
complete -c defaults -o app --description 'The name of an application may be provided inst… [See Man Page]'
complete -c defaults -s g --description 'Specify the global domain.'
complete -c defaults -o string --description 'Allows the user to specify a string as the valu… [See Man Page]'
complete -c defaults -o data --description 'Allows the user to specify a bunch of raw data … [See Man Page]'
complete -c defaults -o 'int[eger]' --description 'Allows the user to specify an integer as the va… [See Man Page]'
complete -c defaults -o float --description 'Allows the user to specify a floating point num… [See Man Page]'
complete -c defaults -o 'bool[ean]' --description 'Allows the user to specify a boolean as the val… [See Man Page]'
complete -c defaults -o date --description 'Allows the user to specify a date as the value … [See Man Page]'
complete -c defaults -o array --description 'Allows the user to specify an array as the valu… [See Man Page]'
complete -c defaults -o array-add --description 'Allows the user to add new elements to the end … [See Man Page]'
complete -c defaults -o dict --description 'Allows the user to add a dictionary to the defa… [See Man Page]'
complete -c defaults -o dict-add --description 'Allows the user to add new key/value pairs to a… [See Man Page]'
complete -c defaults -o currentHost --description 'Restricts preferences operations to the host th… [See Man Page]'
complete -c defaults -o host --description 'Restricts preferences operations to \\fIhostname\\fR.'

