# df
# Autogenerated from man page /usr/share/man/man1/df.1
# using Darwin man parser
complete -c df -s a --description 'Show all mount points, including those that wer… [See Man Page]'
complete -c df -s b --description 'Use (the default) 512-byte blocks.'
complete -c df -s g --description 'Use 1073741824-byte (1-Gbyte) blocks rather than the default.'
complete -c df -s H --description '"Human-readable" output.'
complete -c df -s h --description '"Human-readable" output.'
complete -c df -s i --description 'Include statistics on the number of free inodes.'
complete -c df -s k --description 'Use 1024-byte (1-Kbyte) blocks, rather than the default.'
complete -c df -s l --description 'Only display information about locally-mounted filesystems.'
complete -c df -s m --description 'Use 1048576-byte (1-Mbyte) blocks rather than the default.'
complete -c df -s n --description 'Print out the previously obtained statistics fr… [See Man Page]'
complete -c df -s P --description 'Use (the default) 512-byte blocks.'
complete -c df -s T --description 'Only print out statistics for filesystems of th… [See Man Page]'
complete -c df -s t --description 'If used with no arguments, this option is a no-… [See Man Page]'

