# discoveryd_helper
# Autogenerated from man page /usr/share/man/man8/discoveryd_helper.8
# using Darwin man parser
complete -c discoveryd_helper -l loglevel --description 'Set the logging level for discoveryutil, not di… [See Man Page]'
complete -c discoveryd_helper -l logclass --description 'Set the logging class bitmap by subsystem using… [See Man Page]'
complete -c discoveryd_helper -l lognoclass --description 'Clear the logging class bitmap by subsystem usi… [See Man Page]'

