# discoveryd
# Autogenerated from man page /usr/share/man/man8/discoveryd.8
# using Darwin man parser
complete -c discoveryd -l loglevel --description 'Set the logging level for discoveryd to one of:… [See Man Page]'
complete -c discoveryd -l logclass --description 'Set the logging class bitmap by subsystem using… [See Man Page]'
complete -c discoveryd -l lognoclass --description 'Clear the logging class bitmap by subsystem usi… [See Man Page]'
complete -c discoveryd -l udsocket --description 'Use the "standard" or "experimental" unix domai… [See Man Page]'
complete -c discoveryd -l logto --description 'Send the discoveryd logging output to asl(3), s… [See Man Page]'
complete -c discoveryd -l xpcpid --description 'Become a debug version of discoveryd, which is … [See Man Page]'

