# discoveryutil
# Autogenerated from man page /usr/share/man/man8/discoveryutil.8
# using Darwin man parser
complete -c discoveryutil -l debug --description 'Interact with discoveryd not started by launchd(8).'
complete -c discoveryutil -l priv --description 'Interact with discoveryd started by launchd(8).'
complete -c discoveryutil -l loglevel --description 'Set the logging level for discoveryutil, not di… [See Man Page]'
complete -c discoveryutil -l logclass --description 'Set the logging class bitmap by subsystem using… [See Man Page]'
complete -c discoveryutil -l lognoclass --description 'Clear the logging class bitmap by subsystem usi… [See Man Page]'
complete -c discoveryutil -l xpcpid --description 'Connect to a debug version of discoveryd which … [See Man Page]'
complete -c discoveryutil -l timeout --description 'Set a timeout when communicating with discovery… [See Man Page]'

