# diskarbitrationd
# Autogenerated from man page /usr/share/man/man8/diskarbitrationd.8
# using Darwin man parser
complete -c diskarbitrationd -s d --description 'Report detailed information in /var/log/diskarbitrationd. log.'

