# dnctl
# Autogenerated from man page /usr/share/man/man8/dnctl.8
# using Darwin man parser
complete -c dnctl -s a --description 'While listing, show counter values.'
complete -c dnctl -s f --description 'Don\'t ask for confirmation for commands that ca… [See Man Page]'
complete -c dnctl -s h --description 'Displays a short help.'
complete -c dnctl -s n --description 'Only check syntax of the command strings, witho… [See Man Page]'
complete -c dnctl -s q --description 'While add Ns ing, zero Ns ing, resetlog Ns ging… [See Man Page]'
complete -c dnctl -s s --description 'While listing pipes, sort according to one of t… [See Man Page]'
complete -c dnctl -s v --description 'Be verbose.'

