# dot_clean
# Autogenerated from man page /usr/share/man/man1/dot_clean.1
# using Darwin man parser
complete -c dot_clean -s f --description 'Tp Flat merge.'
complete -c dot_clean -s h --description 'Help.  Prints verbose usage message.'
complete -c dot_clean -s m --description 'Always delete dot underbar files.'
complete -c dot_clean -s n --description 'Delete dot underbar file if there is no matching native file.'
complete -c dot_clean -s s --description 'Follow symbolic links.'
complete -c dot_clean -s v --description 'Print verbose output.'
complete -c dot_clean -l keep --description 'The default option.'

