# dscacheutil
# Autogenerated from man page /usr/share/man/man1/dscacheutil.1
# using Darwin man parser
complete -c dscacheutil -s h --description 'Lists the options for calling dscacheutil.'
complete -c dscacheutil -s q --description 'Initiate a query using standard calls.'
complete -c dscacheutil -s a --description 'Optional flag to q for a specific key with a value.'
complete -c dscacheutil -o cachedump --description 'Dumps an overview of the cache by default.'
complete -c dscacheutil -o buckets --description 'Used in conjunction with cachedump to also prin… [See Man Page]'
complete -c dscacheutil -o entries --description 'Used in conjunction with cachedump to dump deta… [See Man Page]'
complete -c dscacheutil -o configuration --description 'Prints current configuration information, such … [See Man Page]'
complete -c dscacheutil -o flushcache --description 'Flushes the entire cache.'
complete -c dscacheutil -o statistics --description 'Prints statistics from the cache including an o… [See Man Page]'

