# dsconfigldap
# Autogenerated from man page /usr/share/man/man1/dsconfigldap.1
# using Darwin man parser
complete -c dsconfigldap -s f --description 'Bindings will be established or dropped in conj… [See Man Page]'
complete -c dsconfigldap -s v --description 'This enables the logging to stdout of the detai… [See Man Page]'
complete -c dsconfigldap -s i --description 'You will be prompted for a password to use in c… [See Man Page]'
complete -c dsconfigldap -s s --description 'This ensures that no clear text passwords will … [See Man Page]'
complete -c dsconfigldap -s e --description 'This ensures that if the server is capable of s… [See Man Page]'
complete -c dsconfigldap -s m --description 'This ensures that man-in-the-middle capabilitie… [See Man Page]'
complete -c dsconfigldap -s g --description 'This ensures that packet signing capabilities w… [See Man Page]'
complete -c dsconfigldap -s x --description 'Connection to the LDAP server will only be made over SSL.'
complete -c dsconfigldap -s S --description 'Will skip updating the search policies.'
complete -c dsconfigldap -s N --description 'Will assume Yes for installing certificates.'
complete -c dsconfigldap -s h --description 'Display usage statement.'
complete -c dsconfigldap -s a --description 'This is either the fully qualified domain name … [See Man Page]'
complete -c dsconfigldap -s r --description 'This is either the fully qualified domain name … [See Man Page]'
complete -c dsconfigldap -s n --description 'This is the UI configuration label that is to b… [See Man Page]'
complete -c dsconfigldap -s c --description 'This is the name to be used for directory bindi… [See Man Page]'
complete -c dsconfigldap -s u --description 'Username of a privileged network user to be use… [See Man Page]'
complete -c dsconfigldap -s p --description 'Password for the privileged network user.'
complete -c dsconfigldap -s l --description 'Username of a local administrator.'
complete -c dsconfigldap -s q --description 'Password for the local administrator.'

