# dseditgroup
# Autogenerated from man page /usr/share/man/man8/dseditgroup.8
# using Darwin man parser
complete -c dseditgroup -s o --description 'If "read" then the parameters of the specified … [See Man Page]'
complete -c dseditgroup -s p --description 'You will be prompted for a password to use in c… [See Man Page]'
complete -c dseditgroup -s q --description 'This disables interactive verification of repla… [See Man Page]'
complete -c dseditgroup -s v --description 'This enables the logging of the DirectoryServic… [See Man Page]'
complete -c dseditgroup -s m --description 'The username of the account to verify group mem… [See Man Page]'
complete -c dseditgroup -s n --description 'Directory Service node name such as /LDAPv3/ldap. company.'
complete -c dseditgroup -s u --description 'Username of a user that has administrative priv… [See Man Page]'
complete -c dseditgroup -s P --description 'Password to use in conjunction with the specified username.'
complete -c dseditgroup -s a --description 'The name of the record to be added to the group… [See Man Page]'
complete -c dseditgroup -s d --description 'The name of the record to be deleted from the g… [See Man Page]'
complete -c dseditgroup -s t --description 'The type of the record to be added to or delete… [See Man Page]'
complete -c dseditgroup -s T --description 'The type of the group record to be created or m… [See Man Page]'
complete -c dseditgroup -s L --description 'If used with computergroup will also maintain t… [See Man Page]'
complete -c dseditgroup -s i --description 'This is a group id.'
complete -c dseditgroup -s g --description 'This is a text representation of an 128 bit id.'
complete -c dseditgroup -s r --description 'This is a simple text string.'
complete -c dseditgroup -s k --description 'This is a simple text string.'
complete -c dseditgroup -s c --description 'This is a simple text string.'
complete -c dseditgroup -s s --description 'The number of seconds that this record is deeme… [See Man Page]'

