# dsexport
# Autogenerated from man page /usr/share/man/man1/dsexport.1
# using Darwin man parser
complete -c dsexport -l N --description 'Export all attributes, including native attributes.'
complete -c dsexport -s r --description 'Comma-separated list of records to export from … [See Man Page]'
complete -c dsexport -s e --description 'Comma-separated list of attributes that should not be exported.'
complete -c dsexport -s a --description 'Address of the desired proxy machine.'
complete -c dsexport -s u --description 'Username to use for the proxy connection.'
complete -c dsexport -s p --description 'Password to use for the proxy connection.'

