# dsmemberutil
# Autogenerated from man page /usr/share/man/man1/dsmemberutil.1
# using Darwin man parser
complete -c dsmemberutil -s h --description 'Lists the options for calling dsmemberutil.'
complete -c dsmemberutil -s v --description 'Causes dsmemberutil to operate in verbose mode.'
complete -c dsmemberutil -s u --description 'Using user with UID.'
complete -c dsmemberutil -s U --description 'Using user with name.'
complete -c dsmemberutil -s s --description 'Using user with SID.'
complete -c dsmemberutil -s x --description 'Using user with UUID.'
complete -c dsmemberutil -s g --description 'Using group with GID.'
complete -c dsmemberutil -s G --description 'Using group with name.'
complete -c dsmemberutil -s S --description 'Using group with SID.'
complete -c dsmemberutil -s X --description 'Using group with UUID El EXAMPLES Pp -tag -widt… [See Man Page]'

