# du
# Autogenerated from man page /usr/share/man/man1/du.1
# using Darwin man parser
complete -c du -s a --description 'Display an entry for each file in a file hierarchy.'
complete -c du -s c --description 'Display a grand total.'
complete -c du -s d --description 'Display an entry for all files and directories … [See Man Page]'
complete -c du -s H --description 'Symbolic links on the command line are followed… [See Man Page]'
complete -c du -s h --description '"Human-readable" output.'
complete -c du -s I --description 'Ignore files and directories matching the specified mask.'
complete -c du -s g --description 'Display block counts in 1073741824-byte (1-Gbyte) blocks.'
complete -c du -s k --description 'Display block counts in 1024-byte (1-Kbyte) blocks.'
complete -c du -s L --description 'Symbolic links on the command line and in file … [See Man Page]'
complete -c du -s m --description 'Display block counts in 1048576-byte (1-Mbyte) blocks.'
complete -c du -s P --description 'No symbolic links are followed.  This is the default.'
complete -c du -s r --description 'Generate messages about directories that cannot… [See Man Page]'
complete -c du -s s --description 'Display an entry for each specified file.'
complete -c du -s x --description 'File system mount points are not traversed.'

