# dynamic_pager
# Autogenerated from man page /usr/share/man/man8/dynamic_pager.8
# using Darwin man parser
complete -c dynamic_pager -s F --description 'The base name of the filename to use for the swapfiles.'

