# ed
# Autogenerated from man page /usr/share/man/man1/ed.1
# using Darwin man parser
complete -c ed -s s --description 'Suppress diagnostics.'
complete -c ed -s x --description 'Prompt for an encryption key to be used in subs… [See Man Page]'
complete -c ed -s p --description 'Specify a command prompt.'

