# efix
# Autogenerated from man page /usr/share/man/man1/efix.1
# using Deroffing man parser
complete -c efix -s i --description 'the input image is in format f.'
complete -c efix -s o --description 'write the output in format f.   Default is tiffg3.'
complete -c efix -s n --description 'use the printf(3) pattern path to generate the … [See Man Page]'
complete -c efix -s v --description 'print messages of type in string lvl.'
complete -c efix -s f --description 'use font file fnt for text.'
complete -c efix -s s --description 'scale the input by a factor of X horizontally and Y vertically.'
complete -c efix -s d --description 'displace the output right by R and down by D (o… [See Man Page]'
complete -c efix -s p --description 'truncate or pad the output to generate an image… [See Man Page]'
complete -c efix -s r --description 'assume an output device resolution of X by Y dots per inch.'
complete -c efix -s R --description 'assume an input device resolution of X by Y dots per inch.'
complete -c efix -s l --description 'place n lines per page during text input.  Default is 66.'
complete -c efix -s O --description 'overlay (logical OR) the image from file f into the output.'
complete -c efix -s M --description 'ignore all other options and copy the standard … [See Man Page]'

