# emlog
# Autogenerated from man page /usr/share/man/man8/emlog.pl.8
# using Darwin man parser
complete -c emlog -s p --description 'Tells emlog to listen on the given local port n… [See Man Page]'
complete -c emlog -s l --description 'Tells emlog to process a single line of text then quit.'

