# emond
# Autogenerated from man page /usr/share/man/man8/emond.8
# using Darwin man parser
complete -c emond -s r --description 'Tells emond to look for rules files in the specified path.'
complete -c emond -s c --description 'Tells emond to look in specified path for its config file.'

