# encode_keychange
# Autogenerated from man page /usr/share/man/man1/encode_keychange.1
# using Deroffing man parser
complete -c encode_keychange -s E --description '<engineID> is intepreted as a hex string when p… [See Man Page]'
complete -c encode_keychange -s f --description 'Force passphrases to be read from standard input.'
complete -c encode_keychange -s h --description 'Display the help message.'
complete -c encode_keychange -s N --description 'Passphrase used to generate the new Ku.'
complete -c encode_keychange -s O --description 'Passphrase used to generate the old Ku.'
complete -c encode_keychange -s P --description 'Turn off the prompt for passphrases when gettin… [See Man Page]'
complete -c encode_keychange -s v --description 'Be verbose.'
complete -c encode_keychange -s V --description 'Echo passphrases to terminal.'

