# erb
# Autogenerated from man page /usr/share/man/man1/erb.1
# using Darwin man parser
complete -c erb -l version --description 'Prints the version of erb.  Pp.'
complete -c erb -s E --description '.'
complete -c erb -l encoding --description 'Specifies the default value(s) for external enc… [See Man Page]'
complete -c erb -s P --description 'Evaluates lines starting with "%" as Ruby code … [See Man Page]'
complete -c erb -s S --description 'Specifies the safe level in which eRuby script will run.  Pp.'
complete -c erb -s T --description 'Specifies trim mode (default 0).'
complete -c erb -s U --description 'can be one of Sets the default value for intern… [See Man Page]'
complete -c erb -s d --description '.'
complete -c erb -l debug --description 'Turns on debug mode.  "$DEBUG" will be set to true.  Pp.'
complete -c erb -s h --description '.'
complete -c erb -l help --description 'Prints a summary of the options.  Pp.'
complete -c erb -s n --description 'Used with x.'
complete -c erb -s v --description 'Enables verbose mode.  "$VERBOSE" will be set to true.  Pp.'
complete -c erb -s x --description 'Converts the eRuby script into Ruby script and … [See Man Page]'

