# errinfo
# Autogenerated from man page /usr/share/man/man1/errinfo.1m
# using Deroffing man parser
complete -c errinfo -s c --description 'counts - print an aggregate style report contai… [See Man Page]'
complete -c errinfo -s p --description 'examine this PID only.'
complete -c errinfo -s n --description 'examine processes with ths name only (eg, "ls") EXAMPLES.'

