# exfat
# Autogenerated from man page /usr/share/man/man8/exfat.util.8
# using Darwin man parser
complete -c exfat -s p --description 'Probe the device to determine whether it contai… [See Man Page]'
complete -c exfat -s k --description 'Return the volume UUID of the ExFAT file system on device.'
complete -c exfat -s s --description 'Set a new UUID for the ExFAT file system on dev… [See Man Page]'
complete -c exfat -s m --description 'Deprecated.'
complete -c exfat -s u --description 'Deprecated.  Unmount the file system on device.'

