# expand
# Autogenerated from man page /usr/share/man/man1/expand.1
# using Darwin man parser
complete -c expand -s a --description 'expand ( unexpand only.'
complete -c expand -s t --description 'Set tab stops at column positions tab1 , tab2 , .  , tabn.'

