# fax
# Autogenerated from man page /usr/share/man/man1/fax.1
# using Deroffing man parser
complete -c fax -s l --description 'use low (96 line per inch) resolution.'
complete -c fax -s v --description 'display verbose messages for debugging.'
complete -c fax -s m --description 'the phone call has already been dialed manually… [See Man Page]'

