# fc-pattern
# Autogenerated from man page /usr/local/share/man/man1/fc-pattern.1
# using Type1
complete -c fc-pattern -s c --description 'Perform config substitution on pattern.'
complete -c fc-pattern -s d --description 'Perform default substitution on pattern.'
complete -c fc-pattern -s f --description 'Format output according to the format specifier format.'
complete -c fc-pattern -s V --description 'Show version of the program and exit.'
complete -c fc-pattern -s h --description 'Show summary of options.'

