# fc-validate
# Autogenerated from man page /usr/local/share/man/man1/fc-validate.1
# using Type1
complete -c fc-validate -s i --description 'Only query face indexed index of each file.'
complete -c fc-validate -s l --description 'Set lang as a language instead of current locale.'
complete -c fc-validate -s v --description 'Show more detailed information.'
complete -c fc-validate -s V --description 'Show version of the program and exit.'
complete -c fc-validate -s h --description 'Show summary of options.'

