# fddist
# Autogenerated from man page /usr/share/man/man1/fddist.1m
# using Deroffing man parser
complete -c fddist -s r --description 'reads only.'
complete -c fddist -s w --description 'writes only.'

