# fdesetup
# Autogenerated from man page /usr/share/man/man8/fdesetup.8
# using Darwin man parser
complete -c fdesetup -o defer --description 'Defer enabling FileVault until the user passwor… [See Man Page]'
complete -c fdesetup -o user --description 'Short user name.  Pp.'
complete -c fdesetup -o uuid --description 'User UUID in canonical form: 11111111-2222-3333… [See Man Page]'
complete -c fdesetup -o usertoadd --description 'Additional user(s) to be added to FileVault.  Pp.'
complete -c fdesetup -o inputplist --description 'Acquire configuration information from stdin wh… [See Man Page]'
complete -c fdesetup -o prompt --description 'Always prompt for information.  Pp.'
complete -c fdesetup -o forcerestart --description 'Force a normal restart after FileVault has been… [See Man Page]'
complete -c fdesetup -o authrestart --description 'Do an authenticated restart after a successful enable occurs.'
complete -c fdesetup -o outputplist --description 'Outputs the recovery key and additional system … [See Man Page]'
complete -c fdesetup -o keychain --description 'Use the institutional recovery key stored in /L… [See Man Page]'
complete -c fdesetup -o certificate --description 'Use the certificate data located at the path.'
complete -c fdesetup -o key --description 'Use the keychain file located at the path conta… [See Man Page]'
complete -c fdesetup -o norecoverykey --description 'Do not return a personal recovery key.  Pp.'
complete -c fdesetup -o forceatlogin --description 'When using the -defer option, prompt the design… [See Man Page]'
complete -c fdesetup -o dontaskatlogout --description 'When using the -defer option, the default actio… [See Man Page]'
complete -c fdesetup -o extended --description 'Return extended output information for certain commands.'

