# fdisk
# Autogenerated from man page /usr/share/man/man8/fdisk.8
# using Darwin man parser
complete -c fdisk -s i --description 'Initialize the MBR sector.'
complete -c fdisk -s a --description 'Specify an automatic partitioning style.'
complete -c fdisk -s e --description 'Edit existing MBR sectors.'
complete -c fdisk -s f --description 'Specifies an alternate MBR template file.'
complete -c fdisk -s u --description 'Update MBR code, preserving existing partition table.'
complete -c fdisk -s y --description 'Do not ask for confirmation before writing.'
complete -c fdisk -s d --description 'Dump partition table in a format readable by the -r option.'
complete -c fdisk -s r --description 'Read a partition table from the standard input.'
complete -c fdisk -s t --description 'Test if the disk is partitioned.'
complete -c fdisk -s S --description 'Specify the disk size in blocks.'
complete -c fdisk -s b --description 'Specify the number of bytes per disk block.'

