# femail
# Autogenerated from man page /usr/share/man/man8/femail.8
# using Darwin man parser
complete -c femail -s 4 --description 'Only use IPv4.'
complete -c femail -s 6 --description 'Only use IPv6.'
complete -c femail -s F --description 'Set the sender\'s name to name.'
complete -c femail -s f --description 'Set the sender address to from.'
complete -c femail -s t --description 'Read recipients from the message given on stdin… [See Man Page]'
complete -c femail -s v --description 'Enable verbose operation.'

