# find
# Autogenerated from man page /usr/share/man/man1/find.1
# using Darwin man parser
complete -c find -s E --description 'Interpret regular expressions followed by -rege… [See Man Page]'
complete -c find -s H --description 'Cause the file information and file type (see s… [See Man Page]'
complete -c find -s L --description 'Cause the file information and file type (see s… [See Man Page]'
complete -c find -s P --description 'Cause the file information and file type (see s… [See Man Page]'
complete -c find -s X --description 'Permit find to be safely used in conjunction with xargs 1.'
complete -c find -s d --description 'Cause find to perform a depth-first traversal, i. e.'
complete -c find -s f --description 'Specify a file hierarchy for find to traverse.'
complete -c find -s s --description 'Cause find to traverse the file hierarchies in … [See Man Page]'
complete -c find -s x --description 'Prevent find from descending into directories t… [See Man Page]'

