# findmydeviced
# Autogenerated from man page /usr/share/man/man8/findmydeviced.1
# using Darwin man parser
complete -c findmydeviced -s a --description 'Description of -a flag.'
complete -c findmydeviced -s b --description 'Description of -b flag \\" Ends the list Pp .'

