# fingerd
# Autogenerated from man page /usr/share/man/man8/fingerd.8
# using Darwin man parser
complete -c fingerd -s s --description 'Enable secure mode.'
complete -c fingerd -s l --description 'Enable logging.'
complete -c fingerd -s p --description 'Use an alternate program as the local information provider.'

