# finger
# Autogenerated from man page /usr/share/man/man1/finger.1
# using Darwin man parser
complete -c finger -s 4 --description 'Forces finger to use IPv4 addresses only.'
complete -c finger -s 6 --description 'Forces finger to use IPv6 addresses only.'
complete -c finger -s g --description 'This option restricts the gecos output to only … [See Man Page]'
complete -c finger -s h --description 'When used in conjunction with the s option, the… [See Man Page]'
complete -c finger -s k --description 'Disable all use of utmpx 5.'
complete -c finger -s l --description 'Produce a multi-line format displaying all of t… [See Man Page]'
complete -c finger -s m --description 'Prevent matching of user names.'
complete -c finger -s o --description 'When used in conjunction with the s option, the… [See Man Page]'
complete -c finger -s p --description 'Prevent the l option of finger from displaying … [See Man Page]'
complete -c finger -s s --description 'Display the user\'s login name, real name, termi… [See Man Page]'

