# firmwarepasswd
# Autogenerated from man page /usr/share/man/man8/firmwarepasswd.8
# using Darwin man parser
complete -c firmwarepasswd -o setpasswd --description 'Prompts to add a new firmware password or chang… [See Man Page]'
complete -c firmwarepasswd -o setmode --description 'Set the mode to "command" or "full".'
complete -c firmwarepasswd -o mode --description 'Displays the current mode if one is set.'
complete -c firmwarepasswd -o check --description 'Displays whether or not a firmware password is set.  Pp.'
complete -c firmwarepasswd -o delete --description 'Prompts for password and clears both password a… [See Man Page]'
complete -c firmwarepasswd -o verify --description 'Prompts for password and displays success if correct.'
complete -c firmwarepasswd -o unlockseed --description 'Generates a firmware password recovery key.'
complete -c firmwarepasswd -s h --description 'Displays a list of all the commands available i… [See Man Page]'

