# footprint
# Autogenerated from man page /usr/share/man/man1/footprint.1
# using Darwin man parser
complete -c footprint -o categories --description 'Detailed output on a per-VM-region type level (medium detail).'
complete -c footprint -o regions --description 'Display all memory objects and associated regio… [See Man Page]'
complete -c footprint -o swapped --description 'Display swapped bytes information where applicable.'
complete -c footprint -o graphics --description 'Gather graphics data if available (platform dep… [See Man Page]'
complete -c footprint -o collapseSharing --description 'Do not group shared memory output by process.'
complete -c footprint -o targetChildren --description 'Gather footprint information for the set of pro… [See Man Page]'
complete -c footprint -o skipIdleExitClean --description 'Do not gather information on any processes that… [See Man Page]'

