# freetype-config
# Autogenerated from man page /usr/local/share/man/man1/freetype-config.1
# using Deroffing man parser
complete -c freetype-config -l prefix --description 'Return the prefix value of the installed FreeTy… [See Man Page]'
complete -c freetype-config -l exec-prefix --description 'Return the executable prefix value of the insta… [See Man Page]'
complete -c freetype-config -l ftversion --description 'Return the FreeType version number.'
complete -c freetype-config -l version --description 'Return the `libtool version\' of the FreeType library.'
complete -c freetype-config -l libtool --description 'Return the library name for linking with libtool.'
complete -c freetype-config -l libs --description 'Return compiler flags for linking with the inst… [See Man Page]'
complete -c freetype-config -l cflags --description 'Return compiler flags for compiling against the… [See Man Page]'
complete -c freetype-config -l static --description 'Make command line options display flags for static linking.'

