# fs_usage
# Autogenerated from man page /usr/share/man/man1/fs_usage.1
# using Darwin man parser
complete -c fs_usage -s e --description 'Specifying the e option generates output that e… [See Man Page]'
complete -c fs_usage -s w --description 'Specifying the w option forces a wider, more de… [See Man Page]'
complete -c fs_usage -s f --description 'Specifying the f option turns on output filteri… [See Man Page]'
complete -c fs_usage -s b --description 'Specifying the b option annotates disk I/O even… [See Man Page]'
complete -c fs_usage -s t --description 'Specifies a run timeout in seconds.'
complete -c fs_usage -s R --description 'Specifies a raw trace file to process.  ==========.'
complete -c fs_usage -s S --description 'If R is selected, specifies the start time in m… [See Man Page]'
complete -c fs_usage -s E --description 'If R is selected, specifies the ending time in … [See Man Page]'

