# fsck_msdos
# Autogenerated from man page /usr/share/man/man8/fsck_msdos.8
# using Darwin man parser
complete -c fsck_msdos -s q --description 'Causes fsck_msdos to quickly check whether the … [See Man Page]'
complete -c fsck_msdos -s f --description 'This option is ignored by fsck_msdos and is pre… [See Man Page]'
complete -c fsck_msdos -s n --description 'Causes fsck_msdos to assume no as the answer to… [See Man Page]'
complete -c fsck_msdos -s p --description 'Preen the specified file systems.'
complete -c fsck_msdos -s y --description 'Causes fsck_msdos to assume yes as the answer t… [See Man Page]'

