# fsck
# Autogenerated from man page /usr/share/man/man8/fsck.8
# using Darwin man parser
complete -c fsck -s f --description 'Force fsck to check `clean\' filesystems when preening.'
complete -c fsck -s l --description 'Limit the number of parallel checks to the numb… [See Man Page]'
complete -c fsck -s p --description '"Preen" mode, described above.'
complete -c fsck -s q --description 'Do a quick check to determine if the filesystem… [See Man Page]'
complete -c fsck -s y --description 'Assume a yes response to all questions asked by… [See Man Page]'
complete -c fsck -s n --description 'Assume a no response to all questions asked by … [See Man Page]'

