# fsck_hfs
# Autogenerated from man page /usr/share/man/man8/fsck_hfs.8
# using Darwin man parser
complete -c fsck_hfs -s c --description 'Specify the size of the cache used by fsck_hfs internally.'
complete -c fsck_hfs -s d --description 'Display debugging information.'
complete -c fsck_hfs -s D --description 'Print extra debugging information.'
complete -c fsck_hfs -s b --description 'Specify the size, in bytes, of the physical blo… [See Man Page]'
complete -c fsck_hfs -s B --description 'Print the files containing the physical blocks … [See Man Page]'
complete -c fsck_hfs -s f --description 'When used with the p option, force fsck_hfs to … [See Man Page]'
complete -c fsck_hfs -s g --description 'Causes fsck_hfs to generate its output strings in GUI format.'
complete -c fsck_hfs -s x --description 'Causes fsck_hfs to generate its output strings … [See Man Page]'
complete -c fsck_hfs -s l --description 'Lock down the file system and perform a test-only check.'
complete -c fsck_hfs -s m --description 'Mode is an octal number that will be used to se… [See Man Page]'
complete -c fsck_hfs -s p --description 'Preen the specified file systems.'
complete -c fsck_hfs -s q --description 'Causes fsck_hfs to quickly check whether the vo… [See Man Page]'
complete -c fsck_hfs -s y --description 'Always attempt to repair any damage that is found.'
complete -c fsck_hfs -s n --description 'Never attempt to repair any damage that is found.'
complete -c fsck_hfs -s E --description 'Cause fsck_hfs to exit (with a value of 47) if … [See Man Page]'
complete -c fsck_hfs -s S --description 'Cause fsck_hfs to scan the entire device lookin… [See Man Page]'
complete -c fsck_hfs -s R --description 'Rebuilds the requested btree.'
complete -c fsck_hfs -s r --description 'Rebuild the catalog btree.   This is synonymous with .'

