# fuser
# Autogenerated from man page /usr/share/man/man1/fuser.1
# using Deroffing man parser
complete -c fuser -s c --description 'The file is treated as a mount point and the ut… [See Man Page]'
complete -c fuser -s f --description 'The report shall be only for the named files.'
complete -c fuser -s u --description 'The user name, in parentheses, associated with … [See Man Page]'

