# fwkdp
# Autogenerated from man page /usr/share/man/man1/fwkdp.1
# using Darwin man parser
complete -c fwkdp -l setargs --description 'Sets the nvram boot-args on the current machine… [See Man Page]'
complete -c fwkdp -l proxy --description 'Use proxy mode only.'
complete -c fwkdp -l gdb --description 'Use proxy mode only and automatically start gdb… [See Man Page]'
complete -c fwkdp -l core --description 'Use core dump receive mode only.'
complete -c fwkdp -l verbose --description 'Verbose mode.'
complete -c fwkdp -l disable --description 'Sets the nvram boot-args on the current machine… [See Man Page]'
complete -c fwkdp -l erase --description 'Deletes the boot-args variable from nvram.'
complete -c fwkdp -l ioff --description 'Turns off interactive mode.'
complete -c fwkdp -l restart --description 'Automatically restarts the machine only after t… [See Man Page]'
complete -c fwkdp -l help --description 'Displays usage info for fwkdp.'

