# fwkpfv
# Autogenerated from man page /usr/share/man/man1/fwkpfv.1
# using Darwin man parser
complete -c fwkpfv -l appendlog --description 'Append output logging to /tmp/fwkpf. log.'
complete -c fwkpfv -l openlog --description 'Open log file with Console. app.  Only valid with a Ns \\&.'
complete -c fwkpfv -l newlog --description 'Create a new log file, rather than append.'
complete -c fwkpfv -l prefix --description 'Prefix logger machine\'s ID to each log.'
complete -c fwkpfv -l publish --description 'Do not publish FireWire unit directory keys.'
complete -c fwkpfv -l single --description 'Use a single window even if multiple loggers are present.'
complete -c fwkpfv -l buffer --description 'Sets the host\'s psuedo address space queue buff… [See Man Page]'
complete -c fwkpfv -l file --description 'Sets the log file path, if in use, to path Ns g… [See Man Page]'
complete -c fwkpfv -l setargs --description 'Sets the nvram boot-args on the current machine… [See Man Page]'
complete -c fwkpfv -l setpm --description 'Sets the nvram boot-args on the current machine… [See Man Page]'
complete -c fwkpfv -l disable --description 'Sets the nvram boot-args on the current machine… [See Man Page]'
complete -c fwkpfv -l erase --description 'Deletes the boot-args variable from nvram.'
complete -c fwkpfv -l ioff --description 'Turns off interactive mode.'
complete -c fwkpfv -l restart --description 'Automatically restarts the machine only after t… [See Man Page]'
complete -c fwkpfv -l help --description 'Displays usage info for fwkpfv.'

