# gen_bridge_metadata
# Autogenerated from man page /usr/share/man/man1/gen_bridge_metadata.1
# using Darwin man parser
complete -c gen_bridge_metadata -s f --description 'Generates metadata for the given framework.'
complete -c gen_bridge_metadata -s p --description 'Generates metadata based on the private headers… [See Man Page]'
complete -c gen_bridge_metadata -s F --description 'Selects the metadata format that will be generated.'
complete -c gen_bridge_metadata -s e --description 'Considers the given exception file when generat… [See Man Page]'
complete -c gen_bridge_metadata -l 64-bit --description '(This option is included for backwards compatib… [See Man Page]'
complete -c gen_bridge_metadata -l no-32-bit --description 'Do not write the 32-bit annotations to the fina… [See Man Page]'
complete -c gen_bridge_metadata -l no-64-bit --description 'Do not write the 64-bit annotations to the fina… [See Man Page]'
complete -c gen_bridge_metadata -s c --description 'Provides custom flags that will be passed to the C compiler.'
complete -c gen_bridge_metadata -s C --description 'Provides custom flags that will be passed to th… [See Man Page]'
complete -c gen_bridge_metadata -s o --description 'Writes the output to the given file.'
complete -c gen_bridge_metadata -s h --description 'Prints a summary of the options.  Pp.'
complete -c gen_bridge_metadata -s d --description 'Turns on debugging messages.'
complete -c gen_bridge_metadata -s v --description 'Shows the version of the program.'

