# genstrings
# Autogenerated from man page /usr/share/man/man1/genstrings.1
# using Darwin man parser
complete -c genstrings -s a --description 'Allows the output to be appended to the old output files.'
complete -c genstrings -s s --description 'Substitutes \\fIroutine\\fR for NSLocalizedString.'
complete -c genstrings -o skipTable --description 'Causes genstrings to skip over the file for \\fITable\\fR.'
complete -c genstrings -o noPositionalParameters --description 'Turns off generation of positional parameters.'
complete -c genstrings -s u --description 'Allow unicode characters in the value of strings files.'
complete -c genstrings -o macRoman --description 'For compatibility, read source files using Mac Roman encoding.'
complete -c genstrings -s q --description 'Turns off multiple key/value pairs warning.'
complete -c genstrings -s o --description 'Specifies what directory the tables should be created in.  El .'

