# git-push
# Autogenerated from man page /usr/local/share/man/man1/git-push.1
# using Deroffing man parser
complete -c git-push -l signed --description 'GPG-sign the push request to update refs on the… [See Man Page]'

