# git-pack-objects
# Autogenerated from man page /usr/local/share/man/man1/git-pack-objects.1
# using Deroffing man parser
complete -c git-pack-objects -l not --description 'or.'
complete -c git-pack-objects -l shallow --description 'lines are also accepted.'

