# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
# using Deroffing man parser
complete -c git-format-patch -l signature-file --description 'Works just like --signature except the signatur… [See Man Page]'

