# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
# using Deroffing man parser
complete -c git-fetch -l refmap --description 'When fetching refs listed on the command line, … [See Man Page]'

