# git-revert
# Autogenerated from man page /usr/local/share/man/man1/git-revert.1
# using Deroffing man parser
complete -c git-revert -o 'S[<key-id>]' -l 'gpg-sign[' --description 'GPG-sign commits.'

