# git-credential-store
# Autogenerated from man page /usr/local/share/man/man1/git-credential-store.1
# using Deroffing man parser
complete -c git-credential-store -l file --description 'Use <path> to store credentials.'

