# git-send-pack
# Autogenerated from man page /usr/local/share/man/man1/git-send-pack.1
# using Deroffing man parser
complete -c git-send-pack -l stdin --description 'Take the list of refs from stdin, one per line.'
complete -c git-send-pack -l stateless-rpc --description 'is specified together with this option then the… [See Man Page]'

