# git-repack
# Autogenerated from man page /usr/local/share/man/man1/git-repack.1
# using Deroffing man parser
complete -c git-repack -s b -l write-bitmap-index --description 'Write a reachability bitmap index as part of the repack.'
complete -c git-repack -l pack-kept-objects --description 'Include objects in . keep files when repacking.'

