# git-patch-id
# Autogenerated from man page /usr/local/share/man/man1/git-patch-id.1
# using Deroffing man parser
complete -c git-patch-id -l stable --description 'Use a "stable" sum of hashes as the patch ID.'
complete -c git-patch-id -l unstable --description 'Use an "unstable" hash as the patch ID.'

