# git-stash
# Autogenerated from man page /usr/local/share/man/man1/git-stash.1
# using Deroffing man parser
complete -c git-stash -l '[no-]keep-index]' --description 'Save your local modifications to a new stash, a… [See Man Page]'

