# git-update-index
# Autogenerated from man page /usr/local/share/man/man1/git-update-index.1
# using Deroffing man parser
complete -c git-update-index -l split-index -l no-split-index --description 'Enable or disable split index mode.'

