# git-reset
# Autogenerated from man page /usr/local/share/man/man1/git-reset.1
# using Deroffing man parser
complete -c git-reset -s N --description 'is specified, removed paths are marked as inten… [See Man Page]'

