# git-replace
# Autogenerated from man page /usr/local/share/man/man1/git-replace.1
# using Deroffing man parser
complete -c git-replace -l edit --description 'Edit an object\\(cqs content interactively.'
complete -c git-replace -l raw --description 'When editing, provide the raw object contents r… [See Man Page]'
complete -c git-replace -l graft --description 'Create a graft commit.'

