# git-difftool
# Autogenerated from man page /usr/local/share/man/man1/git-difftool.1
# using Deroffing man parser
complete -c git-difftool -l '[no-]trust-exit-code' --description 'git-difftool invokes a diff tool individually on each file.'
complete -c git-difftool -l trust-exit-code --description 'to make git-difftool exit when an invoked diff … [See Man Page]'

