# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
# using Deroffing man parser
complete -c git-log -l reflog --description 'Pretend as if all objects mentioned by reflogs … [See Man Page]'
complete -c git-log -l indexed-objects --description 'Pretend as if all trees and blobs used by the i… [See Man Page]'
complete -c git-log -l 'show-linear-break[' --description 'When --graph is not used, all history branches … [See Man Page]'

