# git-verify-commit
# Autogenerated from man page /usr/local/share/man/man1/git-verify-commit.1
# using Deroffing man parser
complete -c git-verify-commit -s v -l verbose --description 'Print the contents of the commit object before validating it.'

