# git-am
# Autogenerated from man page /usr/local/share/man/man1/git-am.1
# using Deroffing man parser
complete -c git-am -l patch-format --description 'By default the command will try to detect the p… [See Man Page]'
complete -c git-am -o 'S[<keyid>]' -l 'gpg-sign[' --description 'GPG-sign commits.'

