# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
# using Deroffing man parser
complete -c git-config -l output --description 'option.  Git will attempt to detect whether meld supports.'
complete -c git-config -l 'output.' --description 'mergetool. keepBackup.'
complete -c git-config -l pack-kept-objects --description 'was passed.  See git-repack(1) for details.'
complete -c git-config -l write-bitmap-index --description 'or repack. writeBitmaps).  repack. writeBitmaps.'

