# git-commit-tree
# Autogenerated from man page /usr/local/share/man/man1/git-commit-tree.1
# using Deroffing man parser
complete -c git-commit-tree -l 'gpg-sign[' --description 'GPG-sign commit.'
complete -c git-commit-tree -l no-gpg-sign --description 'Countermand commit.'

