# git-fast-export
# Autogenerated from man page /usr/local/share/man/man1/git-fast-export.1
# using Deroffing man parser
complete -c git-fast-export -l anonymize --description 'Anonymize the contents of the repository while … [See Man Page]'
complete -c git-fast-export -l refspec --description 'Apply the specified refspec to each ref exported.'

