# git-submodule
# Autogenerated from man page /usr/local/share/man/man1/git-submodule.1
# using Deroffing man parser
complete -c git-submodule -l checkout --description 'This option is only valid for the update command.'

