# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
# using Deroffing man parser
complete -c git-rev-list -l reflog --description 'Pretend as if all objects mentioned by reflogs … [See Man Page]'
complete -c git-rev-list -l indexed-objects --description 'Pretend as if all trees and blobs used by the i… [See Man Page]'
complete -c git-rev-list -l use-bitmap-index --description 'Try to speed up the traversal using the pack bi… [See Man Page]'
complete -c git-rev-list -l 'show-linear-break[' --description 'When --graph is not used, all history branches … [See Man Page]'

