# git-send-email
# Autogenerated from man page /usr/local/share/man/man1/git-send-email.1
# using Deroffing man parser
complete -c git-send-email -l '[no-]cc-cover' --description 'If this is set, emails found in Cc: headers in … [See Man Page]'
complete -c git-send-email -l '[no-]to-cover' --description 'If this is set, emails found in To: headers in … [See Man Page]'

