# git-rev-parse
# Autogenerated from man page /usr/local/share/man/man1/git-rev-parse.1
# using Deroffing man parser
complete -c git-rev-parse -l shared-index-path --description 'Show the path to the shared index file in split… [See Man Page]'

