# GoogleSyncMigrate
# Autogenerated from man page /usr/share/man/man1/GoogleSyncMigrate.1
# using Darwin man parser
complete -c GoogleSyncMigrate -s a --description 'Description of -a flag.'
complete -c GoogleSyncMigrate -s b --description 'Description of -b flag \\" Ends the list Pp .'

