# groff
# Autogenerated from man page /usr/share/man/man1/groff.1
# using Deroffing man parser
complete -c groff -s p --description 'and.'
complete -c groff -s l --description 'See groff_font (5) and the man pages of the out… [See Man Page]'
complete -c groff -s P --description 'to pass options to output devices; for example,… [See Man Page]'

