# groffer
# Autogenerated from man page /usr/share/man/man1/groffer.1
# using Deroffing man parser
complete -c groffer -l shell --description '.'
complete -c groffer -l foreground --description '.'
complete -c groffer -l resolution --description '.'
complete -c groffer -l x-viewer -o geometry --description '# # some shell commands if test "$DISPLAY" = ""… [See Man Page]'

