# grog
# Autogenerated from man page /usr/share/man/man1/grog.1
# using Deroffing man parser
complete -c grog -s e --description '.'
complete -c grog -o man --description '.'
complete -c grog -o me --description '.'
complete -c grog -o mm --description '.'
complete -c grog -o mom --description '.'
complete -c grog -o ms --description '.'
complete -c grog -o mdoc --description '.'
complete -c grog -o mdoc-old --description '.'
complete -c grog -s p --description '.'
complete -c grog -s R --description '.'
complete -c grog -s g --description '.'
complete -c grog -s G --description '.'
complete -c grog -s s --description 'and.'
complete -c grog -s t --description 'are required for printing files , and prints th… [See Man Page]'
complete -c grog -s C --description '(which is also passed on) to enable compatibility mode, and.'
complete -c grog -s v --description 'to print the version number.'
complete -c grog -o Tdvi --description 'option.'

