# gunzip
# Autogenerated from man page /usr/share/man/man1/gunzip.1
# using Darwin man parser
complete -c gunzip -s 1 --description '.'
complete -c gunzip -s 2 --description '.'
complete -c gunzip -s 9 --description 'These options change the compression level used… [See Man Page]'
complete -c gunzip -s c --description 'This option specifies that output will go to th… [See Man Page]'
complete -c gunzip -s d --description 'This option selects decompression rather than compression.'
complete -c gunzip -s f --description 'This option turns on force mode.'
complete -c gunzip -s h --description 'This option prints a usage summary and exits.'
complete -c gunzip -s k --description 'Keep (don\'t delete) input files during compress… [See Man Page]'
complete -c gunzip -s L --description 'This option prints gunzip license.'
complete -c gunzip -s l --description 'This option displays information about the file… [See Man Page]'
complete -c gunzip -s N --description 'This option causes the stored filename in the i… [See Man Page]'
complete -c gunzip -s n --description 'This option stops the filename and timestamp fr… [See Man Page]'
complete -c gunzip -s q --description 'With this option, no warnings or errors are printed.'
complete -c gunzip -s r --description 'This option is used to gunzip the files in a di… [See Man Page]'
complete -c gunzip -s S --description 'This option changes the default suffix from . gz to suffix.'
complete -c gunzip -s t --description 'This option will test compressed files for integrity.'
complete -c gunzip -s V --description 'This option prints the version of the gunzip program.'
complete -c gunzip -s v --description 'This option turns on verbose mode, which prints… [See Man Page]'

