# gzcat
# Autogenerated from man page /usr/share/man/man1/gzcat.1
# using Darwin man parser
complete -c gzcat -s 1 --description '.'
complete -c gzcat -s 2 --description '.'
complete -c gzcat -s 9 --description 'These options change the compression level used… [See Man Page]'
complete -c gzcat -s c --description 'This option specifies that output will go to th… [See Man Page]'
complete -c gzcat -s d --description 'This option selects decompression rather than compression.'
complete -c gzcat -s f --description 'This option turns on force mode.'
complete -c gzcat -s h --description 'This option prints a usage summary and exits.'
complete -c gzcat -s k --description 'Keep (don\'t delete) input files during compress… [See Man Page]'
complete -c gzcat -s L --description 'This option prints gzcat license.'
complete -c gzcat -s l --description 'This option displays information about the file… [See Man Page]'
complete -c gzcat -s N --description 'This option causes the stored filename in the i… [See Man Page]'
complete -c gzcat -s n --description 'This option stops the filename and timestamp fr… [See Man Page]'
complete -c gzcat -s q --description 'With this option, no warnings or errors are printed.'
complete -c gzcat -s r --description 'This option is used to gzcat the files in a dir… [See Man Page]'
complete -c gzcat -s S --description 'This option changes the default suffix from . gz to suffix.'
complete -c gzcat -s t --description 'This option will test compressed files for integrity.'
complete -c gzcat -s V --description 'This option prints the version of the gzcat program.'
complete -c gzcat -s v --description 'This option turns on verbose mode, which prints… [See Man Page]'

