# gzip
# Autogenerated from man page /usr/share/man/man1/gzip.1
# using Darwin man parser
complete -c gzip -s 1 --description '.'
complete -c gzip -s 2 --description '.'
complete -c gzip -s 9 --description 'These options change the compression level used… [See Man Page]'
complete -c gzip -s c --description 'This option specifies that output will go to th… [See Man Page]'
complete -c gzip -s d --description 'This option selects decompression rather than compression.'
complete -c gzip -s f --description 'This option turns on force mode.'
complete -c gzip -s h --description 'This option prints a usage summary and exits.'
complete -c gzip -s k --description 'Keep (don\'t delete) input files during compress… [See Man Page]'
complete -c gzip -s L --description 'This option prints gzip license.'
complete -c gzip -s l --description 'This option displays information about the file… [See Man Page]'
complete -c gzip -s N --description 'This option causes the stored filename in the i… [See Man Page]'
complete -c gzip -s n --description 'This option stops the filename and timestamp fr… [See Man Page]'
complete -c gzip -s q --description 'With this option, no warnings or errors are printed.'
complete -c gzip -s r --description 'This option is used to gzip the files in a dire… [See Man Page]'
complete -c gzip -s S --description 'This option changes the default suffix from . gz to suffix.'
complete -c gzip -s t --description 'This option will test compressed files for integrity.'
complete -c gzip -s V --description 'This option prints the version of the gzip program.'
complete -c gzip -s v --description 'This option turns on verbose mode, which prints… [See Man Page]'

