# hdik
# Autogenerated from man page /usr/share/man/man8/hdik.8
# using Darwin man parser
complete -c hdik -o shadow --description 'Use a shadow file in conjunction with the data in the image.'
complete -c hdik -o nomount --description 'Suppress automatic mounting of filesystems cont… [See Man Page]'
complete -c hdik -o drivekey --description 'Specify a key/value pair for the IOHDIXHDDrive … [See Man Page]'

