# hfs
# Autogenerated from man page /usr/share/man/man8/hfs.util.8
# using Darwin man parser
complete -c hfs -s a --description 'Adopt permissions for the HFS file system at device.'
complete -c hfs -s I --description 'Print out status information about the journal … [See Man Page]'
complete -c hfs -s J --description 'Enable journaling on the HFS file system mounted on mountpoint.'
complete -c hfs -s k --description 'Get the UUID key for the HFS file system at device.'
complete -c hfs -s m --description 'Mount the HFS file system located on device ont… [See Man Page]'
complete -c hfs -s M --description 'Force mount the HFS file system located on devi… [See Man Page]'
complete -c hfs -s N --description 'Disable journaling on a HFS+ file system located at device.'
complete -c hfs -s p --description 'Probe the device for an HFS file system using t… [See Man Page]'
complete -c hfs -s s --description 'Set the UUID key (generates a new UUID value) f… [See Man Page]'
complete -c hfs -s u --description 'Unmount the HFS file system located at device.'
complete -c hfs -s U --description 'Disable journaling on the HFS+ file system moun… [See Man Page]'

