# hostname
# Autogenerated from man page /usr/share/man/man1/hostname.1
# using Darwin man parser
complete -c hostname -s f --description 'Include domain information in the printed name.'
complete -c hostname -s s --description 'Trim off any domain information from the printed name.'

