# htcacheclean
# Autogenerated from man page /usr/share/man/man8/htcacheclean.8
# using Type1
complete -c htcacheclean -o dinterval --description 'Daemonize and repeat cache cleaning every interval minutes.'
complete -c htcacheclean -s D --description 'Do a dry run and don\'t delete anything.'
complete -c htcacheclean -s v --description 'Be verbose and print statistics.'
complete -c htcacheclean -s r --description 'Clean thoroughly.'
complete -c htcacheclean -s n --description 'Be nice.'
complete -c htcacheclean -s t --description 'Delete all empty directories.'
complete -c htcacheclean -o ppath --description 'Specify path as the root directory of the disk cache.'
complete -c htcacheclean -o Ppidfile --description 'Specify pidfile as the name of the file to writ… [See Man Page]'
complete -c htcacheclean -o Rround --description 'Specify round as the amount to round sizes up t… [See Man Page]'
complete -c htcacheclean -o llimit --description 'Specify limit as the total disk cache size limit.'
complete -c htcacheclean -o Llimit --description 'Specify limit as the total disk cache inode limit.'
complete -c htcacheclean -s i --description 'Be intelligent and run only when there was a mo… [See Man Page]'
complete -c htcacheclean -s a --description 'List the URLs currently stored in the cache.'

