# htpasswd
# Autogenerated from man page /usr/share/man/man1/htpasswd.1
# using Type1
complete -c htpasswd -s b --description 'Use batch mode; i. e.'
complete -c htpasswd -s i --description 'Read the password from stdin without verificati… [See Man Page]'
complete -c htpasswd -s c --description 'Create the passwdfile.'
complete -c htpasswd -s n --description 'Display the results on standard output rather t… [See Man Page]'
complete -c htpasswd -s m --description 'Use MD5 encryption for passwords.'
complete -c htpasswd -s B --description 'Use bcrypt encryption for passwords.'
complete -c htpasswd -s C --description 'This flag is only allowed in combination with -… [See Man Page]'
complete -c htpasswd -s d --description 'Use crypt() encryption for passwords.'
complete -c htpasswd -s s --description 'Use SHA encryption for passwords.'
complete -c htpasswd -s p --description 'Use plaintext passwords.'
complete -c htpasswd -s D --description 'Delete user.'
complete -c htpasswd -s v --description 'Verify password.'

