# httpd
# Autogenerated from man page /usr/share/man/man8/httpd.8
# using Type1
complete -c httpd -s d --description 'Set the initial value for the ServerRoot direct… [See Man Page]'
complete -c httpd -s f --description 'Uses the directives in the file config on startup.'
complete -c httpd -s k --description 'Signals httpd to start, restart, or stop.'
complete -c httpd -s C --description 'Process the configuration directive before read… [See Man Page]'
complete -c httpd -s c --description 'Process the configuration directive after reading config files.'
complete -c httpd -s D --description 'Sets a configuration parameter which can be use… [See Man Page]'
complete -c httpd -s e --description 'Sets the LogLevel to level during server startup.'
complete -c httpd -s E --description 'Send error messages during server startup to file.'
complete -c httpd -s h --description 'Output a short summary of available command line options.'
complete -c httpd -s l --description 'Output a list of modules compiled into the server.'
complete -c httpd -s L --description 'Output a list of directives provided by static … [See Man Page]'
complete -c httpd -s M --description 'Dump a list of loaded Static and Shared Modules.'
complete -c httpd -s S --description 'Show the settings as parsed from the config fil… [See Man Page]'
complete -c httpd -s T --description 'Skip document root check at startup/restart.'
complete -c httpd -s t --description 'Run syntax tests for configuration files only.'
complete -c httpd -s v --description 'Print the version of httpd, and then exit.'
complete -c httpd -s V --description 'Print the version and build parameters of httpd, and then exit.'
complete -c httpd -s X --description 'Run httpd in debug mode.'
complete -c httpd -s n --description 'The name of the Apache httpd service to signal.'

