# iconutil
# Autogenerated from man page /usr/share/man/man1/iconutil.1
# using Darwin man parser
complete -c iconutil -s c --description 'Given the argument iconset, iconutil converts the source \'.'
complete -c iconutil -s o --description 'Overrides the default output file name that ico… [See Man Page]'

