# iconservicesd
# Autogenerated from man page /usr/share/man/man1/iconservicesd.1
# using Darwin man parser
complete -c iconservicesd -s a --description 'Description of -a flag.'
complete -c iconservicesd -s b --description 'Description of -b flag \\" Ends the list Pp .'

