# iconservicesagent
# Autogenerated from man page /usr/share/man/man1/iconservicesagent.1
# using Darwin man parser
complete -c iconservicesagent -s a --description 'Description of -a flag.'
complete -c iconservicesagent -s b --description 'Description of -b flag \\" Ends the list Pp .'

