# icontool
# Autogenerated from man page /usr/share/man/man1/icontool.1
# using Darwin man parser
complete -c icontool -s a --description 'Description of -a flag.'
complete -c icontool -s b --description 'Description of -b flag \\" Ends the list Pp .'

