# iconv
# Autogenerated from man page /usr/share/man/man1/iconv.1
# using Deroffing man parser
complete -c iconv -s f -l from-code --description 'Specifies the encoding of the input.'
complete -c iconv -s t -l to-code --description 'Specifies the encoding of the output.'
complete -c iconv -s c --description 'When this option is given, characters that cann… [See Man Page]'
complete -c iconv -l unicode-subst --description 'When this option is given, Unicode characters t… [See Man Page]'
complete -c iconv -l byte-subst --description 'When this option is given, bytes in the input t… [See Man Page]'
complete -c iconv -l widechar-subst --description 'When this option is given, wide characters in t… [See Man Page]'
complete -c iconv -s s -l silent --description 'When this option is given, error messages about… [See Man Page]'

