# id
# Autogenerated from man page /usr/share/man/man1/id.1
# using Darwin man parser
complete -c id -s A --description 'Display the process audit user ID and other pro… [See Man Page]'
complete -c id -s F --description 'Display the full name of the user.'
complete -c id -s G --description 'Display the different group IDs (effective, rea… [See Man Page]'
complete -c id -s M --description 'Display the MAC label of the current process.'
complete -c id -s P --description 'Display the id as a password file entry.'
complete -c id -s a --description 'Ignored for compatibility with other id implementations.'
complete -c id -s g --description 'Display the effective group ID as a number.'
complete -c id -s n --description 'Display the name of the user or group ID for th… [See Man Page]'
complete -c id -s p --description 'Make the output human-readable.'
complete -c id -s r --description 'Display the real ID for the g and u options ins… [See Man Page]'
complete -c id -s u --description 'Display the effective user ID as a number.'

