# id3tool
# Autogenerated from man page /usr/local/share/man/man1/id3tool.1
# using Deroffing man parser
complete -c id3tool -s t -l set-title --description 'Sets the title to WORD.'
complete -c id3tool -s a -l set-album --description 'Sets the album to WORD.'
complete -c id3tool -s r -l set-artist --description 'Sets the artist to WORD.'
complete -c id3tool -s y -l set-year --description 'Sets the year to YEAR [4 digits].'
complete -c id3tool -s n -l set-note --description 'Sets the note to WORD.'
complete -c id3tool -s g -l set-genre --description 'Sets the genre code to INT (the codes can be ac… [See Man Page]'
complete -c id3tool -s G -l set-genre-word --description 'Sets the genre to WORD (given that WORD is from the genre list.'
complete -c id3tool -s c -l set-track --description 'Sets the track to INT.'
complete -c id3tool -s h -l help --description 'Show summary of options.'
complete -c id3tool -s v -l version --description 'Show version of program.'
complete -c id3tool -s l -l genre-list --description 'Shows the genre list.'

