# imptrace
# Autogenerated from man page /usr/share/man/man1/imptrace.1
# using Darwin man parser
complete -c imptrace -s i --description 'Show internal kernel boosts.'
complete -c imptrace -s s --description 'Show stacks for internal boosts.'
complete -c imptrace -s p --description 'Limit events to the process identified by pid.'
complete -c imptrace -s d --description 'Display raw Dtrace output; do not reformat time… [See Man Page]'

