# install
# Autogenerated from man page /usr/share/man/man1/install.1
# using Darwin man parser
complete -c install -s B --description 'Use suffix as the backup suffix if b is given.  ==========.'
complete -c install -s b --description 'Back up any existing files before overwriting t… [See Man Page]'
complete -c install -s C --description 'Copy the file.'
complete -c install -s c --description 'Copy the file.  This is actually the default.'
complete -c install -s d --description 'Create directories.'
complete -c install -s f --description 'Specify the target\'s file flags; see chflags 1 … [See Man Page]'
complete -c install -s g --description 'Specify a group.  A numeric GID is allowed.  ==========.'
complete -c install -s M --description 'Disable all use of mmap 2.  ==========.'
complete -c install -s m --description 'Specify an alternate mode.'
complete -c install -s o --description 'Specify an owner.  A numeric UID is allowed.  ==========.'
complete -c install -s p --description 'Preserve the modification time.'
complete -c install -s S --description 'Safe copy.'
complete -c install -s s --description 'install install exec\'s the command strip 1 to s… [See Man Page]'
complete -c install -s v --description 'Causes install install to show when C actually … [See Man Page]'

