# installer
# Autogenerated from man page /usr/share/man/man8/installer.8
# using Darwin man parser
complete -c installer -o dominfo --description 'Displays a list of domains into which the softw… [See Man Page]'
complete -c installer -o volinfo --description 'Displays a list of volumes onto which the softw… [See Man Page]'
complete -c installer -o pkginfo --description 'Displays a list of packages that can be install… [See Man Page]'
complete -c installer -o query --description 'Queries a package for information about the metadata.'
complete -c installer -o allowUntrusted --description 'Allow install of a package signed by an untrust… [See Man Page]'
complete -c installer -o dumplog --description 'Detailed log information is always sent to sysl… [See Man Page]'
complete -c installer -o help --description 'Displays the help screen describing the list of parameters.'
complete -c installer -o verbose --description 'Displays more descriptive information than the default output.'
complete -c installer -o verboseR --description 'Displays same information as -verbose except th… [See Man Page]'
complete -c installer -o vers --description 'Displays the version of this command.'
complete -c installer -o config --description 'Formats the command line installation arguments for later use.'
complete -c installer -o plist --description 'Formats the installer output into an XML file, … [See Man Page]'
complete -c installer -o file --description 'Specifies the path to the XML file containing p… [See Man Page]'
complete -c installer -o lang --description 'Default language of installed system (ISO format).'
complete -c installer -o listiso --description 'Display the list of valid ISO language codes th… [See Man Page]'
complete -c installer -o showChoiceChangesXML --description 'Prints to stdout the install choices for the pa… [See Man Page]'
complete -c installer -o applyChoiceChangesXML --description 'Applies the install choice changes specified in… [See Man Page]'
complete -c installer -o showChoicesAfterApplyingChangesXML --description 'Applies the install choice changes specified in… [See Man Page]'
complete -c installer -o showChoicesXML --description 'Prints to stdout the install choices for the pa… [See Man Page]'
complete -c installer -o store --description 'Install the product archive specified by packag… [See Man Page]'

