# iostat
# Autogenerated from man page /usr/share/man/man8/iostat.8
# using Darwin man parser
complete -c iostat -o '?\\&' --description 'Display a usage statement and exit.  ==========.'
complete -c iostat -s C --description 'Display CPU statistics.'
complete -c iostat -s c --description 'Repeat the display count times.'
complete -c iostat -s d --description 'Display only device statistics.'
complete -c iostat -s I --description 'Display total statstics for a given time period… [See Man Page]'
complete -c iostat -s K --description 'In the blocks transferred display (-o), display… [See Man Page]'
complete -c iostat -s n --description 'Display up to devs number of devices.'
complete -c iostat -s o --description 'Display old-style iostat iostat device statistics.'
complete -c iostat -s T --description 'Display TTY statistics.'
complete -c iostat -s U --description 'Display system load averages.'
complete -c iostat -s w --description 'Pause wait seconds between each display.'

