# ipcrm
# Autogenerated from man page /usr/share/man/man1/ipcrm.1
# using Darwin man parser
complete -c ipcrm -s M --description 'Mark the shared memory segment associated with … [See Man Page]'
complete -c ipcrm -s m --description 'Mark the shared memory segment associated with … [See Man Page]'
complete -c ipcrm -s Q --description 'Remove the message queue associated with key ip… [See Man Page]'
complete -c ipcrm -s q --description 'Remove the message queue associated with the id… [See Man Page]'
complete -c ipcrm -s S --description 'Remove the semaphore set associated with key ip… [See Man Page]'
complete -c ipcrm -s s --description 'Removes the semaphore set associated with id ip… [See Man Page]'

