# jar
# Autogenerated from man page /usr/share/man/man1/jar.1
# using Deroffing man parser
complete -c jar -s C --description 'Temporarily changes directories (cd dir) during… [See Man Page]'
complete -c jar -o J-Xms48m --description 'sets the startup memory to 48 megabytes.'
complete -c jar -s J --description 'to pass options to the underlying virtual machine.'

