# jarsigner
# Autogenerated from man page /usr/share/man/man1/jarsigner.1
# using Deroffing man parser
complete -c jarsigner -o keystore --description 'Specifies the URL that tells the keystore location.'
complete -c jarsigner -o storetype --description 'Specifies the type of keystore to be instantiated.'
complete -c jarsigner -o storepass --description 'Specifies the password which is required to acc… [See Man Page]'
complete -c jarsigner -o keypass --description 'Specifies the password used to protect the priv… [See Man Page]'
complete -c jarsigner -o sigfile --description 'Specifies the base file name to be used for the generated   .'
complete -c jarsigner -o signedjar --description 'Specifies the name to be used for the signed JAR file. RS  .'
complete -c jarsigner -o verify --description 'If this appears on the command line, the specif… [See Man Page]'
complete -c jarsigner -o certs --description 'If this appears on the command line, along with… [See Man Page]'
complete -c jarsigner -o verbose --description 'If this appears on the command line, it indicat… [See Man Page]'
complete -c jarsigner -o internalsf --description 'In the past, the   .'
complete -c jarsigner -o sectionsonly --description 'If this appears on the command line, the   .'
complete -c jarsigner -o provider --description 'Used to specify the name of the cryptographic s… [See Man Page]'
complete -c jarsigner -o sigFile --description 'option.  For example, if the option appears as.'
complete -c jarsigner -s J --description 'Passes the specified javaoption string directly… [See Man Page]'

