# javap
# Autogenerated from man page /usr/share/man/man1/javap.1
# using Deroffing man parser
complete -c javap -s b --description 'Ensures backward compatibility with   javap in JDK 1. 1.'
complete -c javap -o bootclasspath --description 'Specifies path from which to load bootstrap classes.'
complete -c javap -s c --description 'Prints out disassembled code, that is, the inst… [See Man Page]'
complete -c javap -o classpath --description 'Specifies the  path  javap uses to look up classes.'
complete -c javap -o extdirs --description 'Overrides location at which installed extensions are searched.'
complete -c javap -o help --description 'Prints out help message for  javap .'
complete -c javap -s J --description 'Passes   flag directly to runtime system. RS .'
complete -c javap -s l --description 'Displays line and local variable tables.'
complete -c javap -o package --description 'Shows only package, protected, and public classes and members.'
complete -c javap -o private --description 'Shows all classes and members.'
complete -c javap -o protected --description 'Shows only protected and public classes and members.'
complete -c javap -o public --description 'Shows only public classes and members.'
complete -c javap -s s --description 'Displays internal type signatures.'
complete -c javap -o 'Djava.security.policy' --description '.'
complete -c javap -o verbose --description 'Prints stack size, number of locals , and args for methods.'

