# javah
# Autogenerated from man page /usr/share/man/man1/javah.1
# using Deroffing man parser
complete -c javah -s o --description 'Concatenates the resulting header or source fil… [See Man Page]'
complete -c javah -o bootclasspath --description 'Specifies path from which to load bootstrap classes.'
complete -c javah -o classpath --description 'Specifies the path   javah  uses to look up classes.'
complete -c javah -s d --description 'Sets the directory where   javah  saves the hea… [See Man Page]'
complete -c javah -o force --description 'Specifies that output files should always be written.'
complete -c javah -o help --description 'Prints help message for   javah usage. ne 2 . bp.'
complete -c javah -o jni --description 'Causes   javah  to create an output file contai… [See Man Page]'
complete -c javah -o old --description 'Specifies the old JDK1.'
complete -c javah -o stubs --description 'Causes   javah  to generate C declarations from… [See Man Page]'
complete -c javah -o trace --description 'Tracing is no longer supported.'
complete -c javah -o verbose --description 'Indicates verbose output and causes   javah  to… [See Man Page]'
complete -c javah -o version --description 'Print out javah version information.'
complete -c javah -o verbose:jni --description 'option of the virtual machine.'
complete -c javah -s J --description 'Pass option to the Java virtual machine, where … [See Man Page]'
complete -c javah -o J-Xms48m --description 'sets the startup memory to 48 megabytes.'

