# javaws
# Autogenerated from man page /usr/share/man/man1/javaws.1
# using Deroffing man parser
complete -c javaws -o offline --description 'Runs Java Web Start in offline mode. SS.'
complete -c javaws -o uninstall --description 'Removes a specific application/applet from the … [See Man Page]'
complete -c javaws -o updateVersions --description 'Updates the Java Web Start configuration file b… [See Man Page]'
complete -c javaws -o Xclearcache --description 'Clears the user\'s cache.'
complete -c javaws -o Xnosplash --description 'Disables the display of the initial splash screen. SS.'
complete -c javaws -o import --description 'Imports the application specified by the URL in… [See Man Page]'
complete -c javaws -o silent --description 'When used with the -import option, imports in silent mode; i.'
complete -c javaws -o codebase --description 'Replaces the codebase with URL in the jnlp file… [See Man Page]'
complete -c javaws -o system --description 'Uses the system cache instead of the user cache. SS.'
complete -c javaws -o shortcut --description 'Allows the creation of shortcuts during silent import. SS.'
complete -c javaws -o association --description 'Allows the creation of associations during silent import. SS.'
complete -c javaws -o open --description 'If specified, replaces the arguments in the jnl… [See Man Page]'
complete -c javaws -o print --description 'If specified, replaces the arguments in the jnl… [See Man Page]'
complete -c javaws -o online --description 'Runs in online mode (default behavior). SS.'
complete -c javaws -o viewer --description 'Runs the Java Application Cache Viewer (default… [See Man Page]'
complete -c javaws -o userConfig --description 'Clears the specified deployment property. SS.'
complete -c javaws -o wait --description 'If specified, the javaws process will not exit … [See Man Page]'

