# jdb
# Autogenerated from man page /usr/share/man/man1/jdb.1
# using Deroffing man parser
complete -c jdb -o sourcepath --description 'Uses the given path in searching for source fil… [See Man Page]'
complete -c jdb -o attach --description 'Attaches the debugger to previously running VM … [See Man Page]'
complete -c jdb -o launch --description 'Launches the debugged application immediately u… [See Man Page]'
complete -c jdb -o Xrunjdwp:transport --description 'server=y,suspend=n T}	T{.'
complete -c jdb -s D --description '.'
complete -c jdb -o classpath --description 'and.'
complete -c jdb -s X --description '.'
complete -c jdb -s J --description 'Pass option to the Java virtual machine, where … [See Man Page]'
complete -c jdb -o J-Xms48m --description 'sets the startup memory to 48 megabytes.'

