# jinfo
# Autogenerated from man page /usr/share/man/man1/jinfo.1
# using Deroffing man parser
complete -c jinfo -o flags --description 'prints command line flags as name, value pairs . if t.'
complete -c jinfo -o sysprops --description 'prints JavaSystem properties as name, value pairs . if t.'
complete -c jinfo -s h --description 'prints a help message . if t.'
complete -c jinfo -o help --description 'prints a help message SEE ALSO jps (1) jsadebugd (1).'

