# jot
# Autogenerated from man page /usr/share/man/man1/jot.1
# using Darwin man parser
complete -c jot -s r --description 'Generate random data instead of the default sequential data.'
complete -c jot -s b --description 'Just print word repetitively.'
complete -c jot -s w --description 'Print word with the generated data appended to it.'
complete -c jot -s c --description 'This is an abbreviation for w Ar %c.'
complete -c jot -s s --description 'Print data separated by string.'
complete -c jot -s n --description 'Do not print the final newline normally appended to the output.'
complete -c jot -s p --description 'Print only as many digits or characters of the … [See Man Page]'

