# jps
# Autogenerated from man page /usr/share/man/man1/jps.1
# using Deroffing man parser
complete -c jps -s q --description 'Suppress the output of the class name, JAR file… [See Man Page]'
complete -c jps -s m --description 'Output the arguments passed to the main method.'
complete -c jps -s l --description 'Output the full package name for the applicatio… [See Man Page]'
complete -c jps -s v --description 'Output the arguments passed to the JVM. if t.'
complete -c jps -s V --description 'Output the arguments passed to the JVM through … [See Man Page]'
complete -c jps -s J --description 'Pass option to the java launcher called by javac.'
complete -c jps -o J-Xms48m --description 'sets the startup memory to 48 megabytes.'

