# jstack
# Autogenerated from man page /usr/share/man/man1/jstack.1
# using Deroffing man parser
complete -c jstack -s m --description 'prints mixed mode (both Java and native C/C++ f… [See Man Page]'
complete -c jstack -s h --description 'Prints a help message. if t.'
complete -c jstack -o help --description 'Prints a help message.'

