# jstatd
# Autogenerated from man page /usr/share/man/man1/jstatd.1
# using Deroffing man parser
complete -c jstatd -o nr --description 'Do not attempt to create an internal RMI regist… [See Man Page]'
complete -c jstatd -s p --description 'Port number where the RMI registry is expected … [See Man Page]'
complete -c jstatd -s n --description 'Name to which the remote RMI object is bound in… [See Man Page]'
complete -c jstatd -s J --description 'Pass option to the java launcher called by javac.'

