# jstat
# Autogenerated from man page /usr/share/man/man1/jstat.1
# using Deroffing man parser
complete -c jstat -o help --description 'Display help message. if t.'
complete -c jstat -o version --description 'Display version information. if t.'
complete -c jstat -o options --description 'Display list of statistics options.'
complete -c jstat -o statOption --description 'Determines the statistics information that jstat displays.'
complete -c jstat -s h --description 'Display a column header every n samples (output… [See Man Page]'
complete -c jstat -s t --description 'Display a timestamp column as the first column of output.'
complete -c jstat -s J --description 'Pass \\f2javaOption to the java application launcher.'
complete -c jstat -o gcutil --description 'jstat -gcutil 21891 250 7   S0     S1     E    … [See Man Page]'

