# kadmind
# Autogenerated from man page /usr/share/man/man8/kadmind.8
# using Darwin man parser
complete -c kadmind -s c --description 'location of config file.'
complete -c kadmind -s k --description 'location of master key file.'
complete -c kadmind -l keytab --description 'what keytab to use.'
complete -c kadmind -s r --description 'realm to use.'
complete -c kadmind -s d --description 'enable debugging.'
complete -c kadmind -s p --description 'ports to listen to.'

