# kdcsetup
# Autogenerated from man page /usr/share/man/man8/kdcsetup.8
# using Darwin man parser
complete -c kdcsetup -s v --description 'Controls the amount of output generated by kdcsetup.'
complete -c kdcsetup -s a --description 'Name of a directory administrator authorized to… [See Man Page]'
complete -c kdcsetup -s p --description 'The password for the above admin.   Required parameter.'

