# kdestroy
# Autogenerated from man page /usr/share/man/man1/kdestroy.1
# using Darwin man parser
complete -c kdestroy -o credential --description 'remove principal from the credential cache if it exists.'
complete -c kdestroy -s p --description '.'
complete -c kdestroy -o principal --description 'The cache with client principal to remove.'
complete -c kdestroy -s c --description '.'
complete -c kdestroy -o cache --description 'The cache to remove.'
complete -c kdestroy -s A --description '.'
complete -c kdestroy -s a --description '.'
complete -c kdestroy -l all --description 'remove all credential caches.'
complete -c kdestroy -l no-unlog --description 'Do not remove AFS tokens.'
complete -c kdestroy -l no-delete-v4 --description 'Do not remove v4 tickets.  El SEE ALSO kinit 1, klist 1.'

