# KernelEventAgent
# Autogenerated from man page /usr/share/man/man8/KernelEventAgent.8
# using Darwin man parser
complete -c KernelEventAgent -s d --description 'Debug mode.'
complete -c KernelEventAgent -s v --description 'Verbose mode.'
complete -c KernelEventAgent -s f --description 'The file system identified by fsname is also pa… [See Man Page]'
complete -c KernelEventAgent -s t --description 'The timeout value, specified in seconds, is the… [See Man Page]'

