# kextload
# Autogenerated from man page /usr/share/man/man8/kextload.8
# using Darwin man parser
complete -c kextload -s b --description 'Look up the kext whose CFBundleIdentifier is id… [See Man Page]'
complete -c kextload -s d --description 'Add kext and its plugins to the set of known ke… [See Man Page]'
complete -c kextload -s h --description 'Print a help message describing each option fla… [See Man Page]'
complete -c kextload -s q --description 'Quiet mode; print no informational or error messages.'
complete -c kextload -s r --description 'Use directory as a repository of kexts.'
complete -c kextload -s v --description 'Verbose mode; print information about program operation.'

