# kextstat
# Autogenerated from man page /usr/share/man/man8/kextstat.8
# using Darwin man parser
complete -c kextstat -s a --description 'Print the architecture of the kext.'
complete -c kextstat -s b --description 'Display the status of only the kext with the gi… [See Man Page]'
complete -c kextstat -s h --description 'Print a help message describing each option fla… [See Man Page]'
complete -c kextstat -s k --description 'Don\'t show information for built-in components of the kernel.'
complete -c kextstat -s l --description 'Print the list of loaded kexts only and omit th… [See Man Page]'

