# kextunload
# Autogenerated from man page /usr/share/man/man8/kextunload.8
# using Darwin man parser
complete -c kextunload -s b --description 'Unload executable and IOKitPersonalities (as de… [See Man Page]'
complete -c kextunload -s c --description 'Terminate all instances of class classname that… [See Man Page]'
complete -c kextunload -s h --description 'Print a help message describing each option fla… [See Man Page]'
complete -c kextunload -s m --description 'Same as b (remains for backward compatibility).'
complete -c kextunload -s p --description 'Terminate services and remove personalities onl… [See Man Page]'
complete -c kextunload -s q --description 'Quiet mode; print no informational or error messages.'
complete -c kextunload -s v --description 'Verbose mode; print information about program operation.'

