# kextd
# Autogenerated from man page /usr/share/man/man8/kextd.8
# using Darwin man parser
complete -c kextd -s c --description 'Ignore any repository cache files and scan all … [See Man Page]'
complete -c kextd -s d --description 'Debug mode; print messages to stdout/stderr rat… [See Man Page]'
complete -c kextd -s h --description 'Print a help message describing each option fla… [See Man Page]'
complete -c kextd -s q --description 'Quiet mode; log no informational or error messages.'
complete -c kextd -s v --description 'Verbose mode; print information about program operation.'
complete -c kextd -s x --description 'Run kextd in safe boot mode (indicating startup… [See Man Page]'

