# kextlibs
# Autogenerated from man page /usr/share/man/man8/kextlibs.8
# using Darwin man parser
complete -c kextlibs -s h --description 'Print a help message describing each option fla… [See Man Page]'
complete -c kextlibs -o all-symbols --description 'Print reports on all symbols that remain undefi… [See Man Page]'
complete -c kextlibs -s c --description 'Print the compatible version rather than the current version.'
complete -c kextlibs -o multdef-symbols --description 'Print all undefined symbols from kext found in … [See Man Page]'
complete -c kextlibs -o non-kpi --description 'Search the compatibility kext, com. apple. kernel. 6.'
complete -c kextlibs -o onedef-symbols --description 'Print all undefined symbols from kext found in … [See Man Page]'
complete -c kextlibs -s r --description 'Search directory for dependencies.'
complete -c kextlibs -s e --description 'Add /System/Library/Extensions and /Library/Ext… [See Man Page]'
complete -c kextlibs -o undef-symbols --description 'Print all undefined symbols from kext that can\'… [See Man Page]'
complete -c kextlibs -o unsupported --description 'Search unsupported library kexts for symbols (b… [See Man Page]'
complete -c kextlibs -s v --description 'Verbose mode; print information about program operation.'
complete -c kextlibs -o xml --description 'Print an XML fragment to stdout suitable for co… [See Man Page]'

