# KeychainMigrator
# Autogenerated from man page /usr/share/man/man1/KeychainMigrator.1
# using Darwin man parser
complete -c KeychainMigrator -s a --description 'Description of -a flag.'
complete -c KeychainMigrator -s b --description 'Description of -b flag \\" Ends the list Pp .'

