# kgetcred
# Autogenerated from man page /usr/share/man/man1/kgetcred.1
# using Darwin man parser
complete -c kgetcred -l canonicalize --description 'requests that the KDC canonicalize the principal.'
complete -c kgetcred -s c --description 'the credential cache to use.'
complete -c kgetcred -s e --description 'encryption type to use.'
complete -c kgetcred -l no-transit-check --description 'requests that the KDC doesn\'t do transit checking.'
complete -c kgetcred -l version --description '.'
complete -c kgetcred -l help --description 'El SEE ALSO kinit 1, klist 1.'

