# killall
# Autogenerated from man page /usr/share/man/man1/killall.1
# using Darwin man parser
complete -c killall -s v --description 'Be more verbose about what will be done.'
complete -c killall -s e --description 'Use the effective user ID instead of the (defau… [See Man Page]'
complete -c killall -o help --description 'Give a help on the command usage and exit.'
complete -c killall -s l --description 'List the names of the available signals and exi… [See Man Page]'
complete -c killall -s m --description 'Match the argument procname as a (case sensitiv… [See Man Page]'
complete -c killall -s s --description 'Show only what would be done, but do not send any signal.'
complete -c killall -s d --description 'Print detailed information about the processes … [See Man Page]'
complete -c killall -o SIGNAL --description 'Send a different signal instead of the default TERM.'
complete -c killall -s u --description 'Limit potentially matching processes to those b… [See Man Page]'
complete -c killall -s t --description 'Limit potentially matching processes to those r… [See Man Page]'
complete -c killall -s c --description 'When used with the u or t flags, limit potentia… [See Man Page]'
complete -c killall -s z --description 'Do not skip zombies.'

