# kpconfig
# Autogenerated from man page /usr/share/man/man1/kpconfig.1
# using Darwin man parser
complete -c kpconfig -s a --description 'Description of -a flag.'
complete -c kpconfig -s b --description 'Description of -b flag \\" Ends the list Pp .'

