# kpfile
# Autogenerated from man page /usr/share/man/man1/kpfile.1
# using Darwin man parser
complete -c kpfile -s c --description 'Import trace codes from code-file in addition t… [See Man Page]'
complete -c kpfile -s F --description 'Provide the timebase frequency.'
complete -c kpfile -s H --description 'Use default parameters from the local host.'
complete -c kpfile -s h --description 'Print help message.'
complete -c kpfile -s i --description 'Print summary information about trace files.'
complete -c kpfile -s N --description 'Do not import trace codes from /usr/share/misc/trace. codes.'
complete -c kpfile -s o --description 'Write output to file instead of converting files in place.'
complete -c kpfile -s t --description 'Print trace file as text.'
complete -c kpfile -s V --description 'Convert trace files to version v.'
complete -c kpfile -s v --description 'Print extra information.'
complete -c kpfile -s z --description 'Compress trace files.'
complete -c kpfile -s 0 --description 'Don\'t compress trace files.'
complete -c kpfile -s 1 --description 'Use the fastest compression level.'
complete -c kpfile -s 2 --description 'Use the medium compression level.'
complete -c kpfile -s 3 --description 'Use the best compression level.  This is the default.'

