# kptop
# Autogenerated from man page /usr/share/man/man1/kptop.1
# using Darwin man parser
complete -c kptop -s a --description 'Description of -a flag.'
complete -c kptop -s b --description 'Description of -b flag \\" Ends the list Pp .'

