# lam
# Autogenerated from man page /usr/share/man/man1/lam.1
# using Darwin man parser
complete -c lam -s f --description 'Print line fragments according to the format string min .'
complete -c lam -s p --description 'Like f, but pad this file\'s field when end-of-f… [See Man Page]'
complete -c lam -s s --description 'Print sepstring before printing line fragments … [See Man Page]'
complete -c lam -s t --description 'The input line terminator is c instead of a newline.'

