# languagesetup
# Autogenerated from man page /usr/share/man/man1/languagesetup.1
# using Darwin man parser
complete -c languagesetup -s a --description 'Description of -a flag.'
complete -c languagesetup -s b --description 'Description of -b flag \\" Ends the list Pp .'

