# localemanager
# Autogenerated from man page /usr/share/man/man8/localemanager.8
# using Darwin man parser
complete -c localemanager -s l --description 'Locale name.'
complete -c localemanager -o subnet --description 'Subnet specified in CIDR notation.'
complete -c localemanager -o server --description 'Server fully-qualified domain name.'
complete -c localemanager -s i --description 'Use this IP address for the server.'

