# localedef
# Autogenerated from man page /usr/share/man/man1/localedef.1
# using Darwin man parser
complete -c localedef -s c --description 'Create permanent output even if warning message… [See Man Page]'
complete -c localedef -s f --description 'Specify the pathname of a file containing a map… [See Man Page]'
complete -c localedef -s i --description 'The pathname of a file containing the source definitions.'

