# lockfile
# Autogenerated from man page /usr/share/man/man1/lockfile.1
# using Deroffing man parser
complete -c lockfile -o r-1 --description 'lockfile will retry forever.'
complete -c lockfile -s '!' --description 'flag to invert the exit status.'
complete -c lockfile -s f --description '.'
complete -c lockfile -o ml --description 'and.'
complete -c lockfile -o mu --description 'respectively.'

