# logger
# Autogenerated from man page /usr/share/man/man1/logger.1
# using Darwin man parser
complete -c logger -s i --description 'Log the process id of the logger process with each line.'
complete -c logger -s s --description 'Log the message to standard error, as well as the system log.'
complete -c logger -s f --description 'Log the specified file.'
complete -c logger -s p --description 'Enter the message with the specified priority.'
complete -c logger -s t --description 'Mark every line in the log with the specified tag .'

