# login
# Autogenerated from man page /usr/share/man/man1/login.1
# using Darwin man parser
complete -c login -s f --description 'When a user name is specified, this option indi… [See Man Page]'
complete -c login -s h --description 'Specify the host from which the connection was received.'
complete -c login -s l --description 'Tells the program executed by login that this i… [See Man Page]'
complete -c login -s p --description 'By default, login discards any previous environment.'
complete -c login -s q --description 'This forces quiet logins, as if a . hushlogin is present.'

