# look
# Autogenerated from man page /usr/share/man/man1/look.1
# using Darwin man parser
complete -c look -s d --description 'Dictionary character set and order, i. e.'
complete -c look -s f --description 'Ignore the case of alphabetic characters.'
complete -c look -s t --description 'Specify a string termination character, i. e.'

