# lowBatteryWarning
# Autogenerated from man page /usr/share/man/man1/lowBatteryWarning.1
# using Darwin man parser
complete -c lowBatteryWarning -s a --description 'Description of -a flag.'
complete -c lowBatteryWarning -s b --description 'Description of -b flag \\" Ends the list Pp .'

