# lpinfo
# Autogenerated from man page /usr/share/man/man8/lpinfo.8.gz
# using Deroffing man parser
complete -c lpinfo -s E --description 'Forces encryption when connecting to the server.'
complete -c lpinfo -s U --description 'Sets the username to use when connecting to the server.'
complete -c lpinfo -s h --description 'Selects an alternate server.'
complete -c lpinfo -s l --description 'Shows a "long" listing of devices or drivers.'
complete -c lpinfo -l device-id --description 'Specifies the IEEE-1284 device ID to match when… [See Man Page]'
complete -c lpinfo -l exclude-schemes --description 'Specifies a comma-delimited list of device or P… [See Man Page]'
complete -c lpinfo -l include-schemes --description 'Specifies a comma-delimited list of device or P… [See Man Page]'
complete -c lpinfo -l language --description 'Specifies the language to match when listing dr… [See Man Page]'
complete -c lpinfo -l make-and-model --description 'Specifies the make and model to match when list… [See Man Page]'
complete -c lpinfo -l product --description 'Specifies the product to match when listing dri… [See Man Page]'
complete -c lpinfo -l timeout --description 'Specifies the timeout when listing devices with the -v option.'

