# lpr
# Autogenerated from man page /usr/share/man/man1/lpr.1.gz
# using Deroffing man parser
complete -c lpr -s E --description 'Forces encryption when connecting to the server.'
complete -c lpr -s H --description 'Specifies an alternate server.'
complete -c lpr -s T --description 'Sets the job name/title.'
complete -c lpr -s P --description 'Prints files to the named printer.'
complete -c lpr -s U --description 'Specifies an alternate username.'
complete -c lpr -s '#' --description 'Sets the number of copies to print.'
complete -c lpr -s h --description 'Disables banner printing.'
complete -c lpr -s l --description 'Specifies that the print file is already format… [See Man Page]'
complete -c lpr -s m --description 'Send an email on job completion.'
complete -c lpr -s o --description 'Sets a job option.'
complete -c lpr -s p --description 'Specifies that the print file should be formatt… [See Man Page]'
complete -c lpr -s q --description 'Hold job for printing.'
complete -c lpr -s C --description '.'
complete -c lpr -s J --description '.'
complete -c lpr -s r --description 'Specifies that the named print files should be … [See Man Page]'

