# lsactivity
# Autogenerated from man page /usr/share/man/man8/lsactivity.8
# using Darwin man parser
complete -c lsactivity -o title --description 'the title to give the activity.'
complete -c lsactivity -o payload --description 'Add the value item to the payload with the key key.'
complete -c lsactivity -o payloadData --description 'Uses NSKeyedUnarchiver to unarchive the given data.'
complete -c lsactivity -o payloadFile --description 'read the payload dictionary from path.'
complete -c lsactivity -o options --description 'Add the key,value pair to the options dictionary.'
complete -c lsactivity -o type --description 'Sets the activity type to the given LSSuggested… [See Man Page]'
complete -c lsactivity -o url --description 'Sets the webpageURL for the item to url El upda… [See Man Page]'
complete -c lsactivity -o all --description 'List all best apps, not just the top-ranked one.'
complete -c lsactivity -o watch --description 'Display the live changes to the best applicatio… [See Man Page]'
complete -c lsactivity -o open --description 'Attempt to open (as if selected by the user) ea… [See Man Page]'
complete -c lsactivity -o show --description 'Fetch the activity from the remote device and d… [See Man Page]'
complete -c lsactivity -o remove --description 'Remove the item from future consideration as a … [See Man Page]'
complete -c lsactivity -o duration --description 'The duration, in seconds, to reflect activities.'
complete -c lsactivity -o identifier --description 'Advertise the given bundle identifier.'

