# lsappinfo
# Autogenerated from man page /usr/share/man/man8/lsappinfo.8
# using Deroffing man parser
complete -c lsappinfo -s v -l verbose --description '.'
complete -c lsappinfo -s q -l quiet --description '.'
complete -c lsappinfo -o defaultSession --description '.'
complete -c lsappinfo -o currentSession --description '.'
complete -c lsappinfo -o debug -o info -o notice -o warning -o err -o critical -o alert -o emergency --description '.'

