# lsbom
# Autogenerated from man page /usr/share/man/man8/lsbom.8
# using Darwin man parser
complete -c lsbom -s h --description 'print full usage.'
complete -c lsbom -s b --description 'list block devices.'
complete -c lsbom -s c --description 'list character devices.'
complete -c lsbom -s d --description 'list directories.'
complete -c lsbom -s f --description 'list files.'
complete -c lsbom -s l --description 'list symbolic links.'
complete -c lsbom -s m --description 'print modified times (for plain files only).'
complete -c lsbom -s s --description 'print only the path of each file.'
complete -c lsbom -s x --description 'suppress modes for directories and symlinks.'
complete -c lsbom -l arch --description 'when displaying plain files that represent Univ… [See Man Page]'
complete -c lsbom -s p --description 'print only some of the results lsbom Note: each… [See Man Page]'

