# man
# Autogenerated from man page /usr/share/man/man1/man.1
# using Deroffing man parser
complete -c man -s C --description 'Specify the configuration file to use; the defa… [See Man Page]'
complete -c man -s M --description 'Specify the list of directories to search for man pages.'
complete -c man -s P --description 'Specify which pager to use.'
complete -c man -s B --description 'Specify which browser to use on HTML files.'
complete -c man -s H --description 'Specify a command that renders HTML files as text.'
complete -c man -s S --description 'List is a colon separated list of manual sections to search.'
complete -c man -s a --description 'By default,  man will exit after displaying the… [See Man Page]'
complete -c man -s c --description 'Reformat the source man page, even when an up-t… [See Man Page]'
complete -c man -s d --description 'Don\'t actually display the man pages, but do pr… [See Man Page]'
complete -c man -s D --description 'Both display and print debugging info.'
complete -c man -s f --description 'Equivalent to  whatis .'
complete -c man -s F -l preformat --description 'Format only - do not display.'
complete -c man -s h --description 'Print a help message and exit.'
complete -c man -s k --description 'Equivalent to  apropos .'
complete -c man -s K --description 'Search for the specified string in *all* man pages.'
complete -c man -s m --description 'Specify an alternate set of man pages to search… [See Man Page]'
complete -c man -s p --description 'Specify the sequence of preprocessors to run be… [See Man Page]'
complete -c man -s t --description 'Use  /usr/bin/groff -Tps -mandoc -c to format t… [See Man Page]'
complete -c man -s w -l path --description 'Don\'t actually display the man pages, but do pr… [See Man Page]'
complete -c man -s W --description 'Like -w, but print file names one per line, wit… [See Man Page]'

