# mcxquery
# Autogenerated from man page /usr/share/man/man1/mcxquery.1
# using Darwin man parser
complete -c mcxquery -o user --description 'Specify the short name of the user record to re… [See Man Page]'
complete -c mcxquery -o group --description 'Specify the short name of the group record to r… [See Man Page]'
complete -c mcxquery -o computer --description 'Specify the computer record to read managed preferences from.'

