# md5
# Autogenerated from man page /usr/share/man/man1/md5.1
# using Darwin man parser
complete -c md5 -s s --description 'Print a checksum of the given string.'
complete -c md5 -s p --description 'Echo stdin to stdout and append the checksum to stdout.'
complete -c md5 -s q --description 'Quiet mode - only the checksum is printed out.'
complete -c md5 -s r --description 'Reverses the format of the output.'
complete -c md5 -s t --description 'Run a built-in time trial.'
complete -c md5 -s x --description 'Run a built-in test script.'

