# mddiagnose
# Autogenerated from man page /usr/share/man/man8/mddiagnose.8
# using Darwin man parser
complete -c mddiagnose -s h --description 'Print full usage.'
complete -c mddiagnose -s m --description 'Gather a subset of the normal report.'
complete -c mddiagnose -s f --description 'Write the diagnostic to the specified path.'
complete -c mddiagnose -s p --description 'Gather Spotlight permissions and filter information.'

