# mdfind
# Autogenerated from man page /usr/share/man/man1/mdfind.1
# using Darwin man parser
complete -c mdfind -s 0 --description 'Prints an ASCII NUL character after each result path.'
complete -c mdfind -o live --description 'Causes the mdfind command to provide live-updat… [See Man Page]'
complete -c mdfind -o count --description 'Causes the mdfind command to output the total n… [See Man Page]'
complete -c mdfind -o onlyin --description 'Limit the scope of the search to the directory specified.'
complete -c mdfind -o name --description 'Searches for matching file names only.'
complete -c mdfind -o literal --description 'Force the provided query string to be taken as … [See Man Page]'
complete -c mdfind -o interpret --description 'Force the provided query string to be interpret… [See Man Page]'

