# mdimport
# Autogenerated from man page /usr/share/man/man1/mdimport.1
# using Darwin man parser
complete -c mdimport -s g --description 'Load the plugin at the provided path, ignoring … [See Man Page]'
complete -c mdimport -s V --description 'Print timing information for this run of mdimport.'
complete -c mdimport -s A --description 'Print out the list of all of the attributes and… [See Man Page]'
complete -c mdimport -s X --description 'Print the schema file and exit.'
complete -c mdimport -s r --description 'Ask the server to reimport files for UTIs claim… [See Man Page]'
complete -c mdimport -s p --description 'Print out performance information gathered during the run.'
complete -c mdimport -s L --description 'Print the list of installed importers and exit.'
complete -c mdimport -s d --description 'Print debugging information.  Level can be 1-4.'
complete -c mdimport -s n --description 'Don\'t actually set the attributes on the file.'
complete -c mdimport -s w --description 'Wait for the specified interval between scanning files.'

