# mdls
# Autogenerated from man page /usr/share/man/man1/mdls.1
# using Darwin man parser
complete -c mdls -o name --description 'Print only the matching metadata attribute value.'
complete -c mdls -o raw --description 'Print raw attribute data in the order that was requested.'
complete -c mdls -o nullMarker --description 'Sets a marker string to be used when a requeste… [See Man Page]'

