# mdutil
# Autogenerated from man page /usr/share/man/man1/mdutil.1
# using Darwin man parser
complete -c mdutil -s p --description 'Spotlight caches indexes of some network devices locally.'
complete -c mdutil -s E --description 'This flag will cause each local store for the v… [See Man Page]'
complete -c mdutil -s i --description 'Sets the indexing status for the provided volumes to on or off.'
complete -c mdutil -s d --description 'Disables Spotlight searches on the provided volume.'
complete -c mdutil -s s --description 'Display the indexing status of the listed volumes.'
complete -c mdutil -s a --description 'Apply command to all volumes.'
complete -c mdutil -s v --description 'Print verbose information when available.'

