# mkdir
# Autogenerated from man page /usr/share/man/man1/mkdir.1
# using Darwin man parser
complete -c mkdir -s m --description 'Set the file permission bits of the final creat… [See Man Page]'
complete -c mkdir -s p --description 'Create intermediate directories as required.'
complete -c mkdir -s v --description 'Be verbose when creating directories, listing t… [See Man Page]'

