# mklocale
# Autogenerated from man page /usr/share/man/man1/mklocale.1
# using Darwin man parser
complete -c mklocale -s d --description 'Turns on debugging messages.'
complete -c mklocale -s o --description 'Specify output file.'

