# mktemp
# Autogenerated from man page /usr/share/man/man1/mktemp.1
# using Darwin man parser
complete -c mktemp -s d --description 'Make a directory instead of a file.'
complete -c mktemp -s q --description 'Fail silently if an error occurs.'
complete -c mktemp -s t --description 'Generate a template (using the supplied prefix … [See Man Page]'
complete -c mktemp -s u --description 'Operate in unsafe mode.'

