# mount_fdesc
# Autogenerated from man page /usr/share/man/man8/mount_fdesc.8
# using Darwin man parser
complete -c mount_fdesc -s o --description 'Options are specified with a o flag followed by… [See Man Page]'

