# mount_webdav
# Autogenerated from man page /usr/share/man/man8/mount_webdav.8
# using Darwin man parser
complete -c mount_webdav -s s --description 'Require that authentication credentials be sent… [See Man Page]'
complete -c mount_webdav -s S --description 'Suppresses all user interface including the aut… [See Man Page]'
complete -c mount_webdav -s i --description 'Interactive mode, you are prompted for the user… [See Man Page]'
complete -c mount_webdav -s o --description 'Options passed to mount 2 are specified with th… [See Man Page]'
complete -c mount_webdav -s v --description 'Allows the volume_name attribute (ATTR_VOL_NAME… [See Man Page]'

