# mount
# Autogenerated from man page /usr/share/man/man8/mount.8
# using Darwin man parser
complete -c mount -s a --description 'All the filesystems listed via getfsent 3 are mounted.'
complete -c mount -s d --description 'Causes everything to be done except for the actual system call.'
complete -c mount -s f --description 'Forces the revocation of write access when tryi… [See Man Page]'
complete -c mount -s o --description 'Options are specified with a o flag followed by… [See Man Page]'
complete -c mount -s r --description 'Mount the file system read-only (even the super… [See Man Page]'
complete -c mount -s t --description 'The argument following the t is used to indicat… [See Man Page]'
complete -c mount -s u --description 'The u flag indicates that the status of an alre… [See Man Page]'
complete -c mount -s v --description 'Verbose mode.'
complete -c mount -s w --description 'Mount the file system read-write.'

