# mount_smbfs
# Autogenerated from man page /usr/share/man/man8/mount_smbfs.8
# using Darwin man parser
complete -c mount_smbfs -s N --description 'Do not ask for a password.'
complete -c mount_smbfs -s o --description 'Options passed to mount 2 are specified with th… [See Man Page]'
complete -c mount_smbfs -s f --description 'Specify permissions that should be assigned to … [See Man Page]'
complete -c mount_smbfs -s h --description 'Prints a help message, much like the SYNOPSIS above.'
complete -c mount_smbfs -s s --description 'Force a new session to be created to the server.'
complete -c mount_smbfs -s v --description 'Prints version.'

