# mount_hfs
# Autogenerated from man page /usr/share/man/man8/mount_hfs.8
# using Darwin man parser
complete -c mount_hfs -s e --description 'Specify the Macintosh encoding.'
complete -c mount_hfs -s u --description 'Set the owner of the files in the file system to user.'
complete -c mount_hfs -s g --description 'Set the group of the files in the file system to group.'
complete -c mount_hfs -s m --description 'Specify the maximum file permissions for files … [See Man Page]'
complete -c mount_hfs -s o --description 'Options are specified with a o flag followed by… [See Man Page]'
complete -c mount_hfs -s j --description 'Ignore the journal for this mount.'
complete -c mount_hfs -s w --description 'Mount the HFS wrapper volume.'
complete -c mount_hfs -s x --description 'Disable execute permissions on a standard HFS file system.'

