# mount_msdos
# Autogenerated from man page /usr/share/man/man8/mount_msdos.8
# using Darwin man parser
complete -c mount_msdos -s o --description 'Use the specified mount options, as described in mount 8.'
complete -c mount_msdos -s u --description 'Set the owner of the files in the file system to uid.'
complete -c mount_msdos -s g --description 'Set the group of the files in the file system to gid.'
complete -c mount_msdos -s m --description 'Specify the maximum file permissions for files … [See Man Page]'

