# mount_ntfs
# Autogenerated from man page /usr/share/man/man8/mount_ntfs.8
# using Darwin man parser
complete -c mount_ntfs -s s --description 'Mount the volume using case sensitive semantics.'
complete -c mount_ntfs -s o --description 'Options are specified with a o flag followed by… [See Man Page]'

