# mount_udf
# Autogenerated from man page /usr/share/man/man8/mount_udf.8
# using Darwin man parser
complete -c mount_udf -s o --description 'Options are specified with a o flag followed by… [See Man Page]'
complete -c mount_udf -s v --description 'This is an advanced option not useful for regular use.'
complete -c mount_udf -s s --description 'This is an advanced option not useful for regular use.'
complete -c mount_udf -s n --description 'This is an advanced option not useful for regular use.'
complete -c mount_udf -s b --description 'This is an advanced option not useful for regular use.'
complete -c mount_udf -s p --description 'This is an advanced option not useful for regular use.'
complete -c mount_udf -s w --description 'This is an advanced option not useful for regular use.'

