# mountd
# Autogenerated from man page /usr/share/man/man8/mountd.8
# using Darwin man parser
complete -c mountd -s n --description '.'
complete -c mountd -s r --description 'exportsfile Ta Fl F Pa exportsfile Ta alternate… [See Man Page]'

