# mount_ftp
# Autogenerated from man page /usr/share/man/man8/mount_ftp.8
# using Darwin man parser
complete -c mount_ftp -s i --description 'Interactive mode, you are prompted for the user… [See Man Page]'
complete -c mount_ftp -s o --description 'Options passed to mount 2 are specified with th… [See Man Page]'

