# msdos
# Autogenerated from man page /usr/share/man/man8/msdos.util.8
# using Darwin man parser
complete -c msdos -s m --description 'mount.'
complete -c msdos -s n --description 'set name.'
complete -c msdos -s p --description 'probe for mounting.'
complete -c msdos -s u --description 'unmount.'
complete -c msdos -s k --description 'print volume UUID El Pp mountflags above are ei… [See Man Page]'

