# msgs
# Autogenerated from man page /usr/share/man/man1/msgs.1
# using Darwin man parser
complete -c msgs -s y --description 'Type the rest of the message.  RETURN Synonym for y.'
complete -c msgs -s n --description 'Skip this message and go on to the next message.'
complete -c msgs -s q --description 'Drop out of msgs ; the next time msgs will pick… [See Man Page]'
complete -c msgs -s s --description 'Append the current message to the file ``Messag… [See Man Page]'
complete -c msgs -s m --description 'A copy of the specified message is placed in a … [See Man Page]'
complete -c msgs -s f --description 'Do not say ``No new messages. \'\'.  This is useful in a .'
complete -c msgs -s h --description 'Print the first part of messages only.'
complete -c msgs -s l --description 'Cause only locally originated messages to be reported.'
complete -c msgs -s p --description 'Pipe long messages through more  1 .'

