# mtree
# Autogenerated from man page /usr/share/man/man8/mtree.8
# using Darwin man parser
complete -c mtree -s c --description 'Print a specification for the file hierarchy to… [See Man Page]'
complete -c mtree -s d --description 'Ignore everything except directory type files.  ==========.'
complete -c mtree -s e --description 'Do not complain about files that are in the fil… [See Man Page]'
complete -c mtree -s f --description 'Read the specification from file, instead of fr… [See Man Page]'
complete -c mtree -s i --description 'Indent the output 4 spaces each time a director… [See Man Page]'
complete -c mtree -s K --description 'Add the specified (whitespace or comma separate… [See Man Page]'
complete -c mtree -s k --description 'Use the ``type\'\' keyword plus the specified (wh… [See Man Page]'
complete -c mtree -s L --description 'Follow all symbolic links in the file hierarchy.  ==========.'
complete -c mtree -s n --description 'Do not emit pathname comments when creating a specification.'
complete -c mtree -s P --description 'Do not follow symbolic links in the file hierar… [See Man Page]'
complete -c mtree -s p --description 'Use the file hierarchy rooted in path, instead … [See Man Page]'
complete -c mtree -s q --description 'Quiet mode.'
complete -c mtree -s r --description 'Remove any files in the file hierarchy that are… [See Man Page]'
complete -c mtree -s s --description 'Display a single checksum to the standard error… [See Man Page]'
complete -c mtree -s U --description 'Modify the owner, group, permissions, and modif… [See Man Page]'
complete -c mtree -s u --description 'Same as U except a status of 2 is returned if t… [See Man Page]'
complete -c mtree -s w --description 'Make some error conditions non-fatal warnings.  ==========.'
complete -c mtree -s X --description 'The specified file contains fnmatch 3 patterns … [See Man Page]'
complete -c mtree -s x --description 'Do not descend below mount points in the file hierarchy.'

