# native2ascii
# Autogenerated from man page /usr/share/man/man1/native2ascii.1
# using Deroffing man parser
complete -c native2ascii -o encoding --description 'Specifies the encoding name that is used by the… [See Man Page]'
complete -c native2ascii -o reverse --description 'Performs the reverse operation: converts a file… [See Man Page]'
complete -c native2ascii -s J --description 'Pass option to the Java virtual machine, where … [See Man Page]'
complete -c native2ascii -o J-Xms48m --description 'sets the startup memory to 48 megabytes.'

