# natutil
# Autogenerated from man page /usr/share/man/man8/natutil.8
# using Darwin man parser
complete -c natutil -s 1 --description 'Only return data if the IGD found is also our current gateway.'
complete -c natutil -s a --description 'AirPort only The authentication string to use w… [See Man Page]'
complete -c natutil -s i --description 'Get the authentication string interactively.'
complete -c natutil -s d --description 'Reports the IGDs (Internet Gateway Devices) tha… [See Man Page]'
complete -c natutil -s m --description 'Retrieves the port mapping table from the NAT.'
complete -c natutil -s n --description 'The prefix of the targeted NAT device\'s name (u… [See Man Page]'
complete -c natutil -s p --description 'A comma-separated list of the ports to tap or untap.'
complete -c natutil -s s --description 'Retrieves the WAN & LAN status and configuration from the IGD.'
complete -c natutil -s t --description 'Configures the NAT to forward the given ports to this machine.'
complete -c natutil -s u --description 'Removes the given ports from the NAT\'s port forwarding rules.'
complete -c natutil -s v --description 'Verbose output.'
complete -c natutil -s x --description 'XML output.  This option provides the most information.'
complete -c natutil -s L --description 'AirPort only Convert existing DHCP lease into a… [See Man Page]'
complete -c natutil -s T --description 'Ports will be tapped / untapped for the TCP protocol.'
complete -c natutil -s U --description 'Ports will be tapped / untapped for the UDP protocol.'

