# ncal
# Autogenerated from man page /usr/share/man/man1/ncal.1
# using Darwin man parser
complete -c ncal -s J --description 'Display Julian Calendar, if combined with the e… [See Man Page]'
complete -c ncal -s e --description 'Display date of easter (for western churches).'
complete -c ncal -s j --description 'Display Julian days (days one-based, numbered from January 1).'
complete -c ncal -s m --description 'Display the specified month.'
complete -c ncal -s o --description 'Display date of orthodox easter (Greek and Russ… [See Man Page]'
complete -c ncal -s p --description 'Print the country codes and switching days from… [See Man Page]'
complete -c ncal -s s --description 'Assume the switch from Julian to Gregorian Cale… [See Man Page]'
complete -c ncal -s w --description 'Print the number of the week below each week column.'
complete -c ncal -s y --description 'Display a calendar for the specified year.'

