# ncdestroy
# Autogenerated from man page /usr/share/man/man1/ncdestroy.1
# using Darwin man parser
complete -c ncdestroy -s v --description 'Be verbose and show what file system is being o… [See Man Page]'
complete -c ncdestroy -s P --description 'If the trailing component resolves to a symboli… [See Man Page]'

