# ncurses5
# Autogenerated from man page /usr/share/man/man1/ncurses5.4-config.1
# using Darwin man parser
complete -c ncurses5 -l -prefix --description 'Reports package-prefix ncurses5 was installed with.'
complete -c ncurses5 -l -exec-prefix --description 'Reports executable-prefix ncurses5 was installed with.'
complete -c ncurses5 -l -cflags --description 'Reports C compiler flags needed to compile with ncurses.'
complete -c ncurses5 -l -libs --description 'Reports libraries needed to link with ncurses.'
complete -c ncurses5 -l -version --description 'Reports release+patchdate version ncurses5 was installed with.'
complete -c ncurses5 -l -abi-version --description 'Reports ABI version ncurses5 was installed with.'
complete -c ncurses5 -l -mouse-version --description 'Reports mouse-interface version ncurses5 was installed with.'
complete -c ncurses5 -l -bindir --description 'Reports directory containing ncurses5 programs.'
complete -c ncurses5 -l -datadir --description 'Reports directory containing ncurses5 data.'
complete -c ncurses5 -l -libdir --description 'Reports directory containing ncurses5 libraries.'
complete -c ncurses5 -l -mandir --description 'Reports directory containing ncurses5 manpages.'
complete -c ncurses5 -l -terminfo --description 'Reports $TERMINFO terminfo database path.'
complete -c ncurses5 -l -terminfo-dirs --description 'Reports $TERMINFO_DIRS directory list.'
complete -c ncurses5 -l -termpath --description 'Reports $TERMPATH termcap list El EXIT STATUS -std.'

