# ndp
# Autogenerated from man page /usr/share/man/man8/ndp.8
# using Darwin man parser
complete -c ndp -s a --description 'Dump the currently existing NDP entries.'
complete -c ndp -s A --description 'Repeat a (dump NDP entries) every wait seconds.'
complete -c ndp -s c --description 'Erase all the NDP entries.'
complete -c ndp -s d --description 'Delete specified NDP entry.'
complete -c ndp -s f --description 'Parse the file specified by filename.'
complete -c ndp -s H --description 'Harmonize consistency between the routing table… [See Man Page]'
complete -c ndp -s I --description 'Shows or specifies the default interface used a… [See Man Page]'
complete -c ndp -s i --description 'View ND information for the specified interface.'
complete -c ndp -s l --description 'Show link-layer reachability information.'
complete -c ndp -s n --description 'Do not try to resolve numeric address to hostname.'
complete -c ndp -s p --description 'Show prefix list.'
complete -c ndp -s P --description 'Flush all the entries in the prefix list.'
complete -c ndp -s r --description 'Show default router list.'
complete -c ndp -s R --description 'Flush all the entries in the default router list.'
complete -c ndp -s s --description 'Register an NDP entry for a node.'
complete -c ndp -s t --description 'Print timestamp on each entries, to make it pos… [See Man Page]'
complete -c ndp -s x --description 'Show extended link-layer reachability informati… [See Man Page]'
complete -c ndp -s w --description 'Show the cryptographically generated address (C… [See Man Page]'

