# netbiosd
# Autogenerated from man page /usr/share/man/man8/netbiosd.8
# using Darwin man parser
complete -c netbiosd -o debug --description 'The service will log extensive debug informatio… [See Man Page]'
complete -c netbiosd -o dump-packets --description 'Pretty-print all sent and received NetBIOS pack… [See Man Page]'
complete -c netbiosd -o help --description 'Prints a usage message and exits.'
complete -c netbiosd -o max-refresh --description 'Maximum time (in seconds) between searches to r… [See Man Page]'
complete -c netbiosd -o min-refresh --description 'Minimum time (in seconds) between searches to r… [See Man Page]'
complete -c netbiosd -o stdout --description 'Causes netbiosd to print log messages to standa… [See Man Page]'

