# netlog
# Autogenerated from man page /usr/share/man/man1/netlog.1
# using Darwin man parser
complete -c netlog -s v --description 'Verbose output.'
complete -c netlog -s i --description 'Report socket statistics periodically.'
complete -c netlog -s I --description 'Used in combination with i, will make netlog ex… [See Man Page]'

