# newfs_hfs
# Autogenerated from man page /usr/share/man/man8/newfs_hfs.8
# using Darwin man parser
complete -c newfs_hfs -s N --description 'Causes the file system parameters to be printed… [See Man Page]'
complete -c newfs_hfs -s U --description 'Set the owner of the file system\'s root directory to uid.'
complete -c newfs_hfs -s G --description 'Set the group of the file system\'s root directory to gid.'
complete -c newfs_hfs -s M --description 'Specify the octal access permissions mask for t… [See Man Page]'
complete -c newfs_hfs -s P --description 'Set kHFSContentProtectionBit in the volume\'s at… [See Man Page]'
complete -c newfs_hfs -s s --description 'Creates a case-sensitive HFS Plus filesystem.'
complete -c newfs_hfs -s b --description 'The allocation block size of the file system.'
complete -c newfs_hfs -s c --description 'This specifies the clump and/or initial sizes, … [See Man Page]'
complete -c newfs_hfs -s i --description 'This specifies the initial catalog node ID for … [See Man Page]'
complete -c newfs_hfs -s J --description 'Creates a journaled HFS+ volume.'
complete -c newfs_hfs -s n --description 'This specifies the b-tree node sizes, in bytes,… [See Man Page]'
complete -c newfs_hfs -s v --description 'Volume name (file system name) in ascii or UTF-8 format.'

