# newfs_exfat
# Autogenerated from man page /usr/share/man/man8/newfs_exfat.8
# using Darwin man parser
complete -c newfs_exfat -s N --description 'Don\'t create a file system: just print out parameters.'
complete -c newfs_exfat -s R --description 'Do not check whether the device is currently fo… [See Man Page]'
complete -c newfs_exfat -s I --description 'Volume ID, a 32-bit integer.'
complete -c newfs_exfat -s S --description 'Number of bytes per sector.'
complete -c newfs_exfat -s a --description 'Number of sectors per FAT.'
complete -c newfs_exfat -s b --description 'File system block size (bytes per cluster).'
complete -c newfs_exfat -s c --description 'Sectors per cluster.'
complete -c newfs_exfat -s n --description 'Number of FATs.   Acceptable values are 1 or 2.'
complete -c newfs_exfat -s s --description 'The total number of sectors in the device.'
complete -c newfs_exfat -s v --description 'Volume name (label).'

