# newsyslog
# Autogenerated from man page /usr/share/man/man8/newsyslog.8
# using Darwin man parser
complete -c newsyslog -s f --description 'Instruct newsyslog to use config_file instead o… [See Man Page]'
complete -c newsyslog -s a --description 'Specify a directory into which archived log fil… [See Man Page]'
complete -c newsyslog -s d --description 'Specify a directory which all log files will be relative to.'
complete -c newsyslog -s v --description 'Place newsyslog in verbose mode.'
complete -c newsyslog -s n --description 'Cause newsyslog not to trim the logs, but to pr… [See Man Page]'
complete -c newsyslog -s r --description 'Remove the restriction that newsyslog must be running as root.'
complete -c newsyslog -s s --description 'Specify that newsyslog should not send any sign… [See Man Page]'
complete -c newsyslog -s C --description 'If specified once, then newsyslog will create a… [See Man Page]'
complete -c newsyslog -s F --description 'Force newsyslog to trim the logs, even if the t… [See Man Page]'
complete -c newsyslog -s N --description 'Do not perform any rotations.'
complete -c newsyslog -s R --description 'Specify that newsyslog should rotate a given li… [See Man Page]'

