# nfsd
# Autogenerated from man page /usr/share/man/man8/nfsd.8
# using Darwin man parser
complete -c nfsd -s F --description 'The exports_file argument specifies an alternat… [See Man Page]'
complete -c nfsd -s N --description 'Allow non-root mount requests to be served.'
complete -c nfsd -s P --description 'Specifies which port to use for the MOUNT service.'
complete -c nfsd -s R --description 'Allow mount RPCs requests for regular files to be served.'
complete -c nfsd -s n --description 'Specifies how many NFS server threads to create.'
complete -c nfsd -s p --description 'Specifies which port to use for the NFS service… [See Man Page]'
complete -c nfsd -s r --description 'Register the NFS service with portmap 8.'
complete -c nfsd -s t --description 'Serve TCP NFS clients.'
complete -c nfsd -s u --description 'Serve UDP NFS clients.'
complete -c nfsd -s v --description 'Increase nfsd Ns \'s logging level by one (may b… [See Man Page]'

