# nl
# Autogenerated from man page /usr/share/man/man1/nl.1
# using Darwin man parser
complete -c nl -s b --description 'Specify the logical page body lines to be numbered.'
complete -c nl -s d --description 'Specify the delimiter characters used to indica… [See Man Page]'
complete -c nl -s f --description 'Specify the same as b Ar type except for logica… [See Man Page]'
complete -c nl -s h --description 'Specify the same as b Ar type except for logica… [See Man Page]'
complete -c nl -s i --description 'Specify the increment value used to number logical page lines.'
complete -c nl -s l --description 'If numbering of all lines is specified for the … [See Man Page]'
complete -c nl -s n --description 'Specify the line numbering output format.'
complete -c nl -s p --description 'Specify that line numbering should not be resta… [See Man Page]'
complete -c nl -s s --description 'Specify the characters used in separating the l… [See Man Page]'
complete -c nl -s v --description 'Specify the initial value used to number logica… [See Man Page]'
complete -c nl -s w --description 'Specify the number of characters to be occupied… [See Man Page]'

