# notifyutil
# Autogenerated from man page /usr/share/man/man1/notifyutil.1
# using Darwin man parser
complete -c notifyutil -s p --description 'Post a notification for key.'
complete -c notifyutil -s w --description 'Register for key and wait forever for notifications.'
complete -c notifyutil -s '#' --description 'Register for key and wait for # (an integer) notifications.'
complete -c notifyutil -s g --description 'Get state value for key.'
complete -c notifyutil -s s --description 'Set state value for key.'
complete -c notifyutil -o port --description 'Use mach port notifications for subsequent w or… [See Man Page]'
complete -c notifyutil -o file --description 'Use file descriptor notifications for subsequent registrations.'
complete -c notifyutil -o check --description 'Use shared memory notifications for subsequent registrations.'
complete -c notifyutil -o signal --description 'Use signal notifications for subsequent registrations.'
complete -c notifyutil -o dispatch --description 'Use dispatch for subsequent registrations.'

