# npm-install
# Autogenerated from man page /usr/local/share/man/man1/npm-install.1
# using Deroffing man parser
complete -c npm-install -l save: --description 'o 2.'
complete -c npm-install -l save-dev: --description 'o 2.'
complete -c npm-install -l save-optional: --description 'When using any of the above options to save dep… [See Man Page]'
complete -c npm-install -l save-exact: --description 'exact version rather than using npm\'s default s… [See Man Page]'

