# npm-uninstall
# Autogenerated from man page /usr/local/share/man/man1/npm-uninstall.1
# using Deroffing man parser
complete -c npm-uninstall -l save: --description 'o 2.'
complete -c npm-uninstall -l save-dev: --description 'o 2.'
complete -c npm-uninstall -l save-optional: --description 'Scope is optional and follows the usual rules f… [See Man Page]'

