# nroff
# Autogenerated from man page /usr/share/man/man1/nroff.1
# using Deroffing man parser
complete -c nroff -s T --description 'option, selecting the output encoding emitted b… [See Man Page]'
complete -c nroff -s h --description 'and.'
complete -c nroff -s c --description 'options are equivalent to grotty \'s options.'
complete -c nroff -s d --description '.'
complete -c nroff -s C --description '.'
complete -c nroff -s i --description '.'
complete -c nroff -s M --description '.'
complete -c nroff -s m --description '.'
complete -c nroff -s n --description '.'
complete -c nroff -s o --description 'and.'
complete -c nroff -s r --description 'options have the effect described in troff (1).'
complete -c nroff -s e --description '.'
complete -c nroff -s q --description 'and.'
complete -c nroff -s s --description '(which are not implemented in troff ).  Options .'
complete -c nroff -s p --description '(pic),.'
complete -c nroff -s t --description '(tbl),.'
complete -c nroff -s S --description '(safer), and.'
complete -c nroff -s U --description '(unsafe) are passed to groff .'
complete -c nroff -s v --description 'shows the version number.'

