# nvram
# Autogenerated from man page /usr/share/man/man8/nvram.8
# using Deroffing man parser
complete -c nvram -s d --description 'Deletes the named firmware variable. \\" ==========.'
complete -c nvram -s f --description 'Set firmware variables from a text file.'
complete -c nvram -s x --description 'Use XML format for reading and writing variables.'
complete -c nvram -s c --description 'Delete all of the firmware variables.'
complete -c nvram -s p --description 'or.'

