# od
# Autogenerated from man page /usr/share/man/man1/od.1
# using Darwin man parser
complete -c od -s A --description 'Specify the input address base.'
complete -c od -s a --description 'Output named characters.  Equivalent to t Ar a.'
complete -c od -s B --description 'Output octal shorts.  Equivalent to t Ar o2.'
complete -c od -s b --description 'Output octal bytes.  Equivalent to t Ar o1.'
complete -c od -s c --description 'Output C-style escaped characters.  Equivalent to t Ar c.'
complete -c od -s D --description 'Output unsigned decimal ints.  Equivalent to t Ar u4.'
complete -c od -s e --description 'Output double-precision floating point numbers.'
complete -c od -s f --description 'Output single-precision floating point numbers.'
complete -c od -s H --description 'Output hexadecimal ints.  Equivalent to t Ar x4.'
complete -c od -s h --description 'Output hexadecimal shorts.  Equivalent to t Ar x2.'
complete -c od -s I --description 'Output signed decimal longs.  Equivalent to t Ar dL.'
complete -c od -s i --description 'Output signed decimal ints.  Equivalent to t Ar dI.'
complete -c od -s j --description 'Skip skip bytes of the combined input before dumping.'
complete -c od -s N --description 'Dump at most length bytes of input.'
complete -c od -s O --description 'Output octal ints.  Equivalent to t Ar o4.'
complete -c od -s s --description 'Output signed decimal shorts.  Equivalent to t Ar d2.'
complete -c od -s t --description 'Specify the output format.'
complete -c od -s v --description 'Write all input data, instead of replacing line… [See Man Page]'

