# odmigrationtool
# Autogenerated from man page /usr/share/man/man1/odmigrationtool.1
# using Darwin man parser
complete -c odmigrationtool -o source --description 'source volume or path to migrate from.'
complete -c odmigrationtool -o target --description 'destination volume or path to mirage to.'

