# openman
# Autogenerated from man page /usr/local/share/man/man1/openman.1
# using Deroffing man parser
complete -c openman -s k --description 'flag is specified, then apropos(1) mode is used… [See Man Page]'
complete -c openman -s b --description 'flag is specfied, ManOpen.'
complete -c openman -s M --description 'or.'
complete -c openman -s m --description 'flag.'
complete -c openman -s f --description 'flag.'

