# opensnoop
# Autogenerated from man page /usr/share/man/man1/opensnoop.1m
# using Deroffing man parser
complete -c opensnoop -s a --description 'print all data.'
complete -c opensnoop -s A --description 'dump all data, space delimited.'
complete -c opensnoop -s c --description 'print current working directory of process.'
complete -c opensnoop -s e --description 'print errno value.'
complete -c opensnoop -s F --description 'print the flags passed to open.'
complete -c opensnoop -s g --description 'print full command arguments.'
complete -c opensnoop -s s --description 'print start time, us.'
complete -c opensnoop -s t --description 'print user stack trace.'
complete -c opensnoop -s v --description 'print start time, string.'
complete -c opensnoop -s x --description 'only print failed opens.'
complete -c opensnoop -s Z --description 'print zonename.'
complete -c opensnoop -s f --description 'file pathname to snoop.'
complete -c opensnoop -s n --description 'process name to snoop.'
complete -c opensnoop -s p --description 'process ID to snoop.'

