# open
# Autogenerated from man page /usr/share/man/man1/open.1
# using Darwin man parser
complete -c open -s a --description 'Specifies the application to use for opening the file.'
complete -c open -s b --description 'Specifies the bundle identifier for the applica… [See Man Page]'
complete -c open -s e --description 'Causes the file to be opened with /Applications/TextEdit.'
complete -c open -s t --description 'Causes the file to be opened with the default t… [See Man Page]'
complete -c open -s f --description 'Reads input from standard input and opens the r… [See Man Page]'
complete -c open -s F --description 'Opens the application "fresh," that is, without… [See Man Page]'
complete -c open -s W --description 'Causes open to wait until the applications it o… [See Man Page]'
complete -c open -s R --description 'Reveals the file(s) in the Finder instead of opening them.'
complete -c open -s n --description 'Open a new instance of the application(s) even … [See Man Page]'
complete -c open -s g --description 'Do not bring the application to the foreground.'
complete -c open -s h --description 'Searches header locations for a header whose na… [See Man Page]'
complete -c open -l args --description 'All remaining arguments are passed to the opene… [See Man Page]'

