# osascript
# Autogenerated from man page /usr/share/man/man1/osascript.1
# using Darwin man parser
complete -c osascript -s e --description 'Enter one line of a script.'
complete -c osascript -s i --description 'Interactive mode: osascript will prompt for one… [See Man Page]'
complete -c osascript -s l --description 'Override the language for any plain text files.'
complete -c osascript -s s --description 'Modify the output style.'

