# ostraceutil
# Autogenerated from man page /usr/share/man/man1/ostraceutil.1
# using Darwin man parser
complete -c ostraceutil -o diagnostic --description 'Generate a diagnostic for a given process, will… [See Man Page]'
complete -c ostraceutil -o errors --description 'Watch for software errors triggered by processes.'
complete -c ostraceutil -o faults --description 'Watch for software faults triggered by processes.'
complete -c ostraceutil -o list --description 'Will list all available trace related strings for a binary.'
complete -c ostraceutil -o parent --description 'All related trace messages for parent process.'
complete -c ostraceutil -o process --description 'Only trace messages specific to the process (ex… [See Man Page]'
complete -c ostraceutil -o quiet --description 'Reduce the amount of duplicate information in o… [See Man Page]'
complete -c ostraceutil -o timeout --description 'Timeout a watch event after a specified number of seconds.'
complete -c ostraceutil -o watch --description 'Watch for trace messages or other events for a … [See Man Page]'

