# otest
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/otest.1
# using Darwin man parser
complete -c otest -o SenTest --description 'This flag denotes the scope of the unit test to be run.'

