# paste
# Autogenerated from man page /usr/share/man/man1/paste.1
# using Darwin man parser
complete -c paste -s d --description 'Use one or more of the provided characters to r… [See Man Page]'
complete -c paste -s s --description 'Concatenate all of the lines of each separate i… [See Man Page]'

