# pathchk
# Autogenerated from man page /usr/share/man/man1/pathchk.1
# using Darwin man parser
complete -c pathchk -s p --description 'Perform portability checks on the specified pathname arguments.'

