# path_helper
# Autogenerated from man page /usr/share/man/man8/path_helper.8
# using Darwin man parser
complete -c path_helper -s c --description 'Generate C-shell commands on stdout.'
complete -c path_helper -s s --description 'Generate Bourne shell commands on stdout.'

