# pbs
# Autogenerated from man page /usr/share/man/man8/pbs.8
# using Darwin man parser
complete -c pbs -o debug --description 'Output debugging information regarding what pbs is doing.'
complete -c pbs -o dump_pboard --description 'Prints the private pasteboard containing the cu… [See Man Page]'
complete -c pbs -o dump_userdefs --description 'Prints the userdef cache of Services information.'
complete -c pbs -o flush_pboard --description 'Erases the private pasteboard containing Services information.'
complete -c pbs -o flush_userdefs --description 'Erases the userdef cache.'
complete -c pbs -o flush --description 'Equivalent to -flush_pboard and -flush_userdefs… [See Man Page]'

