# pdisk
# Autogenerated from man page /usr/share/man/man8/pdisk.8
# using Darwin man parser
complete -c pdisk -s a --description '.'
complete -c pdisk -l abbr --description 'Abbreviate the partition types shown in the partition list.'
complete -c pdisk -s c --description '.'
complete -c pdisk -l compute_size --description 'Causes pdisk to always ignore the device size l… [See Man Page]'
complete -c pdisk -s d --description '.'
complete -c pdisk -l debug --description 'Turns on debugging.'
complete -c pdisk -s f --description '.'
complete -c pdisk -l fname --description 'Show HFS volume names instead of partition name when available.'
complete -c pdisk -s h --description '.'
complete -c pdisk -l help --description 'Prints a short help message.'
complete -c pdisk -s i --description '.'
complete -c pdisk -l interactive --description 'Causes pdisk to go into an interactive mode sim… [See Man Page]'
complete -c pdisk -s l --description '.'
complete -c pdisk -l list --description 'If no device argument is given, pdisk tries to … [See Man Page]'
complete -c pdisk -s L --description '.'
complete -c pdisk -l logical --description 'Show partition limits in logical blocks.'
complete -c pdisk -s r --description '.'
complete -c pdisk -l readonly --description 'Prevents pdisk from writing to the device.'
complete -c pdisk -s v --description '.'
complete -c pdisk -l version --description 'Prints the version number of pdisk.'

