# pkill
# Autogenerated from man page /usr/share/man/man1/pkill.1
# using Darwin man parser
complete -c pkill -s F --description 'Restrict matches to a process whose PID is stor… [See Man Page]'
complete -c pkill -s G --description 'Restrict matches to processes with a real group… [See Man Page]'
complete -c pkill -s I --description 'Request confirmation before attempting to signal each process.'
complete -c pkill -s L --description 'The pidfile file given for the F option must be… [See Man Page]'
complete -c pkill -s P --description 'Restrict matches to processes with a parent pro… [See Man Page]'
complete -c pkill -s U --description 'Restrict matches to processes with a real user … [See Man Page]'
complete -c pkill -s d --description 'Specify a delimiter to be printed between each process ID.'
complete -c pkill -s a --description 'Include process ancestors in the match list.'
complete -c pkill -s f --description 'Match against full argument lists.'
complete -c pkill -s g --description 'Restrict matches to processes with a process gr… [See Man Page]'
complete -c pkill -s i --description 'Ignore case distinctions in both the process ta… [See Man Page]'
complete -c pkill -s l --description 'Long output.'
complete -c pkill -s n --description 'Select only the newest (most recently started) … [See Man Page]'
complete -c pkill -s o --description 'Select only the oldest (least recently started)… [See Man Page]'
complete -c pkill -s q --description 'Do not write anything to standard output.'
complete -c pkill -s t --description 'Restrict matches to processes associated with a… [See Man Page]'
complete -c pkill -s u --description 'Restrict matches to processes with an effective… [See Man Page]'
complete -c pkill -s v --description 'Reverse the sense of the matching; display proc… [See Man Page]'
complete -c pkill -s x --description 'Require an exact match of the process name, or … [See Man Page]'
complete -c pkill -o signal --description 'A non-negative decimal number or symbolic signa… [See Man Page]'

