# pl
# Autogenerated from man page /usr/share/man/man1/pl.1
# using Darwin man parser
complete -c pl -l input --description 'Cause pl to use the specified file as input.'
complete -c pl -l output --description 'Cause pl to use the specified file as output.'

