# PlistBuddy
# Autogenerated from man page /usr/share/man/man8/PlistBuddy.8
# using Darwin man parser
complete -c PlistBuddy -s c --description 'Execute command and exit.'
complete -c PlistBuddy -s x --description 'Output will be in the form of an xml plist where appropriate.'
complete -c PlistBuddy -s h --description 'Print the complete help info.'

