# plockstat
# Autogenerated from man page /usr/share/man/man1/plockstat.1
# using Deroffing man parser
complete -c plockstat -s v --description 'print a message when tracing starts.'
complete -c plockstat -s A --description 'trace contention and hold events (same as -CH).'
complete -c plockstat -s C --description 'trace contention events for mutexes and rwlocks.'
complete -c plockstat -s H --description 'trace hold events for mutexes and rwlocks.'
complete -c plockstat -s V --description 'print the dtrace script to run.'
complete -c plockstat -s n --description 'display only \'count\' entries for each event type.'
complete -c plockstat -s s --description 'show stack trace upto \'depth\' entries.'
complete -c plockstat -s e --description 'exit after specified seconds.'
complete -c plockstat -s x --description 'enable a DTrace runtime option or a D compiler option.'
complete -c plockstat -s p --description 'attach and trace the specified process id SEE ALSO dtrace(1).'

