# pluginkit
# Autogenerated from man page /usr/share/man/man8/pluginkit.8
# using Darwin man parser
complete -c pluginkit -s A --description 'Matches find all versions of a given plug-in kn… [See Man Page]'
complete -c pluginkit -s a --description 'Explicitly adds plugins at the file location(s)… [See Man Page]'
complete -c pluginkit -s e --description 'Perform a matching operation (see -m) and apply… [See Man Page]'
complete -c pluginkit -s D --description 'Matches find all physical instances of a given … [See Man Page]'
complete -c pluginkit -s i --description 'Specifies a plug-in identifier to match, a shor… [See Man Page]'
complete -c pluginkit -s l --description 'When matching plugins, requests only the latest… [See Man Page]'
complete -c pluginkit -s m --description 'Requests pluginkit to scan all registered plug-… [See Man Page]'
complete -c pluginkit -s p --description 'Specifies a plug-in protocol to  match, a short… [See Man Page]'
complete -c pluginkit -s r --description 'Explicitly removes plugins at the file location(s) given.'
complete -c pluginkit -l raw --description 'Present replies from the management daemon (pkd… [See Man Page]'
complete -c pluginkit -s v --description 'Asks for more verbose operation.'

