# plutil
# Autogenerated from man page /usr/share/man/man1/plutil.1
# using Darwin man parser
complete -c plutil -o help --description 'Show the usage information for the command and exit.'
complete -c plutil -s p --description 'Print the property list in a human-readable fashion.'
complete -c plutil -o lint --description 'Check the named property list files for syntax errors.'
complete -c plutil -o convert --description 'Convert the named file to the indicated format … [See Man Page]'
complete -c plutil -s s --description 'Don\'t print anything on success.'
complete -c plutil -s r --description 'For JSON, add whitespace and indentation to mak… [See Man Page]'
complete -c plutil -s o --description 'Specify an alternate path name for the result o… [See Man Page]'
complete -c plutil -s e --description 'Specify an alternate extension for converted fi… [See Man Page]'

