# pod2man5
# Autogenerated from man page /usr/share/man/man1/pod2man5.18.1
# using Type1
complete -c pod2man5 -o errors --description 'Set the error handling style.'
complete -c pod2man5 -l nourls --description 'Normally, L<> formatting codes with a \\s-1URL\\s… [See Man Page]'

