# postlock
# Autogenerated from man page /usr/share/man/man1/postlock.1
# using Deroffing man parser
complete -c postlock -s c --description 'Read the main.'
complete -c postlock -s l --description 'Override the locking method specified via the m… [See Man Page]'
complete -c postlock -s v --description 'Enable verbose logging for debugging purposes.'

