# postsuper
# Autogenerated from man page /usr/share/man/man1/postsuper.1
# using Deroffing man parser
complete -c postsuper -s s -s p --description 'directories - this includes the incoming, activ… [See Man Page]'
complete -c postsuper -s c --description 'The main.'
complete -c postsuper -s d --description 'Delete one message with the named queue ID from… [See Man Page]'
complete -c postsuper -s h --description 'Put mail "on hold" so that no attempt is made to deliver it.'
complete -c postsuper -s H --description 'Release mail that was put "on hold".'
complete -c postsuper -s r --description 'Requeue the message with the named queue ID fro… [See Man Page]'
complete -c postsuper -s S --description 'A redundant version of -s that requires that lo… [See Man Page]'
complete -c postsuper -s v --description 'Enable verbose logging for debugging purposes.'

