# postmap
# Autogenerated from man page /usr/share/man/man1/postmap.1
# using Deroffing man parser
complete -c postmap -s b --description 'Enable message body query mode.'
complete -c postmap -s c --description 'Read the main.'
complete -c postmap -s d --description 'Search the specified maps for key and remove one entry per map.'
complete -c postmap -s f --description 'Do not fold the lookup key to lower case while … [See Man Page]'
complete -c postmap -s h --description 'Enable message header query mode.'
complete -c postmap -s i --description 'Incremental mode.'
complete -c postmap -s m --description 'Enable MIME parsing with "-b" and "-h".'
complete -c postmap -s N --description 'Include the terminating null character that ter… [See Man Page]'
complete -c postmap -s n --description 'Don\'t include the terminating null character th… [See Man Page]'
complete -c postmap -s o --description 'Do not release root privileges when processing … [See Man Page]'
complete -c postmap -s p --description 'Do not inherit the file access permissions from… [See Man Page]'
complete -c postmap -s q --description 'Search the specified maps for key and write the… [See Man Page]'
complete -c postmap -s r --description 'When updating a table, do not complain about at… [See Man Page]'
complete -c postmap -s s --description 'Retrieve all database elements, and write one l… [See Man Page]'
complete -c postmap -s v --description 'Enable verbose logging for debugging purposes.'
complete -c postmap -s w --description 'When updating a table, do not complain about at… [See Man Page]'

