# postalias
# Autogenerated from man page /usr/share/man/man1/postalias.1
# using Deroffing man parser
complete -c postalias -s c --description 'Read the main.'
complete -c postalias -s d --description 'Search the specified maps for key and remove one entry per map.'
complete -c postalias -s f --description 'Do not fold the lookup key to lower case while … [See Man Page]'
complete -c postalias -s i --description 'Incremental mode.'
complete -c postalias -s N --description 'Include the terminating null character that ter… [See Man Page]'
complete -c postalias -s n --description 'Don\'t include the terminating null character th… [See Man Page]'
complete -c postalias -s o --description 'Do not release root privileges when processing … [See Man Page]'
complete -c postalias -s p --description 'Do not inherit the file access permissions from… [See Man Page]'
complete -c postalias -s q --description 'Search the specified maps for key and write the… [See Man Page]'
complete -c postalias -s r --description 'When updating a table, do not complain about at… [See Man Page]'
complete -c postalias -s s --description 'Retrieve all database elements, and write one l… [See Man Page]'
complete -c postalias -s v --description 'Enable verbose logging for debugging purposes.'
complete -c postalias -s w --description 'When updating a table, do not complain about at… [See Man Page]'

