# postfix
# Autogenerated from man page /usr/share/man/man1/postfix.1
# using Deroffing man parser
complete -c postfix -s c --description 'Read the main. cf and master.'
complete -c postfix -s D --description 'Run each Postfix daemon under control of a debu… [See Man Page]'
complete -c postfix -s v --description 'Enable verbose logging for debugging purposes.'

