# postqueue
# Autogenerated from man page /usr/share/man/man1/postqueue.1
# using Deroffing man parser
complete -c postqueue -s c --description 'The main.'
complete -c postqueue -s f --description 'Flush the queue: attempt to deliver all queued mail.'
complete -c postqueue -s i --description 'Schedule immediate delivery of deferred mail wi… [See Man Page]'
complete -c postqueue -s p --description 'Produce a traditional sendmail-style queue listing.'
complete -c postqueue -s s --description 'Schedule immediate delivery of all mail that is… [See Man Page]'
complete -c postqueue -s v --description 'Enable verbose logging for debugging purposes.'

