# ppdc
# Autogenerated from man page /usr/share/man/man1/ppdc.1.gz
# using Deroffing man parser
complete -c ppdc -s D --description 'Sets the named variable for use in the source file.'
complete -c ppdc -s I --description 'Specifies an alternate include directory.'
complete -c ppdc -s c --description 'Specifies a single message catalog file in GNU … [See Man Page]'
complete -c ppdc -s d --description 'Specifies the output directory for PPD files.'
complete -c ppdc -s l --description 'Specifies one or more languages to use when loc… [See Man Page]'
complete -c ppdc -s m --description 'Specifies that the output filename should be ba… [See Man Page]'
complete -c ppdc -s t --description 'Specifies that PPD files should be tested instead of generated.'
complete -c ppdc -s v --description 'Specifies verbose output, basically a running s… [See Man Page]'
complete -c ppdc -s z --description 'Generates compressed PPD files (filename. ppd. gz).'
complete -c ppdc -l cr --description '.'
complete -c ppdc -l crlf --description '.'
complete -c ppdc -l lf --description 'Specifies the line ending to use - carriage ret… [See Man Page]'

