# ppdhtml
# Autogenerated from man page /usr/share/man/man1/ppdhtml.1.gz
# using Deroffing man parser
complete -c ppdhtml -s D --description 'Sets the named variable for use in the source file.'
complete -c ppdhtml -s I --description 'Specifies an alternate include directory.'

