# ppdi
# Autogenerated from man page /usr/share/man/man1/ppdi.1.gz
# using Deroffing man parser
complete -c ppdi -s I --description 'Specifies an alternate include directory.'
complete -c ppdi -s o --description 'Specifies the PPD source file to update.'

