# pr
# Autogenerated from man page /usr/share/man/man1/pr.1
# using Darwin man parser
complete -c pr -o column --description 'Produce output that is columns wide (default is… [See Man Page]'
complete -c pr -s a --description 'Modify the effect of the column option so that … [See Man Page]'
complete -c pr -s d --description 'Produce output that is double spaced.'
complete -c pr -s e --description 'char Ns gap Xc Expand each input <tab> to the n… [See Man Page]'
complete -c pr -s F --description 'Use a <form-feed> character for new pages, inst… [See Man Page]'
complete -c pr -s f --description 'Same as F but pause before beginning the first … [See Man Page]'
complete -c pr -s h --description 'Use the string header to replace the file name … [See Man Page]'
complete -c pr -s i --description 'char Ns gap Xc In output, replace multiple <spa… [See Man Page]'
complete -c pr -s L --description 'Use locale specified as argument instead of one… [See Man Page]'
complete -c pr -s l --description 'Override the 66 line default and reset the page… [See Man Page]'
complete -c pr -s m --description 'Merge the contents of multiple files.'
complete -c pr -s n --description 'char Ns width Xc Provide width digit line numbering.'
complete -c pr -s o --description 'Each line of output is preceded by offset <spaces>s.'
complete -c pr -s p --description 'Pause before each page if the standard output is a terminal.'
complete -c pr -s r --description 'Write no diagnostic reports on failure to open a file.'
complete -c pr -s s --description 'Separate text columns by the single character c… [See Man Page]'
complete -c pr -s t --description 'Print neither the five-line identifying header … [See Man Page]'
complete -c pr -s w --description 'Set the width of the line to width column posit… [See Man Page]'

