# procsystime
# Autogenerated from man page /usr/share/man/man1/procsystime.1m
# using Deroffing man parser
complete -c procsystime -s a --description 'print all data.'
complete -c procsystime -s c --description 'print syscall counts.'
complete -c procsystime -s e --description 'print elapsed times, ns.'
complete -c procsystime -s o --description 'print CPU times, ns.'
complete -c procsystime -s T --description 'print totals.'
complete -c procsystime -s p --description 'examine this PID.'
complete -c procsystime -s n --description 'examine processes which have this name EXAMPLES.'
complete -c procsystime -o on --description 'Print syscall counts for "tar" processes, # procsystime.'
complete -c procsystime -o cn --description 'Print elapsed and CPU times for "tar" processes, # procsystime.'
complete -c procsystime -o eon --description 'print all details for "bash" processes, # procsystime.'
complete -c procsystime -o aTn --description 'run and print details for "df -h", # procsystime df -h.'

