# pstopdf
# Autogenerated from man page /usr/share/man/man1/pstopdf.1
# using Darwin man parser
complete -c pstopdf -s o --description 'The name of the output file to create.'
complete -c pstopdf -s i --description 'Reads from stdin rather than a named input file.'
complete -c pstopdf -s l --description 'Specifies that any messages generated during fi… [See Man Page]'
complete -c pstopdf -s p --description 'Generates a simple progress message to stdout a… [See Man Page]'

