# pwd
# Autogenerated from man page /usr/share/man/man1/pwd.1
# using Darwin man parser
complete -c pwd -s L --description 'Display the logical current working directory.'
complete -c pwd -s P --description 'Display the physical current working directory … [See Man Page]'

