# pwd_mkdb
# Autogenerated from man page /usr/share/man/man8/pwd_mkdb.8
# using Darwin man parser
complete -c pwd_mkdb -s c --description 'Check if the password file is in the correct format.'
complete -c pwd_mkdb -s d --description 'Operate in a base directory other than the default of /etc.'
complete -c pwd_mkdb -s p --description 'Create a Version 7 style password file and inst… [See Man Page]'
complete -c pwd_mkdb -s s --description 'Only update the secure version of the database.'
complete -c pwd_mkdb -s u --description 'Only update the record for the specified user.'

