# pydoc
# Autogenerated from man page /usr/share/man/man1/pydoc.1
# using Darwin man parser
complete -c pydoc -s k --description 'Search for a keyword in the synopsis lines of a… [See Man Page]'
complete -c pydoc -s p --description 'Start an HTTP server on the given port on the local machine.'
complete -c pydoc -s g --description 'Pop up a graphical interface for finding and se… [See Man Page]'
complete -c pydoc -s w --description 'Write out the HTML documentation for a module t… [See Man Page]'
complete -c pydoc -l help --description 'Prints out a help message.'

