# python2
# Autogenerated from man page /usr/share/man/man1/python2.7.1
# using Deroffing man parser
complete -c python2 -o OO --description 'Discard docstrings in addition to the -O optimizations.'

