# qtmodernizer
# Autogenerated from man page /usr/share/man/man1/qtmodernizer.1
# using Darwin man parser
complete -c qtmodernizer -s h --description '.'
complete -c qtmodernizer -s p --description 'If -p or --useprores is specified, qtmodernizer… [See Man Page]'
complete -c qtmodernizer -o p4 --description 'If -p4 or --useprores4444 is specified, qtmoder… [See Man Page]'
complete -c qtmodernizer -s r --description 'Normally qtmodernizer will not replace any existing files.'
complete -c qtmodernizer -s v --description 'Normally qtmodernizer only displays important e… [See Man Page]'
complete -c qtmodernizer -s i --description 'Causes qtmodernizer to display information abou… [See Man Page]'

