# quotaon
# Autogenerated from man page /usr/share/man/man8/quotaon.8
# using Darwin man parser
complete -c quotaon -s a --description 'If the a flag is supplied in place of any files… [See Man Page]'
complete -c quotaon -s g --description 'Only group quotas will be enabled/disabled.'
complete -c quotaon -s u --description 'Only user quotas will be enabled/disabled.'
complete -c quotaon -s v --description 'Causes quotaon quotaon and quotaon quotaoff to … [See Man Page]'

