# quotaoff
# Autogenerated from man page /usr/share/man/man8/quotaoff.8
# using Darwin man parser
complete -c quotaoff -s a --description 'If the a flag is supplied in place of any files… [See Man Page]'
complete -c quotaoff -s g --description 'Only group quotas will be enabled/disabled.'
complete -c quotaoff -s u --description 'Only user quotas will be enabled/disabled.'
complete -c quotaoff -s v --description 'Causes quotaoff quotaon and quotaoff quotaoff t… [See Man Page]'

