# quota
# Autogenerated from man page /usr/share/man/man1/quota.1
# using Darwin man parser
complete -c quota -s g --description 'Print group quotas for the group of which the user is a member.'
complete -c quota -s v --description 'quota quota will display quotas on filesystems … [See Man Page]'
complete -c quota -s q --description 'Print a more terse message, containing only inf… [See Man Page]'

