# quotacheck
# Autogenerated from man page /usr/share/man/man8/quotacheck.8
# using Darwin man parser
complete -c quotacheck -s a --description 'If the a flag is supplied in place of any files… [See Man Page]'
complete -c quotacheck -s g --description 'Only group quotas are checked.  The mount option file, . quota.'
complete -c quotacheck -s u --description 'Only user quotas are checked.   The mount option file, . quota.'
complete -c quotacheck -s v --description 'quotacheck quotacheck reports discrepancies bet… [See Man Page]'

