# racoon
# Autogenerated from man page /usr/share/man/man8/racoon.8
# using Darwin man parser
complete -c racoon -s 4 --description '.'
complete -c racoon -s 6 --description 'Specify the default address family for the sockets.'
complete -c racoon -s B --description 'Install SA(s) from the file which is specified in racoon.'
complete -c racoon -s d --description 'Increase the debug level.'
complete -c racoon -s F --description 'Run racoon in the foreground.'
complete -c racoon -s f --description 'Use configfile as the configuration file instea… [See Man Page]'
complete -c racoon -s L --description 'Include file_name:line_number:function_name in all messages.'
complete -c racoon -s l --description 'Use logfile as the logging file instead of syslogd 8.'
complete -c racoon -s v --description 'This flag causes the packet dump be more verbos… [See Man Page]'

