# rcp
# Autogenerated from man page /usr/share/man/man1/rcp.1
# using Darwin man parser
complete -c rcp -s 4 --description 'Use IPv4 addresses only.'
complete -c rcp -s 6 --description 'Use IPv6 addresses only.'
complete -c rcp -s p --description 'Cause rcp to attempt to preserve (duplicate) in… [See Man Page]'
complete -c rcp -s r --description 'If any of the source files are directories, rcp… [See Man Page]'

