# reboot
# Autogenerated from man page /usr/share/man/man8/reboot.8
# using Darwin man parser
complete -c reboot -s l --description 'The halt or reboot is not recorded in the system log.'
complete -c reboot -s n --description 'The file system cache is not flushed.'
complete -c reboot -s q --description 'The system is halted or restarted quickly and u… [See Man Page]'
complete -c reboot -s u --description 'The system is halted up until the point of remo… [See Man Page]'

