# repquota
# Autogenerated from man page /usr/share/man/man8/repquota.8
# using Darwin man parser
complete -c repquota -s a --description 'Print the quotas of all the filesystems configu… [See Man Page]'
complete -c repquota -s g --description 'Print only group quotas (the default is to prin… [See Man Page]'
complete -c repquota -s u --description 'Print only user quotas (the default is to print… [See Man Page]'
complete -c repquota -s v --description 'Print a header line before printing each filesystem quotas.'

