# revnetgroup
# Autogenerated from man page /usr/share/man/man8/revnetgroup.8
# using Darwin man parser
complete -c revnetgroup -s u --description 'Generate netgroup.'
complete -c revnetgroup -s h --description 'Generate netgroup.'

