# rlogind
# Autogenerated from man page /usr/share/man/man8/rlogind.8
# using Darwin man parser
complete -c rlogind -s a --description 'Ask hostname for verification.'
complete -c rlogind -s l --description 'Prevent any authentication based on the user\'s .'
complete -c rlogind -s n --description 'Disable keep-alive messages.'

