# rlogin
# Autogenerated from man page /usr/share/man/man1/rlogin.1
# using Darwin man parser
complete -c rlogin -s 4 --description 'Use IPv4 addresses only.'
complete -c rlogin -s 6 --description 'Use IPv6 addresses only.'
complete -c rlogin -s 8 --description 'Allow an eight-bit input data path at all times… [See Man Page]'
complete -c rlogin -s D --description 'Set the TCP_NODELAY socket option which can imp… [See Man Page]'
complete -c rlogin -s E --description 'Stop any character from being recognized as an … [See Man Page]'
complete -c rlogin -s d --description 'Turn on socket debugging (see setsockopt 2 ) on… [See Man Page]'
complete -c rlogin -s e --description 'Allow user specification of the escape characte… [See Man Page]'
complete -c rlogin -s i --description 'Allow the caller to specify a different local n… [See Man Page]'
complete -c rlogin -s l --description 'Specify a different username for the remote login.'

