# rm
# Autogenerated from man page /usr/share/man/man1/rm.1
# using Darwin man parser
complete -c rm -s d --description 'Attempt to remove directories as well as other types of files.'
complete -c rm -s f --description 'Attempt to remove the files without prompting f… [See Man Page]'
complete -c rm -s i --description 'Request confirmation before attempting to remov… [See Man Page]'
complete -c rm -s P --description 'Overwrite regular files before deleting them.'
complete -c rm -s R --description 'Attempt to remove the file hierarchy rooted in … [See Man Page]'
complete -c rm -s r --description 'Equivalent to R.'
complete -c rm -s v --description 'Be verbose when deleting files, showing them as… [See Man Page]'
complete -c rm -s W --description 'Attempt to undelete the named files.'

