# rmid
# Autogenerated from man page /usr/share/man/man1/rmid.1
# using Deroffing man parser
complete -c rmid -s C --description 'Specifies an option that is passed as a command… [See Man Page]'
complete -c rmid -s J --description 'Specifies an option that is passed to the java … [See Man Page]'
complete -c rmid -o 'J-Dsun.rmi.activation.execPolicy' --description 'Specifies the policy that  rmid employs to chec… [See Man Page]'
complete -c rmid -o log --description 'Specifies the name of the directory the activat… [See Man Page]'
complete -c rmid -o port --description 'Specifies the port  rmid \'s registry uses.'
complete -c rmid -s D --description '.'
complete -c rmid -o stop --description 'Stops the current invocation of rmid ,  for a p… [See Man Page]'

