# rmiregistry
# Autogenerated from man page /usr/share/man/man1/rmiregistry.1
# using Deroffing man parser
complete -c rmiregistry -s J --description 'Used in conjunction with any java option, this … [See Man Page]'

