# rotatelogs
# Autogenerated from man page /usr/share/man/man8/rotatelogs.8
# using Type1
complete -c rotatelogs -s l --description 'Causes the use of local time rather than GMT as… [See Man Page]'
complete -c rotatelogs -s L --description 'Causes a hard link to be made from the current … [See Man Page]'
complete -c rotatelogs -s p --description 'If given, rotatelogs will execute the specified… [See Man Page]'
complete -c rotatelogs -s f --description 'Causes the logfile to be opened immediately, as… [See Man Page]'
complete -c rotatelogs -s t --description 'Causes the logfile to be truncated instead of rotated.'
complete -c rotatelogs -s v --description 'Produce verbose output on STDERR.'
complete -c rotatelogs -s e --description 'Echo logs through to stdout.'
complete -c rotatelogs -s c --description 'Create log file for each interval, even if empty.'
complete -c rotatelogs -s n --description 'Use a circular list of filenames without timestamps.'

