# rpc
# Autogenerated from man page /usr/share/man/man8/rpc.statd.8
# using Darwin man parser
complete -c rpc -s n --description 'Send SM_NOTIFY messages to notify any hosts of a restart.'
complete -c rpc -s l --description 'List each host (and its status) in the status file.'
complete -c rpc -s L --description 'List each host (and its status) in the status f… [See Man Page]'
complete -c rpc -s N --description 'Clear the "needs notification" status for hostn… [See Man Page]'

