# rpcbind
# Autogenerated from man page /usr/share/man/man8/rpcbind.8
# using Darwin man parser
complete -c rpcbind -s d --description 'causes rpcbind errors and debugging information… [See Man Page]'
complete -c rpcbind -s v --description 'Enable verbose logging of access control checks.'
complete -c rpcbind -s h --description 'Specify specific IP addresses to bind to for UDP requests.'

