# rpcinfo
# Autogenerated from man page /usr/share/man/man8/rpcinfo.8
# using Darwin man parser
complete -c rpcinfo -s T --description 'Specify the netid to use.'
complete -c rpcinfo -s h --description 'Print out the synopsis of this program.'

