# rpcsvchost
# Autogenerated from man page /usr/share/man/man8/rpcsvchost.8
# using Darwin man parser
complete -c rpcsvchost -o debug --description 'rpcsvchost will log debug information and may p… [See Man Page]'
complete -c rpcsvchost -o endpoints --description 'This argument specifies additional endpoints th… [See Man Page]'
complete -c rpcsvchost -o help --description 'Prints a usage message and exits.'
complete -c rpcsvchost -o launchd --description 'Normally, rpcsvchost attempts to bind all the w… [See Man Page]'
complete -c rpcsvchost -o sandbox --description 'When this option is specified, the modules load… [See Man Page]'
complete -c rpcsvchost -o register --description 'When this option is specified, rpcsvchost attem… [See Man Page]'
complete -c rpcsvchost -o stdout --description 'Causes rpcsvchost to print log messages to stan… [See Man Page]'
complete -c rpcsvchost -o wait-for-debugger --description 'Causes rpcsvchost to wait for a debugger to att… [See Man Page]'

