# rs
# Autogenerated from man page /usr/share/man/man1/rs.1
# using Darwin man parser
complete -c rs -s c --description 'Input columns are delimited by the single character x.'
complete -c rs -s s --description 'Like c, but maximal strings of x are delimiters.'
complete -c rs -s C --description 'Output columns are delimited by the single character x.'
complete -c rs -s S --description 'Like C, but padded strings of x are delimiters.'
complete -c rs -s t --description 'Fill in the rows of the output array using the … [See Man Page]'
complete -c rs -s T --description 'Print the pure transpose of the input, ignoring… [See Man Page]'
complete -c rs -s k --description 'Ignore the first N lines of input.'
complete -c rs -s K --description 'Like k, but print the ignored lines.'
complete -c rs -s g --description 'The gutter width (inter-column space), normally… [See Man Page]'
complete -c rs -s G --description 'The gutter width has N percent of the maximum c… [See Man Page]'
complete -c rs -s e --description 'Consider each line of input as an array entry.'
complete -c rs -s n --description 'On lines having fewer entries than the first li… [See Man Page]'
complete -c rs -s y --description 'If there are too few entries to make up the out… [See Man Page]'
complete -c rs -s h --description 'Print the shape of the input array and do nothing else.'
complete -c rs -s H --description 'Like h, but also print the length of each line.'
complete -c rs -s j --description 'Right adjust entries within columns.'
complete -c rs -s w --description 'The width of the display, normally 80, is taken… [See Man Page]'
complete -c rs -s m --description 'Do not trim excess delimiters from the ends of … [See Man Page]'
complete -c rs -s z --description 'Adapt column widths to fit the largest entries … [See Man Page]'

