# rsh
# Autogenerated from man page /usr/share/man/man1/rsh.1
# using Darwin man parser
complete -c rsh -s 4 --description 'Use IPv4 addresses only.'
complete -c rsh -s 6 --description 'Use IPv6 addresses only.'
complete -c rsh -s d --description 'Turn on socket debugging (using setsockopt 2 ) … [See Man Page]'
complete -c rsh -s l --description 'Allow the remote username to be specified.'
complete -c rsh -s n --description 'Redirect input from the special device /dev/nul… [See Man Page]'
complete -c rsh -s t --description 'Allow a timeout to be specified (in seconds).'

