# rshd
# Autogenerated from man page /usr/share/man/man8/rshd.8
# using Darwin man parser
complete -c rshd -s a --description 'This flag is ignored, and is present for compat… [See Man Page]'
complete -c rshd -s D --description 'Sets the TCP_NODELAY socket option, which impro… [See Man Page]'
complete -c rshd -s L --description 'Causes all successful accesses to be logged to … [See Man Page]'
complete -c rshd -s l --description 'Do not use the user\'s .'
complete -c rshd -s n --description 'Turn off transport level keepalive messages.'

