# rtsol
# Autogenerated from man page /usr/share/man/man8/rtsol.8
# using Darwin man parser
complete -c rtsol -s a --description 'Autoprobe outgoing interface.'
complete -c rtsol -s d --description 'Enable debugging.'
complete -c rtsol -s D --description 'Enable more debugging including the printing of… [See Man Page]'
complete -c rtsol -s f --description 'f prevents rtsol from becoming a daemon (foreground mode).'
complete -c rtsol -s m --description 'Enable mobility support.'
complete -c rtsol -s 1 --description 'Perform only one probe.'

