# rtsold
# Autogenerated from man page /usr/share/man/man8/rtsold.8
# using Darwin man parser
complete -c rtsold -s a --description 'Autoprobe outgoing interface.'
complete -c rtsold -s d --description 'Enable debugging.'
complete -c rtsold -s D --description 'Enable more debugging including the printing of… [See Man Page]'
complete -c rtsold -s f --description 'f prevents rtsold from becoming a daemon (foreground mode).'
complete -c rtsold -s m --description 'Enable mobility support.'
complete -c rtsold -s 1 --description 'Perform only one probe.'

