# ruptime
# Autogenerated from man page /usr/share/man/man1/ruptime.1
# using Darwin man parser
complete -c ruptime -s a --description 'Include all users.'
complete -c ruptime -s l --description 'Sort by load average.'
complete -c ruptime -s r --description 'Reverse the sort order.'
complete -c ruptime -s t --description 'Sort by uptime.'
complete -c ruptime -s u --description 'Sort by number of users.'

