# rwhod
# Autogenerated from man page /usr/share/man/man8/rwhod.8
# using Darwin man parser
complete -c rwhod -s i --description 'Enable insecure mode, which causes rwhod to ign… [See Man Page]'
complete -c rwhod -s p --description 'Ignore all POINTOPOINT interfaces.'
complete -c rwhod -s l --description 'Enable listen mode, which causes rwhod to not b… [See Man Page]'
complete -c rwhod -s m --description 'Cause rwhod to use IP multicast (instead of bro… [See Man Page]'

