# rwsnoop
# Autogenerated from man page /usr/share/man/man1/rwsnoop.1m
# using Deroffing man parser
complete -c rwsnoop -s j --description 'print project ID.'
complete -c rwsnoop -s P --description 'print parent process ID.'
complete -c rwsnoop -s t --description 'print timestamp, us.'
complete -c rwsnoop -s v --description 'print time, string.'
complete -c rwsnoop -s Z --description 'print zone ID.'
complete -c rwsnoop -s n --description 'process name to track.'
complete -c rwsnoop -s p --description 'PID to track.'

