# sandbox-exec
# Autogenerated from man page /usr/share/man/man1/sandbox-exec.1
# using Darwin man parser
complete -c sandbox-exec -s f --description 'Read the profile from the file named profile-file.'
complete -c sandbox-exec -s n --description 'Use the pre-defined profile profile-name.'
complete -c sandbox-exec -s p --description 'Specify the profile to be used on the command line.'
complete -c sandbox-exec -s D --description 'Set the profile parameter key to value.'

