# sar
# Autogenerated from man page /usr/share/man/man1/sar.1
# using Darwin man parser
complete -c sar -s d --description 'Report disk activity.'
complete -c sar -s g --description 'Report page-out activity.'
complete -c sar -s p --description 'Report page-in and page fault activity Pp -tag … [See Man Page]'
complete -c sar -s n --description 'Report network activity with modes DEV, EDEV, or PPP.'
complete -c sar -s u --description 'Report CPU activity (default) Pp %usr, %sys, an… [See Man Page]'

