# sc_auth
# Autogenerated from man page /usr/share/man/man8/sc_auth.8
# using Darwin man parser
complete -c sc_auth -s u --description 'Specifies the user whose account is to be modified.'
complete -c sc_auth -s d --description 'Specifies the directory domain containing the user account.'
complete -c sc_auth -s k --description 'Specifies a public key by its name.'
complete -c sc_auth -s h --description 'Specifies a public key by its hash.'
complete -c sc_auth -s v --description 'Verbose mode \\" Ends the list NOTES sc_auth is a shell script.'

