# sc_usage
# Autogenerated from man page /usr/share/man/man1/sc_usage.1
# using Darwin man parser
complete -c sc_usage -s c --description 'When the c option is specified, it expects a pa… [See Man Page]'
complete -c sc_usage -s e --description 'Specifying the e option generates output that i… [See Man Page]'
complete -c sc_usage -s l --description 'The l option causes sc_usage sc_usage to turn o… [See Man Page]'
complete -c sc_usage -s s --description 'By default, sc_usage sc_usage updates its outpu… [See Man Page]'

