# screencapture
# Autogenerated from man page /usr/share/man/man1/screencapture.1
# using Darwin man parser
complete -c screencapture -s c --description 'Force screen capture to go to the clipboard.'
complete -c screencapture -s C --description 'Capture the cursor as well as the screen.'
complete -c screencapture -s i --description 'Capture screen interactively, by selection or window.'
complete -c screencapture -s m --description 'Only capture the main monitor, undefined if -i is set.'
complete -c screencapture -s M --description 'Open the taken picture in a new Mail message.'
complete -c screencapture -s o --description 'In window capture mode, do not capture the shad… [See Man Page]'
complete -c screencapture -s P --description 'Open the taken picture in a Preview window.'
complete -c screencapture -s s --description 'Only allow mouse selection mode.'
complete -c screencapture -s S --description 'In window capture mode, capture the screen inst… [See Man Page]'
complete -c screencapture -s t --description '<format> Image format to create, default is png… [See Man Page]'
complete -c screencapture -s T --description '<seconds> Take the picture after a delay of <se… [See Man Page]'
complete -c screencapture -s w --description 'Only allow window selection mode.'
complete -c screencapture -s W --description 'Start interaction in window selection mode.'
complete -c screencapture -s x --description 'Do not play sounds.'
complete -c screencapture -s a --description 'Do not capture attached windows.'
complete -c screencapture -s r --description 'Do not add screen dpi meta data to captured file.'

