# script
# Autogenerated from man page /usr/share/man/man1/script.1
# using Darwin man parser
complete -c script -s a --description 'Append the output to file or typescript, retain… [See Man Page]'
complete -c script -s k --description 'Log keys sent to program as well as output.'
complete -c script -s q --description 'Run in quiet mode, omit the start and stop status messages.'
complete -c script -s t --description 'Specify time interval between flushing script output file.'

