# scselect
# Autogenerated from man page /usr/share/man/man8/scselect.8
# using Darwin man parser
complete -c scselect -s n --description 'Delay changing the system\'s location until the … [See Man Page]'

