# scutil
# Autogenerated from man page /usr/share/man/man8/scutil.8
# using Darwin man parser
complete -c scutil -s r --description 'Check the network reachability of the specified… [See Man Page]'
complete -c scutil -s w --description 'Check if the specified key exists in the dynami… [See Man Page]'
complete -c scutil -l get --description 'Retrieves the specified preference.'
complete -c scutil -l set --description 'Updates the specified preference with the new value.'
complete -c scutil -l dns --description 'Reports the current DNS configuration.'
complete -c scutil -l proxy --description 'Reports the current proxy configuration.'
complete -c scutil -l nc --description 'Provides a set of commands for monitoring and i… [See Man Page]'

