# sed
# Autogenerated from man page /usr/share/man/man1/sed.1
# using Darwin man parser
complete -c sed -s E --description 'Interpret regular expressions as extended (mode… [See Man Page]'
complete -c sed -s a --description 'The files listed as parameters for the w functi… [See Man Page]'
complete -c sed -s e --description 'Append the editing commands specified by the co… [See Man Page]'
complete -c sed -s f --description 'Append the editing commands found in the file c… [See Man Page]'
complete -c sed -s i --description 'Edit files in-place, saving backups with the sp… [See Man Page]'
complete -c sed -s l --description 'Make output line buffered.'
complete -c sed -s n --description 'By default, each line of input is echoed to the… [See Man Page]'

