# seq
# Autogenerated from man page /usr/share/man/man1/seq.1
# using Darwin man parser
complete -c seq -s f --description 'Use a printf 3 style format to print each number.'
complete -c seq -s s --description 'Use string to separate numbers.'
complete -c seq -s t --description 'Use string to terminate sequence of numbers.'
complete -c seq -s w --description 'Equalize the widths of all numbers by padding w… [See Man Page]'

