# servertool
# Autogenerated from man page /usr/share/man/man1/servertool.1
# using Deroffing man parser
complete -c servertool -o ORBInitialHost --description 'Specifies the host machine on which the name se… [See Man Page]'
complete -c servertool -s J --description 'Pass  option  to the Java virtual machine, wher… [See Man Page]'
complete -c servertool -o server --description '.'
complete -c servertool -o classpath --description '[ .'
complete -c servertool -o applicationName --description '.'
complete -c servertool -o args --description '.'
complete -c servertool -o vmargs --description '] Register a new server with the Object Request… [See Man Page]'
complete -c servertool -o serverid --description '| .'
complete -c servertool -o endpointType --description '] Locate the endpoints (ports) of a specific ty… [See Man Page]'
complete -c servertool -o orbid --description '] Locate all the endpoints (ports) registered b… [See Man Page]'

