# setquota
# Autogenerated from man page /usr/share/man/man1/setquota.1
# using Darwin man parser
complete -c setquota -s a --description 'sets home directory quota for users defined in … [See Man Page]'
complete -c setquota -s l --description 'sets home directory quota for users defined in … [See Man Page]'
complete -c setquota -s n --description 'sets home directory quota for users defined in … [See Man Page]'
complete -c setquota -s u --description 'sets home directory quota for a specific user d… [See Man Page]'

