# sftp-server
# Autogenerated from man page /usr/share/man/man8/sftp-server.8
# using Darwin man parser
complete -c sftp-server -s d --description 'specifies an alternate starting directory for users.'
complete -c sftp-server -s e --description 'Causes sftp-server to print logging information… [See Man Page]'
complete -c sftp-server -s f --description 'Specifies the facility code that is used when l… [See Man Page]'
complete -c sftp-server -s h --description 'Displays sftp-server usage information.'
complete -c sftp-server -s l --description 'Specifies which messages will be logged by sftp-server.'
complete -c sftp-server -s R --description 'Places this instance of sftp-server into a read-only mode.'
complete -c sftp-server -s u --description 'Sets an explicit umask 2 to be applied to newly… [See Man Page]'

