# sharing
# Autogenerated from man page /usr/share/man/man1/sharing.1
# using Darwin man parser
complete -c sharing -s a --description 'add a new share point for the directory specified by <path>.'
complete -c sharing -s e --description 'edit the share point record specified by <share point name>.'
complete -c sharing -s r --description 'delete the share point record specified by <share point name>.'
complete -c sharing -s l --description 'list all existing share point records.'
complete -c sharing -s A --description 'use customized name <afp name> when using share point with afp.'
complete -c sharing -s F --description 'use customized name <ftp name> when using share point with ftp.'
complete -c sharing -s S --description 'use customized name <smb name> when using share… [See Man Page]'
complete -c sharing -s s --description 'Use this option to enable and disable sharing v… [See Man Page]'
complete -c sharing -s g --description 'Use this option to enable and disable guest acc… [See Man Page]'
complete -c sharing -s i --description 'Use this option to enable and disable the "inhe… [See Man Page]'
complete -c sharing -s n --description 'Specify a <customized record name> to be used a… [See Man Page]'

