# showmount
# Autogenerated from man page /usr/share/man/man8/showmount.8
# using Darwin man parser
complete -c showmount -s A --description 'Search for NFS servers advertised via Bonjour.'
complete -c showmount -s a --description 'List all mount points in the form: host : Ns Ar dirpath.'
complete -c showmount -s d --description 'List directory paths of mount points instead of hosts.'
complete -c showmount -s e --description 'Show the host Ns \'s exports list.'
complete -c showmount -s 3 --description 'Use mount protocol Version 3, compatible with NFS Version 3.'
complete -c showmount -s 6 --description 'Use only IPv6 addresses to contact servers.'

