# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8
# using Darwin man parser
complete -c shutdown -s h --description 'The system is halted at the specified time.'
complete -c shutdown -s k --description 'Kick everybody off.'
complete -c shutdown -s n --description 'If the o is specified, prevent the file system … [See Man Page]'
complete -c shutdown -s o --description 'If h or r is specified, shutdown shutdown will … [See Man Page]'
complete -c shutdown -s r --description 'The system is rebooted at the specified time.'
complete -c shutdown -s s --description 'The system is put to sleep at the specified time.'
complete -c shutdown -s u --description 'The system is halted up until the point of remo… [See Man Page]'

