# slaptest
# Autogenerated from man page /usr/share/man/man8/slaptest.8
# using Deroffing man parser
complete -c slaptest -s d --description 'enable debugging messages as defined by the spe… [See Man Page]'
complete -c slaptest -s f --description 'specify an alternative  slapd. conf (5) file.'
complete -c slaptest -s F --description 'specify a config directory.'
complete -c slaptest -s n --description 'Just open and test the dbnum-th database listed… [See Man Page]'
complete -c slaptest -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slaptest -s Q --description 'Be extremely quiet: only the exit code indicate… [See Man Page]'
complete -c slaptest -s u --description 'enable dry-run mode (i. e.'
complete -c slaptest -s v --description 'enable verbose mode.  EXAMPLES To check a  slapd.'

