# slapadd
# Autogenerated from man page /usr/share/man/man8/slapadd.8
# using Deroffing man parser
complete -c slapadd -s b --description 'Use the specified suffix to determine which dat… [See Man Page]'
complete -c slapadd -s c --description 'enable continue (ignore errors) mode.'
complete -c slapadd -s d --description 'enable debugging messages as defined by the spe… [See Man Page]'
complete -c slapadd -s f --description 'specify an alternative  slapd. conf (5) file.'
complete -c slapadd -s F --description 'specify a config directory.'
complete -c slapadd -s g --description 'disable subordinate gluing.'
complete -c slapadd -s j --description 'Jump to the specified line number in the LDIF f… [See Man Page]'
complete -c slapadd -s l --description 'Read LDIF from the specified file instead of standard input.'
complete -c slapadd -s n --description 'Add entries to the dbnum-th database listed in … [See Man Page]'
complete -c slapadd -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slapadd -s q --description 'enable quick (fewer integrity checks) mode.'
complete -c slapadd -s s --description 'disable schema checking.'
complete -c slapadd -s S --description 'Server ID to use in generated entryCSN.'
complete -c slapadd -s u --description 'enable dry-run (don\'t write to backend) mode.'
complete -c slapadd -s v --description 'enable verbose mode.'
complete -c slapadd -s w --description 'write syncrepl context information.'

