# slapdn
# Autogenerated from man page /usr/share/man/man8/slapdn.8
# using Deroffing man parser
complete -c slapdn -s d --description 'enable debugging messages as defined by the spe… [See Man Page]'
complete -c slapdn -s f --description 'specify an alternative  slapd. conf (5) file.'
complete -c slapdn -s F --description 'specify a config directory.'
complete -c slapdn -s N --description 'only output a normalized form of the DN, suitab… [See Man Page]'
complete -c slapdn -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slapdn -s P --description 'only output a prettified form of the DN, suitab… [See Man Page]'
complete -c slapdn -s v --description 'enable verbose mode.'

