# slapauth
# Autogenerated from man page /usr/share/man/man8/slapauth.8
# using Deroffing man parser
complete -c slapauth -s d --description 'enable debugging messages as defined by the spe… [See Man Page]'
complete -c slapauth -s f --description 'specify an alternative  slapd. conf (5) file.'
complete -c slapauth -s F --description 'specify a config directory.'
complete -c slapauth -s M --description 'specify a mechanism.'
complete -c slapauth -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slapauth -s R --description 'specify a realm.'
complete -c slapauth -s U --description 'specify an ID to be used as   authcID throughou… [See Man Page]'
complete -c slapauth -s X --description 'specify an ID to be used as   authzID throughou… [See Man Page]'
complete -c slapauth -s v --description 'enable verbose mode.'

