# slapschema
# Autogenerated from man page /usr/share/man/man8/slapschema.8
# using Deroffing man parser
complete -c slapschema -s a --description 'Only check entries matching the asserted filter.'
complete -c slapschema -s b --description 'Use the specified suffix to determine which database to check.'
complete -c slapschema -s c --description 'Enable continue (ignore errors) mode.'
complete -c slapschema -s d --description 'Enable debugging messages as defined by the spe… [See Man Page]'
complete -c slapschema -s f --description 'Specify an alternative  slapd. conf (5) file.'
complete -c slapschema -s F --description 'specify a config directory.'
complete -c slapschema -s g --description 'disable subordinate gluing.'
complete -c slapschema -s H --description 'use dn, scope and filter from URI to only handl… [See Man Page]'
complete -c slapschema -s l --description 'Write errors to specified file instead of standard output.'
complete -c slapschema -s n --description 'Check the dbnum-th database listed in the configuration file.'
complete -c slapschema -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slapschema -s s --description 'Only check entries in the subtree specified by this DN.'
complete -c slapschema -s v --description 'Enable verbose mode.'

