# slapd
# Autogenerated from man page /usr/share/man/man8/slapd.8
# using Deroffing man parser
complete -c slapd -s 4 --description 'Listen on IPv4 addresses only.'
complete -c slapd -s 6 --description 'Listen on IPv6 addresses only.'
complete -c slapd -s T --description 'Run in Tool mode.'
complete -c slapd -s d --description 'Turn on debugging as defined by R debug-level .'
complete -c slapd -s s --description 'This option tells  slapd at what debug-level de… [See Man Page]'
complete -c slapd -s n --description 'Specifies the service name for logging and other purposes.'
complete -c slapd -s l --description 'Selects the local user of the  syslog (8) facility.'
complete -c slapd -s f --description 'Specifies the slapd configuration file.'
complete -c slapd -s F --description 'Specifies the slapd configuration directory.'
complete -c slapd -s h --description 'slapd will by default serve  ldap:/// (LDAP ove… [See Man Page]'
complete -c slapd -s r --description 'Specifies a directory to become the root directory.'
complete -c slapd -s u --description 'slapd will run slapd with the specified user na… [See Man Page]'
complete -c slapd -s g --description 'slapd will run with the specified group name or id.'
complete -c slapd -s c --description 'This option provides a cookie for the syncrepl … [See Man Page]'
complete -c slapd -s o --description 'This option provides a generic means to specify… [See Man Page]'

