# slapcat
# Autogenerated from man page /usr/share/man/man8/slapcat.8
# using Deroffing man parser
complete -c slapcat -s a --description 'Only dump entries matching the asserted filter.'
complete -c slapcat -s b --description 'Use the specified suffix to determine which dat… [See Man Page]'
complete -c slapcat -s c --description 'Enable continue (ignore errors) mode.'
complete -c slapcat -s d --description 'Enable debugging messages as defined by the spe… [See Man Page]'
complete -c slapcat -s f --description 'Specify an alternative  slapd. conf (5) file.'
complete -c slapcat -s F --description 'specify a config directory.'
complete -c slapcat -s g --description 'disable subordinate gluing.'
complete -c slapcat -s H --description 'use dn, scope and filter from URI to only handl… [See Man Page]'
complete -c slapcat -s l --description 'Write LDIF to specified file instead of standard output.'
complete -c slapcat -s n --description 'Generate output for the dbnum-th database liste… [See Man Page]'
complete -c slapcat -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slapcat -s s --description 'Only dump entries in the subtree specified by this DN.'
complete -c slapcat -s v --description 'Enable verbose mode.'

