# slapindex
# Autogenerated from man page /usr/share/man/man8/slapindex.8
# using Deroffing man parser
complete -c slapindex -s b --description 'Use the specified suffix to determine which dat… [See Man Page]'
complete -c slapindex -s c --description 'enable continue (ignore errors) mode.'
complete -c slapindex -s d --description 'enable debugging messages as defined by the spe… [See Man Page]'
complete -c slapindex -s f --description 'specify an alternative  slapd. conf (5) file.'
complete -c slapindex -s F --description 'specify a config directory.'
complete -c slapindex -s g --description 'disable subordinate gluing.'
complete -c slapindex -s n --description 'Generate output for the dbnum-th database liste… [See Man Page]'
complete -c slapindex -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slapindex -s q --description 'enable quick (fewer integrity checks) mode.'
complete -c slapindex -s t --description 'enable truncate mode.'
complete -c slapindex -s u --description 'in slapd (8)), or change file ownership before … [See Man Page]'
complete -c slapindex -s v --description 'enable verbose mode.'

