# slappasswd
# Autogenerated from man page /usr/share/man/man8/slappasswd.8
# using Deroffing man parser
complete -c slappasswd -s v --description 'enable verbose mode.'
complete -c slappasswd -s u --description 'Generate RFC 2307 userPassword values (the default).'
complete -c slappasswd -s s --description 'The secret to hash.'
complete -c slappasswd -s g --description 'Generate the secret.'
complete -c slappasswd -s T --description 'Hash the contents of the file.'
complete -c slappasswd -s h --description 'If -h is specified, one of the following RFC 23… [See Man Page]'
complete -c slappasswd -s c --description 'Specify the format of the salt passed to  crypt… [See Man Page]'
complete -c slappasswd -s n --description 'Omit the trailing newline; useful to pipe the c… [See Man Page]'

