# slapacl
# Autogenerated from man page /usr/share/man/man8/slapacl.8
# using Deroffing man parser
complete -c slapacl -s b --description 'specify the   DN  which access is requested to;… [See Man Page]'
complete -c slapacl -s d --description 'enable debugging messages as defined by the spe… [See Man Page]'
complete -c slapacl -s D --description 'specify a DN to be used as identity through the… [See Man Page]'
complete -c slapacl -s f --description 'specify an alternative  slapd. conf (5) file.'
complete -c slapacl -s F --description 'specify a config directory.'
complete -c slapacl -s o --description 'Specify an  option with a(n optional) R value .'
complete -c slapacl -s u --description 'do not fetch the entry from the database.'
complete -c slapacl -s U --description 'specify an ID to be mapped to a   DN  as by mea… [See Man Page]'
complete -c slapacl -s v --description 'enable verbose mode.'
complete -c slapacl -s X --description 'specify an authorization ID to be mapped to a D… [See Man Page]'

