# smbd
# Autogenerated from man page /usr/share/man/man8/smbd.8
# using Darwin man parser
complete -c smbd -o debug --description 'The service will log extensive debug informatio… [See Man Page]'
complete -c smbd -o help --description 'Prints a usage message and exits.'
complete -c smbd -o ports --description 'The service will listen on each of the TCP port… [See Man Page]'
complete -c smbd -o stdout --description 'Causes smbd to print log messages to standard o… [See Man Page]'
complete -c smbd -o no-symlinks --description 'In normal operation, smbd will respond to clien… [See Man Page]'

