# smcDiagnose
# Autogenerated from man page /usr/share/man/man1/smcDiagnose.1
# using Darwin man parser
complete -c smcDiagnose -s a --description 'Description of -a flag.'
complete -c smcDiagnose -s b --description 'Description of -b flag \\" Ends the list Pp .'

