# smtpd
# Autogenerated from man page /usr/share/man/man8/smtpd.8
# using Deroffing man parser
complete -c smtpd -o bs --description '$mail_owner privileges, it receives mail even w… [See Man Page]'
complete -c smtpd -s V --description 'and later.'

