# snmpusm
# Autogenerated from man page /usr/share/man/man1/snmpusm.1
# using Deroffing man parser
complete -c snmpusm -o CE --description 'Set usmUserEngineID to be used as part of the i… [See Man Page]'
complete -c snmpusm -o Cp --description 'Set the usmUserPublic value of the (new) user t… [See Man Page]'
complete -c snmpusm -o Ca --description 'Change the authentication key.'
complete -c snmpusm -o Cx --description 'Change the privacy key.'
complete -c snmpusm -o Ck --description 'Allows to use localized key (must start with 0x… [See Man Page]'

