# snmptrap
# Autogenerated from man page /usr/share/man/man1/snmptrap.1
# using Deroffing man parser
complete -c snmptrap -o Ci --description 'is added to the command line flags of snmptrap,… [See Man Page]'

