# snmpnetstat
# Autogenerated from man page /usr/share/man/man1/snmpnetstat.1
# using Deroffing man parser
complete -c snmpnetstat -o Ca --description 'With the default display, show the state of all… [See Man Page]'
complete -c snmpnetstat -o Ci --description 'Show the state of all of the network interfaces.'
complete -c snmpnetstat -o Co --description 'Show an abbreviated interface status, giving oc… [See Man Page]'
complete -c snmpnetstat -o CI --description 'Show information only about this interface; use… [See Man Page]'
complete -c snmpnetstat -o Cn --description 'Show network addresses as numbers (normally  sn… [See Man Page]'
complete -c snmpnetstat -o Cp --description 'Show statistics about  protocol, which is eithe… [See Man Page]'
complete -c snmpnetstat -o Cs --description 'Show per-protocol statistics.   When used with the.'
complete -c snmpnetstat -o Cr --description 'option, show routing statistics instead.'
complete -c snmpnetstat -o CR --description 'For GETBULK requests, repeaters specifies the m… [See Man Page]'

