# snmpwalk
# Autogenerated from man page /usr/share/man/man1/snmpwalk.1
# using Deroffing man parser
complete -c snmpwalk -o Cc --description 'Do not check whether the returned OIDs are increasing.'
complete -c snmpwalk -o CE --description 'End the walk at the specified OID, rather than … [See Man Page]'
complete -c snmpwalk -o Ci --description 'Include the given OID in the search range.'
complete -c snmpwalk -o CI --description 'In fact, the given OID will be retrieved automa… [See Man Page]'
complete -c snmpwalk -o Cp --description 'Upon completion of the walk, print the number o… [See Man Page]'
complete -c snmpwalk -o Ct --description 'Upon completion of the walk, print the total wa… [See Man Page]'

