# snmpdf
# Autogenerated from man page /usr/share/man/man1/snmpdf.1
# using Deroffing man parser
complete -c snmpdf -o Cu --description 'Forces the command to use dskTable in mib UCD-S… [See Man Page]'

