# snmpstatus
# Autogenerated from man page /usr/share/man/man1/snmpstatus.1
# using Deroffing man parser
complete -c snmpstatus -o Cf --description 'option is given, see below), but this variable … [See Man Page]'

