# snmptranslate
# Autogenerated from man page /usr/share/man/man1/snmptranslate.1
# using Deroffing man parser
complete -c snmptranslate -o 'D[TOKEN[' --description 'Turn on debugging output for the given R "TOKEN" "(s).'
complete -c snmptranslate -s h --description 'Display a brief usage message and then exit.'
complete -c snmptranslate -s m --description 'Specifies a colon separated list of MIB modules… [See Man Page]'
complete -c snmptranslate -s M --description 'Specifies a colon separated list of directories… [See Man Page]'
complete -c snmptranslate -s T --description 'Provides control over the translation of the OID values.'
complete -c snmptranslate -o Td --description 'Print full details of the specified OID.'
complete -c snmptranslate -o Tp --description 'Print a graphical tree, rooted at the specified OID.'
complete -c snmptranslate -o Ta --description 'Dump the loaded MIB in a trivial form.'
complete -c snmptranslate -o Tl --description 'Dump a labeled form of all objects.'
complete -c snmptranslate -o To --description 'Dump a numeric form of all objects.'
complete -c snmptranslate -o Ts --description 'Dump a symbolic form of all objects.'
complete -c snmptranslate -o Tt --description 'Dump a tree form of the loaded MIBs (mostly use… [See Man Page]'
complete -c snmptranslate -o Tz --description 'Dump a numeric and labeled form of all objects … [See Man Page]'
complete -c snmptranslate -s V --description 'Display version information for the application and then exit.'
complete -c snmptranslate -s w --description 'Specifies the width of.'

