# snutil
# Autogenerated from man page /usr/share/man/man1/snutil.1
# using Darwin man parser
complete -c snutil -s a --description 'Description of -a flag.'
complete -c snutil -s b --description 'Description of -b flag \\" Ends the list Pp .'

