# soelim
# Autogenerated from man page /usr/share/man/man1/soelim.1
# using Deroffing man parser
complete -c soelim -s C --description 'Recognize  .'
complete -c soelim -s I --description 'This option may be used to specify a directory … [See Man Page]'
complete -c soelim -s r --description 'Do not add .'
complete -c soelim -s t --description 'Don\'t emit .'
complete -c soelim -s s --description 'option of groff .'
complete -c soelim -s v --description 'Print the version number.'

