# sort
# Autogenerated from man page /usr/share/man/man1/sort.1
# using Deroffing man parser
complete -c sort -s b -l ignore-leading-blanks --description 'ignore leading blanks.'
complete -c sort -s d -l dictionary-order --description 'consider only blanks and alphanumeric characters.'
complete -c sort -s f -l ignore-case --description 'fold lower case to upper case characters.'
complete -c sort -s g -l general-numeric-sort --description 'compare according to general numerical value.'
complete -c sort -s i -l ignore-nonprinting --description 'consider only printable characters.'
complete -c sort -s M -l month-sort --description 'compare (unknown) < `JAN\' < .  < `DEC\'.'
complete -c sort -s n -l numeric-sort --description 'compare according to string numerical value.'
complete -c sort -s r -l reverse --description 'reverse the result of comparisons . PP Other options:.'
complete -c sort -s c -l check --description 'check whether input is sorted; do not sort.'
complete -c sort -s k -l key --description 'start a key at POS1, end it at POS2 (origin 1).'
complete -c sort -s m -l merge --description 'merge already sorted files; do not sort.'
complete -c sort -s o -l output --description 'write result to FILE instead of standard output.'
complete -c sort -s s -l stable --description 'stabilize sort by disabling last-resort comparison.'
complete -c sort -s S -l buffer-size --description 'use SIZE for main memory buffer.'
complete -c sort -s t -l field-separator --description 'use SEP instead of non-blank to blank transition.'
complete -c sort -s T -l temporary-directory --description 'use DIR for temporaries, not $TMPDIR or /tmp; m… [See Man Page]'
complete -c sort -s u -l unique --description 'with -c, check for strict ordering; without -c,… [See Man Page]'
complete -c sort -s z -l zero-terminated --description 'end lines with 0 byte, not newline.'
complete -c sort -l help --description 'display this help and exit.'
complete -c sort -l version --description 'output version information and exit.'

