# spilog
# Autogenerated from man page /usr/share/man/man1/spilog.1
# using Darwin man parser
complete -c spilog -s a --description 'Description of -a flag.'
complete -c spilog -s b --description 'Description of -b flag \\" Ends the list Pp .'

