# split
# Autogenerated from man page /usr/share/man/man1/split.1
# using Darwin man parser
complete -c split -s a --description 'Use suffix_length letters to form the suffix of the file name.'
complete -c split -s b --description 'Create smaller files byte_count bytes in length.'
complete -c split -s l --description 'Create smaller files n lines in length.'
complete -c split -s p --description 'The file is split whenever an input line matche… [See Man Page]'

