# srm
# Autogenerated from man page /usr/share/man/man1/srm.1
# using Deroffing man parser
complete -c srm -s d -l directory --description 'ignored (for compatibility with rm(1)).'
complete -c srm -s f -l force --description 'ignore nonexistent files, never prompt.'
complete -c srm -s i -l interactive --description 'prompt before any removal.'
complete -c srm -s r -s R -l recursive --description 'remove the contents of directories recursively.'
complete -c srm -s s -l simple --description 'only overwrite with a single pass of random data.'
complete -c srm -s m -l medium --description 'overwrite the file with 7 US DoD compliant pass… [See Man Page]'
complete -c srm -s z -l zero --description 'after overwriting, zero blocks used by file.'
complete -c srm -s n -l nounlink --description 'overwrite file, but do not rename or unlink it.'
complete -c srm -s v -l verbose --description 'explain what is being done.'
complete -c srm -l help --description 'display this help and exit.'
complete -c srm -l version --description 'output version information and exit NOTES.'

