# sshd
# Autogenerated from man page /usr/share/man/man8/sshd.8
# using Darwin man parser
complete -c sshd -s 4 --description 'Forces sshd to use IPv4 addresses only.'
complete -c sshd -s 6 --description 'Forces sshd to use IPv6 addresses only.'
complete -c sshd -s b --description 'Specifies the number of bits in the ephemeral p… [See Man Page]'
complete -c sshd -s C --description 'Specify the connection parameters to use for th… [See Man Page]'
complete -c sshd -s c --description 'Specifies a path to a certificate file to ident… [See Man Page]'
complete -c sshd -s D --description 'When this option is specified, sshd will not de… [See Man Page]'
complete -c sshd -s d --description 'Debug mode.'
complete -c sshd -s e --description 'When this option is specified, sshd will send t… [See Man Page]'
complete -c sshd -s f --description 'Specifies the name of the configuration file.'
complete -c sshd -s g --description 'Gives the grace time for clients to authenticat… [See Man Page]'
complete -c sshd -s h --description 'Specifies a file from which a host key is read.'
complete -c sshd -s i --description 'Specifies that sshd is being run from inetd 8.'
complete -c sshd -s k --description 'Specifies how often the ephemeral protocol vers… [See Man Page]'
complete -c sshd -s o --description 'Can be used to give options in the format used … [See Man Page]'
complete -c sshd -s p --description 'Specifies the port on which the server listens … [See Man Page]'
complete -c sshd -s q --description 'Quiet mode.  Nothing is sent to the system log.'
complete -c sshd -s T --description 'Extended test mode.'
complete -c sshd -s t --description 'Test mode.'
complete -c sshd -s u --description 'This option is used to specify the size of the … [See Man Page]'

