# sso_util
# Autogenerated from man page /usr/share/man/man8/sso_util.8
# using Darwin man parser
complete -c sso_util -s p --description 'Returns the data in XML format.'
complete -c sso_util -s g --description 'Returns the default Kerberos realm name.'
complete -c sso_util -s l --description 'Returns a list of the services sso_util knows how to Kerberize.'
complete -c sso_util -s L --description 'Returns the default Kerberos log file paths.'
complete -c sso_util -s r --description 'Returns whether or not the given node has a Ker… [See Man Page]'
complete -c sso_util -s a --description 'Account name of an administrator authorized to … [See Man Page]'
complete -c sso_util -s u --description 'Forces the update, ignoring that the update may… [See Man Page]'
complete -c sso_util -s R --description 'Name of the Computer record containing the secu… [See Man Page]'
complete -c sso_util -s f --description 'Specifies the directory node in which to find t… [See Man Page]'

