# stat
# Autogenerated from man page /usr/share/man/man1/stat.1
# using Darwin man parser
complete -c stat -s F --description 'As in ls 1, display a slash / immediately after… [See Man Page]'
complete -c stat -s f --description 'Display information using the specified format.'
complete -c stat -s L --description 'Use stat 2 instead of lstat 2.'
complete -c stat -s l --description 'Display output in stat ls Fl lT format.  ==========.'
complete -c stat -s n --description 'Do not force a newline to appear at the end of … [See Man Page]'
complete -c stat -s q --description 'Suppress failure messages if calls to stat 2 or lstat 2 fail.'
complete -c stat -s r --description 'Display raw information.'
complete -c stat -s s --description 'Display information in "shell output", suitable… [See Man Page]'
complete -c stat -s t --description 'Display timestamps using the specified format.'
complete -c stat -s x --description 'Display information in a more verbose way as kn… [See Man Page]'

