# su
# Autogenerated from man page /usr/share/man/man1/su.1
# using Darwin man parser
complete -c su -s f --description 'If the invoked shell is csh 1, this option prev… [See Man Page]'
complete -c su -s l --description 'Simulate a full login.'
complete -c su -s m --description 'Leave the environment unmodified.'

