# suexec
# Autogenerated from man page /usr/share/man/man8/suexec.8
# using Deroffing man parser
complete -c suexec -s V --description 'If you are root, this option displays the compi… [See Man Page]'

