# sw_vers
# Autogenerated from man page /usr/share/man/man1/sw_vers.1
# using Darwin man parser
complete -c sw_vers -o productName --description 'Print just the value of the ProductName property.'
complete -c sw_vers -o productVersion --description 'Print just the value of the ProductVersion property.'
complete -c sw_vers -o buildVersion --description 'Print just the value of the BuildVersion property.'

