# symstacks
# Autogenerated from man page /usr/share/man/man1/symstacks.rb.1
# using Darwin man parser
complete -c symstacks -s D --description 'Turn on debugging.'
complete -c symstacks -s i --description 'Do an immediate snapshot, and exit.'
complete -c symstacks -s f --description 'Output the log information to the specified path.'
complete -c symstacks -s n --description 'Limit the number of snapshots taken; the default is 1.'
complete -c symstacks -s p --description 'Log the stack information for the specified process-ID only.'
complete -c symstacks -s B --description 'Specify the size of the trace buffer; the defau… [See Man Page]'
complete -c symstacks -s t --description 'Attempt to invoke sysdiagnose 1 This will also … [See Man Page]'
complete -c symstacks -s u --description 'Attempt symbolication.'
complete -c symstacks -s l --description 'Gather information on the loaded binary images … [See Man Page]'
complete -c symstacks -s O --description 'Gather OS trace information as part of the stac… [See Man Page]'
complete -c symstacks -s I --description 'Include the list of importance donors per proce… [See Man Page]'

