# sysctl
# Autogenerated from man page /usr/share/man/man8/sysctl.8
# using Darwin man parser
complete -c sysctl -s A --description 'Equivalent to o a (for compatibility).'
complete -c sysctl -s a --description 'List all the currently available non-opaque values.'
complete -c sysctl -s b --description 'Force the value of the variable(s) to be output… [See Man Page]'
complete -c sysctl -s d --description 'Print the description of the variable instead of its value.'
complete -c sysctl -s e --description 'Separate the name and the value of the variable(s) with =.'
complete -c sysctl -s h --description 'Format output for human, rather than machine, readability.'
complete -c sysctl -s i --description 'Ignore unknown OIDs.'
complete -c sysctl -s N --description 'Show only variable names, not their values.'
complete -c sysctl -s n --description 'Show only variable values, not their names.'
complete -c sysctl -s o --description 'Show opaque variables (which are normally suppressed).'
complete -c sysctl -s q --description 'Suppress some warnings generated by sysctl to standard error.'
complete -c sysctl -s X --description 'Equivalent to x a (for compatibility).'
complete -c sysctl -s x --description 'As o, but prints a hex dump of the entire value… [See Man Page]'

