# syslogd
# Autogenerated from man page /usr/share/man/man8/syslogd.8
# using Darwin man parser
complete -c syslogd -s d --description 'Run syslogd in debugging mode.'
complete -c syslogd -s D --description 'Start as a daemon.'
complete -c syslogd -s m --description 'Set the number of minutes between mark messages.'
complete -c syslogd -o db_max --description 'Sets the size limit in bytes for individual fil… [See Man Page]'
complete -c syslogd -o utmp_ttl --description 'Sets the time-to-live in seconds for messages u… [See Man Page]'
complete -c syslogd -o mps_limit --description 'Sets the kernel quota for messages per second a… [See Man Page]'
complete -c syslogd -o dup_delay --description 'Sets the time to delay for coalescing duplicate… [See Man Page]'
complete -c syslogd -o asl_in --description 'The asl_in module receives log messages on the … [See Man Page]'
complete -c syslogd -o asl_action --description 'The asl_action module examines the stream of re… [See Man Page]'
complete -c syslogd -o klog_in --description 'The klog_in module receives log messages on the… [See Man Page]'
complete -c syslogd -o bsd_in --description 'The bsd_in module receives log messages on the … [See Man Page]'
complete -c syslogd -o bsd_out --description 'The bsd_out module examines the stream of recei… [See Man Page]'
complete -c syslogd -o udp_in --description 'The udp_in module receives log messages on the … [See Man Page]'

