# systemkeychain
# Autogenerated from man page /usr/share/man/man8/systemkeychain.8
# using Darwin man parser
complete -c systemkeychain -s C --description 'Create a keychain and establish it in the syste… [See Man Page]'
complete -c systemkeychain -s s --description 'Extract the master secret from source keychain(… [See Man Page]'
complete -c systemkeychain -s t --description 'Test unlocking the system keychain.'
complete -c systemkeychain -s k --description 'Use a keychain other than the default as the de… [See Man Page]'
complete -c systemkeychain -s c --description 'Create the target keychain if necessary.'
complete -c systemkeychain -s f --description 'Force creation of a system keychain or overwrit… [See Man Page]'
complete -c systemkeychain -s v --description 'Turn on verbose mode.'

