# system_profiler
# Autogenerated from man page /usr/share/man/man8/system_profiler.8
# using Darwin man parser
complete -c system_profiler -o xml --description 'Generates a report in XML format.'
complete -c system_profiler -o listDataTypes --description 'Lists the available datatypes.  Pp.'
complete -c system_profiler -o detailLevel --description 'Specifies the level of detail for the report: -… [See Man Page]'
complete -c system_profiler -o timeout --description 'Specifies the maximum time to wait in seconds for results.'
complete -c system_profiler -o usage --description 'Prints usage info and examples.'

