# tab2space
# Autogenerated from man page /usr/share/man/man1/tab2space.1
# using Deroffing man parser
complete -c tab2space -o help -s h --description 'display this help message.'
complete -c tab2space -o dos -o crlf --description 'set line ends to CRLF (PC-DOS/Windows - default).'
complete -c tab2space -o mac -o cr --description 'set line ends to CR (classic Mac OS).'
complete -c tab2space -o unix -o lf --description 'set line ends to LF (Unix / Mac OS X).'
complete -c tab2space -o tabs --description 'preserve tabs, e. g.  for Makefile.'
complete -c tab2space -o 't<n>' --description 'set tabs to <n> (default is 4) spaces SEE ALSO.'

