# tabs
# Autogenerated from man page /usr/share/man/man1/tabs.1
# using Darwin man parser
complete -c tabs -s n --description 'Set a tab stop every n columns.'
complete -c tabs -s a --description 'Assembler format (columns 1, 10, 16, 36, 72).'
complete -c tabs -o a2 --description 'Assembler format (columns 1, 10, 16, 40, 72).'
complete -c tabs -s c --description 'COBOL normal format (columns 1, 8, 12, 16, 20, 55).'
complete -c tabs -o c2 --description 'COBOL compact format (columns 1, 6, 10, 14, 49).'
complete -c tabs -o c3 --description 'COBOL compact format (columns 1, 6, 10, 14, 18,… [See Man Page]'
complete -c tabs -s f --description 'FORTRAN format (columns 1, 7, 11, 15, 19, 23).'
complete -c tabs -s p --description 'PL/1 format (columns 1, 5, 9, 13, 17, 21, 25, 2… [See Man Page]'
complete -c tabs -s s --description 'SNOBOL format (columns 1, 10, 55).'
complete -c tabs -s u --description 'Assembler format (columns 1, 12, 20, 44).'
complete -c tabs -s T --description 'Output escape sequence for the terminal type type.'

