# tail
# Autogenerated from man page /usr/share/man/man1/tail.1
# using Darwin man parser
complete -c tail -s b --description 'The location is number 512-byte blocks.'
complete -c tail -s c --description 'The location is number bytes.'
complete -c tail -s f --description 'The f option causes tail to not stop when end o… [See Man Page]'
complete -c tail -s F --description 'The F option implies the f option, but tail wil… [See Man Page]'
complete -c tail -s n --description 'The location is number lines.'
complete -c tail -s q --description 'Suppresses printing of headers when multiple fi… [See Man Page]'
complete -c tail -s r --description 'The r option causes the input to be displayed i… [See Man Page]'

