# taskgated
# Autogenerated from man page /usr/share/man/man8/taskgated.8
# using Darwin man parser
complete -c taskgated -s p --description 'Accepts the old (Tiger) convention that a proce… [See Man Page]'
complete -c taskgated -s s --description 'Allow signed applications marked as "safe" to h… [See Man Page]'
complete -c taskgated -s t --description 'The daemon will quit after that many seconds of inactivity.'
complete -c taskgated -s i --description 'Inject the service port of taskgated into the p… [See Man Page]'

