# tbl
# Autogenerated from man page /usr/share/man/man1/tbl.1
# using Deroffing man parser
complete -c tbl -s C --description 'Enable compatibility mode to recognize  . TS and  .'
complete -c tbl -s t --description 'option of groff.  It is highly compatible with Unix tbl .'
complete -c tbl -s v --description 'Print the version number.'

