# tee
# Autogenerated from man page /usr/share/man/man1/tee.1
# using Darwin man parser
complete -c tee -s a --description 'Append the output to the files rather than overwriting them.'
complete -c tee -s i --description 'Ignore the SIGINT signal.'

