# telnetd
# Autogenerated from man page /usr/share/man/man8/telnetd.8
# using Darwin man parser
complete -c telnetd -s 4 --description 'Forces telnetd to use IPv4 addresses only.'
complete -c telnetd -s 6 --description 'Forces telnetd to use IPv6 addresses only.'
complete -c telnetd -s a --description 'This option may be used for specifying what mod… [See Man Page]'
complete -c telnetd -s B --description 'Specify bftp server mode.'
complete -c telnetd -s D --description 'This option may be used for debugging purposes.'
complete -c telnetd -o debug --description 'Enable debugging on each socket created by teln… [See Man Page]'
complete -c telnetd -o edebug --description 'If telnetd has been compiled with support for d… [See Man Page]'
complete -c telnetd -s p --description 'Specify an alternate login 1 command to run to … [See Man Page]'
complete -c telnetd -s h --description 'Disable the printing of host-specific informati… [See Man Page]'
complete -c telnetd -s k --description 'This option is only useful if telnetd has been … [See Man Page]'
complete -c telnetd -s l --description 'Specify line mode.'
complete -c telnetd -s n --description 'Disable TCP keep-alives.'
complete -c telnetd -s S --description 'Sets the IP type-of-service (TOS) option for th… [See Man Page]'
complete -c telnetd -s u --description 'This option is used to specify the size of the … [See Man Page]'
complete -c telnetd -s U --description 'This option causes telnetd to refuse connection… [See Man Page]'
complete -c telnetd -s X --description 'This option is only valid if telnetd has been b… [See Man Page]'

