# texindex
# Autogenerated from man page /usr/share/man/man1/texindex.1
# using Deroffing man parser
complete -c texindex -s h -l help --description 'display this help and exit.'
complete -c texindex -s k -l keep --description 'keep temporary files around after processing.'
complete -c texindex -l no-keep --description 'do not keep temporary files around after processing (default).'
complete -c texindex -s o -l output --description 'send output to FILE.'
complete -c texindex -l version --description 'display version information and exit REPORTING … [See Man Page]'

