# texi2dvi
# Autogenerated from man page /usr/share/man/man1/texi2dvi.1
# using Deroffing man parser
complete -c texi2dvi -s b -l batch --description 'no interaction.'
complete -c texi2dvi -s c -l clean --description 'remove all auxiliary files.'
complete -c texi2dvi -s D -l debug --description 'turn on shell debugging (set -x).'
complete -c texi2dvi -s h -l help --description 'display this help and exit successfully.'
complete -c texi2dvi -s o -l output --description 'leave output in OFILE (implies --clean); Only o… [See Man Page]'
complete -c texi2dvi -s q -l quiet --description 'no output unless errors (implies --batch).'
complete -c texi2dvi -s s -l silent --description 'same as --quiet.'
complete -c texi2dvi -s v -l version --description 'display version information and exit successfully.'
complete -c texi2dvi -s V -l verbose --description 'report on what is done . SS "TeX tuning:".'
complete -c texi2dvi -s @ --description 'use @input instead of input; for preloaded Texinfo.'
complete -c texi2dvi -s e -s E -l expand --description 'force macro expansion using makeinfo.'
complete -c texi2dvi -s I --description 'search DIR for Texinfo files.'
complete -c texi2dvi -s l -l language --description 'specify the LANG of FILE (LaTeX or Texinfo).'
complete -c texi2dvi -s p -l pdf --description 'use pdftex or pdflatex for processing.'
complete -c texi2dvi -s r -l recode --description 'call recode before TeX to translate input characters.'
complete -c texi2dvi -s t -l command --description 'insert CMD in copy of input file.'

