# tftpd
# Autogenerated from man page /usr/share/man/man8/tftpd.8
# using Darwin man parser
complete -c tftpd -s d --description 'Enable verbose debugging messages to syslogd 8.'
complete -c tftpd -s g --description 'Change gid to that of group on startup.'
complete -c tftpd -s i --description 'Enable insecure mode, no realpath 3.'
complete -c tftpd -s l --description 'Logs all requests using syslog 3.'
complete -c tftpd -s n --description 'Suppresses negative acknowledgement of requests… [See Man Page]'
complete -c tftpd -s s --description 'tftpd will chroot 2 to directory on startup.'
complete -c tftpd -s u --description 'Change uid to that of user on startup.'

