# ThunderboltIPLogger
# Autogenerated from man page /usr/share/man/man1/ThunderboltIPLogger.1
# using Darwin man parser
complete -c ThunderboltIPLogger -s a --description 'Description of -a flag.'
complete -c ThunderboltIPLogger -s b --description 'Description of -b flag \\" Ends the list Pp .'

