# timerfires
# Autogenerated from man page /usr/share/man/man1/timerfires.1
# using Darwin man parser
complete -c timerfires -s t --description 'Run only for timeout seconds; then exit.'
complete -c timerfires -s p --description 'Analyze only timers from the process with process ID pid.'
complete -c timerfires -s n --description 'Analyze only timers from processes with name name.'
complete -c timerfires -s s --description 'Show call stacks for "sleep"-type timers.'

