# time
# Autogenerated from man page /usr/share/man/man1/time.1
# using Darwin man parser
complete -c time -s l --description 'The contents of the rusage structure are printed.'
complete -c time -s p --description 'The output is formatted as specified by -p1003. 2-92.'

