# timed
# Autogenerated from man page /usr/share/man/man8/timed.8
# using Darwin man parser
complete -c timed -s d --description 'Enable debugging mode; do not detach from the terminal.'
complete -c timed -s i --description 'Add network to the list of networks to ignore.'
complete -c timed -s F --description 'in +2 ti -2 - Create a list of trusted hosts.'
complete -c timed -s M --description 'Allow this host to become a timed master if necessary.'
complete -c timed -s n --description 'Add network to the list of allowed networks.'
complete -c timed -s t --description 'Enable tracing of received messages and log to … [See Man Page]'

