# tkcon
# Autogenerated from man page /usr/share/man/man1/tkcon.1
# using Deroffing man parser
complete -c tkcon -o argv -l ')' --description 'Causes TkCon to stop evaluating arguments and s… [See Man Page]'
complete -c tkcon -o 'color-<color>' --description 'Sets the requested color type to the specified color for tkcon.'
complete -c tkcon -o eval -o main -o 'e)' --description 'A Tcl script to eval in each main interpreter.'
complete -c tkcon -o exec --description 'Sets the named slave that tkcon operates in.'
complete -c tkcon -o font --description 'Sets the font that tkcon uses for its text windows.'
complete -c tkcon -o nontcl --description 'Sets ::tkcon::OPT(nontcl) to TCL_BOOLEAN (see tkconrc(5)).'
complete -c tkcon -o package -o 'load)' --description 'Packages to automatically load into the slave interpreters (i.'
complete -c tkcon -o rcfile --description 'Specify an alternate tkcon resource file name.'
complete -c tkcon -o root --description 'Makes the named widget the root name of all consoles (i. e.'
complete -c tkcon -o slave --description 'A Tcl script to eval in each slave interpreter.'

