# tmdiagnose
# Autogenerated from man page /usr/share/man/man8/tmdiagnose.8
# using Darwin man parser
complete -c tmdiagnose -s h --description 'Print full usage.'
complete -c tmdiagnose -s d --description 'Delay the start of the diagnostic by sec seconds.'
complete -c tmdiagnose -s f --description 'Write the diagnostic to the specified path.'
complete -c tmdiagnose -s m --description 'Gather memory diagnostics for backupd, mtmd, mtmfs, and Finder.'
complete -c tmdiagnose -s r --description 'Do not reveal the diagnostic in Finder when finished.'

