# tmutil
# Autogenerated from man page /usr/share/man/man8/tmutil.8
# using Darwin man parser
complete -c tmutil -l auto --description 'Run the backup in a mode similar to system-scheduled backups.'
complete -c tmutil -l block --description 'Wait (block) until the backup is finished before exiting.'
complete -c tmutil -l rotation --description 'Allow automatic destination rotation during the backup.'
complete -c tmutil -l destination --description 'Perform the backup to the destination correspon… [See Man Page]'
complete -c tmutil -s a --description 'Compare all supported metadata.'
complete -c tmutil -s @ --description 'Compare extended attributes.'
complete -c tmutil -s e --description 'Compare ACLs.'
complete -c tmutil -s s --description 'Compare sizes.'
complete -c tmutil -s m --description 'Compare file modes.'
complete -c tmutil -s u --description 'Compare UIDs.'
complete -c tmutil -s g --description 'Compare GIDs.'
complete -c tmutil -s t --description 'Compare modification times.'
complete -c tmutil -s n --description 'No metadata comparison.'
complete -c tmutil -s d --description 'Compare file data forks.'
complete -c tmutil -s D --description 'Limit traversal depth to depth levels from the … [See Man Page]'
complete -c tmutil -s E --description 'Don\'t take exclusions into account when compari… [See Man Page]'
complete -c tmutil -s I --description 'Ignore paths with a path component equal to nam… [See Man Page]'
complete -c tmutil -s U --description 'Ignore logical volume identity (volume UUIDs) w… [See Man Page]'
complete -c tmutil -s X --description 'Print output in XML property list format.'

