# tokenadmin
# Autogenerated from man page /usr/share/man/man8/tokenadmin.8
# using Darwin man parser
complete -c tokenadmin -s h --description 'With no arguments, shows a list of all commands.'
complete -c tokenadmin -s q --description 'Makes tokenadmin less verbose.'
complete -c tokenadmin -s v --description 'Makes tokenadmin more verbose.'
complete -c tokenadmin -s u --description 'Specify the short (i. e.'
complete -c tokenadmin -s l --description 'Specify the full name to be used for the account.'
complete -c tokenadmin -s p --description 'Password for the user\'s login keychain (optional).'

