# topsyscall
# Autogenerated from man page /usr/share/man/man1/topsyscall.1m
# using Deroffing man parser
complete -c topsyscall -s C --description 'don\'t clear the screen.'
complete -c topsyscall -s s --description 'print per second values.'

