# topsysproc
# Autogenerated from man page /usr/share/man/man1/topsysproc.1m
# using Deroffing man parser
complete -c topsysproc -s C --description 'don\'t clear the screen.'
complete -c topsysproc -s s --description 'print per second values.'

