# touch
# Autogenerated from man page /usr/share/man/man1/touch.1
# using Darwin man parser
complete -c touch -s A --description 'Adjust the access and modification time stamps … [See Man Page]'
complete -c touch -s a --description 'Change the access time of the file.'
complete -c touch -s c --description 'Do not create the file if it does not exist.'
complete -c touch -s f --description 'Attempt to force the update, even if the file p… [See Man Page]'
complete -c touch -s h --description 'If the file is a symbolic link, change the time… [See Man Page]'
complete -c touch -s m --description 'Change the modification time of the file.'
complete -c touch -s r --description 'Use the access and modifications times from the… [See Man Page]'
complete -c touch -s t --description 'Change the access and modification times to the… [See Man Page]'

