# tr
# Autogenerated from man page /usr/share/man/man1/tr.1
# using Darwin man parser
complete -c tr -s C --description 'Complement the set of characters in string1, th… [See Man Page]'
complete -c tr -s c --description 'Same as C but complement the set of values in string1.'
complete -c tr -s d --description 'Delete characters in string1 from the input.'
complete -c tr -s s --description 'Squeeze multiple occurrences of the characters … [See Man Page]'
complete -c tr -s u --description 'Guarantee that any output is unbuffered.'

