# traceroute6
# Autogenerated from man page /usr/share/man/man8/traceroute6.8
# using Darwin man parser
complete -c traceroute6 -s d --description 'Debug mode.'
complete -c traceroute6 -s f --description 'Specify how many hops to skip in trace.'
complete -c traceroute6 -s g --description 'Specify intermediate gateway traceroute6 ( uses… [See Man Page]'
complete -c traceroute6 -s I --description 'Use ICMP6 ECHO instead of UDP datagrams.'
complete -c traceroute6 -s l --description 'Print both host hostnames and numeric addresses.'
complete -c traceroute6 -s m --description 'Specify maximum hoplimit, up to 255.  The default is 30 hops.'
complete -c traceroute6 -s n --description 'Do not resolve numeric address to hostname.'
complete -c traceroute6 -s N --description 'Use a packet with no upper layer header for the… [See Man Page]'
complete -c traceroute6 -s p --description 'Set UDP port number to port.'
complete -c traceroute6 -s q --description 'Set the number of probe per hop count to probes.'
complete -c traceroute6 -s r --description 'Bypass the normal routing tables and send direc… [See Man Page]'
complete -c traceroute6 -s s --description 'Src specifies the source IPv6 address to be used.'
complete -c traceroute6 -s U --description 'Use UDP datagrams for the probes.  This is the default.'
complete -c traceroute6 -s v --description 'Be verbose.'
complete -c traceroute6 -s w --description 'Specify the delay time between probes.'

