# traptoemail
# Autogenerated from man page /usr/share/man/man1/traptoemail.1
# using Deroffing man parser
complete -c traptoemail -s f --description 'sender address, defaults to "root".'
complete -c traptoemail -s s --description 'SMTP server, defaults to "localhost".'

