# truspi
# Autogenerated from man page /usr/share/man/man1/truspi.1
# using Darwin man parser
complete -c truspi -s a --description 'Description of -a flag.'
complete -c truspi -s b --description 'Description of -b flag \\" Ends the list Pp .'

