# tsort
# Autogenerated from man page /usr/share/man/man1/tsort.1
# using Darwin man parser
complete -c tsort -s l --description 'Search for and display the longest cycle.'
complete -c tsort -s q --description 'Do not display informational messages about cycles.'

