# umount
# Autogenerated from man page /usr/share/man/man8/umount.8
# using Darwin man parser
complete -c umount -s a --description 'All the filesystems described via getfsent 3 are unmounted.'
complete -c umount -s A --description 'All the currently mounted filesystems except th… [See Man Page]'
complete -c umount -s f --description 'The filesystem is forcibly unmounted.'
complete -c umount -s h --description 'Only filesystems mounted from the specified hos… [See Man Page]'
complete -c umount -s t --description 'Is used to indicate the actions should only be … [See Man Page]'
complete -c umount -s v --description 'Verbose, additional information is printed out … [See Man Page]'

