# uname
# Autogenerated from man page /usr/share/man/man1/uname.1
# using Darwin man parser
complete -c uname -s a --description 'Behave as though all of the options mnrsv were specified.'
complete -c uname -s m --description 'print the machine hardware name.'
complete -c uname -s n --description 'print the nodename (the nodename may be a name … [See Man Page]'
complete -c uname -s p --description 'print the machine processor architecture name.'
complete -c uname -s r --description 'print the operating system release.'
complete -c uname -s s --description 'print the operating system name.'
complete -c uname -s v --description 'print the operating system version.'

