# unexpand
# Autogenerated from man page /usr/share/man/man1/unexpand.1
# using Darwin man parser
complete -c unexpand -s a --description 'unexpand ( unexpand only.'
complete -c unexpand -s t --description 'Set tab stops at column positions tab1 , tab2 , .  , tabn.'

