# unpack200
# Autogenerated from man page /usr/share/man/man1/unpack200.1
# using Deroffing man parser
complete -c unpack200 -s H -l deflate-hint --description 'Sets the deflation to be true, false, or keep o… [See Man Page]'
complete -c unpack200 -s r -l remove-pack-file --description 'Removes the input packed-file.'
complete -c unpack200 -s v -l verbose --description 'Outputs minimal messages, multiple specificatio… [See Man Page]'
complete -c unpack200 -s q -l quiet --description 'Specifies quiet operation with no messages.'
complete -c unpack200 -s l -l log-file --description 'Specifies a log file to output messages.'

