# unzipsfx
# Autogenerated from man page /usr/share/man/man1/unzipsfx.1
# using Deroffing man parser
complete -c unzipsfx -s j -s V --description 'following operating-system specific options:  -… [See Man Page]'

