# update_dyld_shared_cache
# Autogenerated from man page /usr/share/man/man1/update_dyld_shared_cache.1
# using Darwin man parser
complete -c update_dyld_shared_cache -o root --description 'This option specifies the root of an OS install… [See Man Page]'
complete -c update_dyld_shared_cache -o overlay --description 'This option specifies the root of a sparse directory tree.'
complete -c update_dyld_shared_cache -o arch --description 'By default update_dyld_shared_cache update_dyld… [See Man Page]'
complete -c update_dyld_shared_cache -o force --description 'This option will cause update_dyld_shared_cache… [See Man Page]'
complete -c update_dyld_shared_cache -o debug --description 'This option prints out additional information a… [See Man Page]'
complete -c update_dyld_shared_cache -o sort_by_name --description 'By default update_dyld_shared_cache update_dyld… [See Man Page]'
complete -c update_dyld_shared_cache -o universal_boot --description 'This option can only be used running on an mach… [See Man Page]'
complete -c update_dyld_shared_cache -o dylib_list --description 'Instead of scanning /var/db/dyld/shared_region_… [See Man Page]'
complete -c update_dyld_shared_cache -o verify --description 'Will regenerate a shared cache in-memory that m… [See Man Page]'
complete -c update_dyld_shared_cache -o iPhone --description 'indicates that cache is not for the current Mac… [See Man Page]'
complete -c update_dyld_shared_cache -o cache_dir --description 'This option specifies the directory in which to… [See Man Page]'

