# uuconv
# Autogenerated from man page /usr/share/man/man1/uuconv.1
# using Deroffing man parser
complete -c uuconv -s i -l input --description 'Set input type (one of taylor, v2, hdb).'
complete -c uuconv -s o -l output --description 'Set output type (one of taylor, v2, hdb).'
complete -c uuconv -s p -l program --description 'Program to convert (e. g. , uucp or cu).'
complete -c uuconv -s v -l version --description 'Report version information and exit.'
complete -c uuconv -l help --description 'Print a help message and exit.'

