# uucp
# Autogenerated from man page /usr/share/man/man1/uucp.1
# using Deroffing man parser
complete -c uucp -s c -l nocopy --description 'Do not copy local source files to the spool directory.'
complete -c uucp -s C -l copy --description 'Copy local source files to the spool directory.'
complete -c uucp -s d -l directories --description 'Create all necessary directories when doing the copy.'
complete -c uucp -s f -l nodirectories --description 'If any necessary directories do not exist for t… [See Man Page]'
complete -c uucp -s R -l recursive --description 'If any of the source file names are directories… [See Man Page]'
complete -c uucp -s g -l grade --description 'Set the grade of the file transfer command.'
complete -c uucp -s m -l mail --description 'Report completion or failure of the file transfer by  mail (1).'
complete -c uucp -s n -l notify --description 'Report completion or failure of the file transf… [See Man Page]'
complete -c uucp -s r -l nouucico --description 'Do not start  uucico (8) daemon immediately; me… [See Man Page]'
complete -c uucp -s j -l jobid --description 'Print jobid on standard output.'
complete -c uucp -s W -l noexpand --description 'Do not prepend remote relative path names with … [See Man Page]'
complete -c uucp -s t -l uuto --description 'This option is used by the   uuto shell script.'
complete -c uucp -s x -l debug --description 'Turn on particular debugging types.'
complete -c uucp -s I -l config --description 'Set configuration file to use.'
complete -c uucp -s v -l version --description 'Report version information and exit.'
complete -c uucp -s k --description 'switch of uustat (1).'
complete -c uucp -l help --description 'Print a help message and exit.'

