# uuencode
# Autogenerated from man page /usr/share/man/man1/uuencode.1
# using Darwin man parser
complete -c uuencode -s m --description 'Use the Base64 method of encoding, rather than … [See Man Page]'
complete -c uuencode -s o --description 'Output to output_file instead of standard output.'
complete -c uuencode -s c --description 'Decode more than one uuencode\'d file from file if possible.'
complete -c uuencode -s i --description 'Do not overwrite files.'
complete -c uuencode -s p --description 'Decode file and write output to standard output.'
complete -c uuencode -s s --description 'Do not strip output pathname to base filename.'

