# uuidgen
# Autogenerated from man page /usr/share/man/man1/uuidgen.1
# using Darwin man parser
complete -c uuidgen -o hdr --description 'Emit CoreFoundation CFUUID-based source code fo… [See Man Page]'

