# uuid
# Autogenerated from man page /usr/local/share/man/man1/uuid.1
# using Type1
complete -c uuid -s v --description 'Sets the version of the generated \\s-1DCE\\s0 1.'
complete -c uuid -s m --description 'Forces the use of a random multi-cast \\s-1MAC\\s… [See Man Page]'
complete -c uuid -s n --description 'Generate count UUIDs instead of just a single o… [See Man Page]'
complete -c uuid -s 1 --description 'If option -n is used with a count greater than … [See Man Page]'
complete -c uuid -s F --description 'Representation format for importing or exportin… [See Man Page]'
complete -c uuid -s o --description 'Write output to filename instead of to stdout.'

