# uulog
# Autogenerated from man page /usr/share/man/man1/uulog.1
# using Deroffing man parser
complete -c uulog -s '#' -s n -l lines --description 'Here \'#\' is a number; e. g. , `-10\'.'
complete -c uulog -s s -l system --description 'Display only log entries pertaining to the specified system.'
complete -c uulog -s u -l user --description 'Display only log entries pertaining to the specified user.'
complete -c uulog -s D -l debuglog --description 'Display the debugging log file.'
complete -c uulog -s S -l statslog --description 'Display the statistics log file.'
complete -c uulog -s F -l follow --description 'Keep displaying the log file forever, printing … [See Man Page]'
complete -c uulog -s f --description 'Keep displaying the log file forever, displayin… [See Man Page]'
complete -c uulog -s X -l debug --description 'Turn on particular debugging types.'
complete -c uulog -s I -l config --description 'Set configuration file to use.'
complete -c uulog -s v -l version --description 'Report version information and exit.'
complete -c uulog -l help --description 'Print a help message and exit.'

