# uupick
# Autogenerated from man page /usr/share/man/man1/uupick.1
# using Deroffing man parser
complete -c uupick -s s -l system --description 'Used to restrict `uupick\' to only present files… [See Man Page]'
complete -c uupick -s x -l debug --description 'Turn on particular debugging types.'
complete -c uupick -s I -l config --description 'Set configuration file to use.'
complete -c uupick -s v -l version --description 'Report version information and exit.'
complete -c uupick -l help --description 'Print a help message and exit.'

