# uuxqt
# Autogenerated from man page /usr/share/man/man8/uuxqt.8
# using Deroffing man parser
complete -c uuxqt -s c -l command --description 'Only execute requests for the specified command.'
complete -c uuxqt -s s -l system --description 'Only execute requests originating from the specified system.'
complete -c uuxqt -s x -l debug --description 'Turn on particular debugging types.'
complete -c uuxqt -s I -l config --description 'Set configuration file to use.'
complete -c uuxqt -s v -l version --description 'Report version information and exit.'
complete -c uuxqt -s q --description 'or.'
complete -c uuxqt -l nouuxqt --description 'option).'
complete -c uuxqt -l help --description 'Print a help message and exit.'

