# vis
# Autogenerated from man page /usr/share/man/man1/vis.1
# using Darwin man parser
complete -c vis -s b --description 'Turns off prepending of backslash before up-arr… [See Man Page]'
complete -c vis -s c --description 'Request a format which displays a small subset … [See Man Page]'
complete -c vis -s F --description 'Causes vis to fold output lines to foldwidth co… [See Man Page]'
complete -c vis -s f --description 'Same as F.'
complete -c vis -s l --description 'Mark newlines with the visible sequence \\e$, fo… [See Man Page]'
complete -c vis -s n --description 'Turns off any encoding, except for the fact tha… [See Man Page]'
complete -c vis -s o --description 'Request a format which displays non-printable c… [See Man Page]'
complete -c vis -s s --description 'Only characters considered unsafe to send to a … [See Man Page]'
complete -c vis -s t --description 'Tabs are also encoded.'
complete -c vis -s w --description 'White space (space-tab-newline) is also encoded.'

