# visudo
# Autogenerated from man page /usr/share/man/man8/visudo.8
# using Type1
complete -c visudo -s c --description 'Enable check-only mode.'
complete -c visudo -s f --description 'Specify and alternate sudoers file location.'
complete -c visudo -s q --description 'Enable quiet mode.'
complete -c visudo -s s --description 'Enable strict checking of the sudoers file.'

