# vpnd
# Autogenerated from man page /usr/share/man/man8/vpnd.8
# using Darwin man parser
complete -c vpnd -s d --description 'Do not move to background and print log strings… [See Man Page]'
complete -c vpnd -s h --description 'Print usage summary and exit.'
complete -c vpnd -s i --description 'Server_id in the plist file that defines the co… [See Man Page]'
complete -c vpnd -s n --description 'Do not move to background, print log informatio… [See Man Page]'
complete -c vpnd -s x --description 'Do not move to background.'

