# vsdbutil
# Autogenerated from man page /usr/share/man/man8/vsdbutil.8
# using Darwin man parser
complete -c vsdbutil -s a --description 'adopts (activates) on-disk ownership on the specified path.'
complete -c vsdbutil -s c --description 'checks the status of the ownership usage on the specified path.'
complete -c vsdbutil -s d --description 'disowns (deactivates) the on-disk ownership on … [See Man Page]'
complete -c vsdbutil -s i --description 'initializes the ownership database to include a… [See Man Page]'
complete -c vsdbutil -s h --description 'prints out a simple help message El Pp The vsdb… [See Man Page]'

