# w
# Autogenerated from man page /usr/share/man/man1/w.1
# using Darwin man parser
complete -c w -s h --description 'Suppress the heading.'
complete -c w -s i --description 'Output is sorted by idle time.'

