# wc
# Autogenerated from man page /usr/share/man/man1/wc.1
# using Darwin man parser
complete -c wc -s c --description 'The number of bytes in each input file is writt… [See Man Page]'
complete -c wc -s l --description 'The number of lines in each input file is writt… [See Man Page]'
complete -c wc -s m --description 'The number of characters in each input file is … [See Man Page]'
complete -c wc -s w --description 'The number of words in each input file is writt… [See Man Page]'

