# weakpass_edit
# Autogenerated from man page /usr/share/man/man8/weakpass_edit.8
# using Darwin man parser
complete -c weakpass_edit -s p --description 'add or delete a passphrase, provided as a comma… [See Man Page]'
complete -c weakpass_edit -s f --description 'add or delete all passphrases contained in a file.'

