# which
# Autogenerated from man page /usr/share/man/man1/which.1
# using Darwin man parser
complete -c which -s a --description 'List all instances of executables found (instea… [See Man Page]'
complete -c which -s s --description 'No output, just return 0 if any of the executab… [See Man Page]'

