# who
# Autogenerated from man page /usr/share/man/man1/who.1
# using Darwin man parser
complete -c who -s a --description 'Same as bdlprTtu.'
complete -c who -s b --description 'Time of last system boot.'
complete -c who -s d --description 'Print dead processes.'
complete -c who -s H --description 'Write column headings above the regular output.'
complete -c who -s l --description 'Print system login processes (unsupported).'
complete -c who -s m --description 'Only print information about the current terminal.'
complete -c who -s p --description 'Print active processes spawned by launchd 8 (unsupported).'
complete -c who -s q --description 'Quick mode : List only the names and the number… [See Man Page]'
complete -c who -s r --description 'Print the current runlevel.  This is meaningless on Mac OS X.'
complete -c who -s s --description 'List only the name, line and time fields.  This is the default.'
complete -c who -s T --description 'Print a character after the user name indicatin… [See Man Page]'
complete -c who -s t --description 'Print last system clock change (unsupported).'
complete -c who -s u --description 'Print the idle time for each user, and the asso… [See Man Page]'

