# whois
# Autogenerated from man page /usr/share/man/man1/whois.1
# using Darwin man parser
complete -c whois -s 6 --description 'Use the IPv6 Resource Center 6bone database.'
complete -c whois -s A --description 'Use the Asia/Pacific Network Information Center APNIC database.'
complete -c whois -s a --description 'Use the American Registry for Internet Numbers ARIN database.'
complete -c whois -s b --description 'Use the Network Abuse Clearinghouse database.'
complete -c whois -s c --description 'This is the equivalent of using the h option wi… [See Man Page]'
complete -c whois -s d --description 'Use the US Department of Defense database.'
complete -c whois -s g --description 'Use the US non-military federal government data… [See Man Page]'
complete -c whois -s h --description 'Use the specified host instead of the default variant.'
complete -c whois -s I --description 'Use the Internet Assigned Numbers Authority IANA database.'
complete -c whois -s i --description 'Use the Network Solutions Registry for Internet Numbers whois.'
complete -c whois -s l --description 'Use the Latin American and Caribbean IP address… [See Man Page]'
complete -c whois -s m --description 'Use the Route Arbiter Database RADB database.'
complete -c whois -s p --description 'Connect to the whois server on port.'
complete -c whois -s Q --description 'Do a quick lookup.'
complete -c whois -s R --description 'Use the Russia Network Information Center RIPN database.'
complete -c whois -s r --description 'Use the R\\(aaeseaux IP Europ\\(aaeens RIPE database.'

