# wish8
# Autogenerated from man page /usr/share/man/man1/wish8.5.1tcl
# using Deroffing man parser
complete -c wish8 -o encoding --description 'VS 8. 5 Specifies the encoding of the text stored in fileName.'
complete -c wish8 -o container --description '.'

