# wsgen
# Autogenerated from man page /usr/share/man/man1/wsgen.1
# using Deroffing man parser
complete -c wsgen -o classpath --description 'Specify where to find input class files.'
complete -c wsgen -o cp --description 'Same as -classpath.'
complete -c wsgen -s d --description 'Specify where to place generated output files.'
complete -c wsgen -o extension --description 'allow vendor extensions (functionality not spec… [See Man Page]'
complete -c wsgen -o help --description 'Display help.'
complete -c wsgen -o keep --description 'Keep generated files.'
complete -c wsgen -s r --description 'Used only in conjunction with the \\f3-wsdl option.'
complete -c wsgen -s s --description 'Specify where to place generated source files.'
complete -c wsgen -o verbose --description 'Output messages about what the compiler is doing.'
complete -c wsgen -o version --description 'Print version information.'
complete -c wsgen -o 'wsdl[:' --description 'By default \\f3wsgen does not generate a WSDL file.'
complete -c wsgen -o servicename --description 'Used only in conjunction with the \\f3-wsdl option.'
complete -c wsgen -o portname --description 'Used only in conjunction with the -wsdl option.'

