# xargs
# Autogenerated from man page /usr/share/man/man1/xargs.1
# using Darwin man parser
complete -c xargs -s 0 --description 'Change xargs to expect NUL (``\\\\0\'\') characters… [See Man Page]'
complete -c xargs -s E --description 'Use eofstr as a logical EOF marker.'
complete -c xargs -s I --description 'Execute utility for each input line, replacing … [See Man Page]'
complete -c xargs -s J --description 'If this option is specified, xargs will use the… [See Man Page]'
complete -c xargs -s L --description 'Call utility for every number non-empty lines read.'
complete -c xargs -s n --description 'Set the maximum number of arguments taken from … [See Man Page]'
complete -c xargs -s o --description 'Reopen stdin as /dev/tty in the child process b… [See Man Page]'
complete -c xargs -s P --description 'Parallel mode: run at most maxprocs invocations… [See Man Page]'
complete -c xargs -s p --description 'Echo each command to be executed and ask the us… [See Man Page]'
complete -c xargs -s R --description 'Specify the maximum number of arguments that I … [See Man Page]'
complete -c xargs -s s --description 'Set the maximum number of bytes for the command… [See Man Page]'
complete -c xargs -s t --description 'Echo the command to be executed to standard err… [See Man Page]'
complete -c xargs -s x --description 'Force xargs to terminate immediately if a comma… [See Man Page]'

