# xattr
# Autogenerated from man page /usr/share/man/man1/xattr.1
# using Darwin man parser
complete -c xattr -s l --description 'By default, the first two command forms either … [See Man Page]'
complete -c xattr -s r --description 'If a file argument is a directory, act as if th… [See Man Page]'
complete -c xattr -s s --description 'If a file argument is a symbolic link, act on t… [See Man Page]'
complete -c xattr -s v --description 'Force the the file name to be displayed, even f… [See Man Page]'
complete -c xattr -s x --description 'Force the attribute value to be displayed in th… [See Man Page]'

