# xcode-select
# Autogenerated from man page /usr/share/man/man1/xcode-select.1
# using Deroffing man parser
complete -c xcode-select -s h -l help --description 'Prints the usage message. UNINDENT NDENT 0. 0.'
complete -c xcode-select -s s -l switch --description 'Sets the active developer directory to the give… [See Man Page]'
complete -c xcode-select -s p -l print-path --description 'Prints the path to the currently selected developer directory.'
complete -c xcode-select -s r -l reset --description 'Unsets any user-specified developer directory, … [See Man Page]'
complete -c xcode-select -s v -l version --description 'Prints xcode-select version information. UNINDENT NDENT 0. 0.'
complete -c xcode-select -l install --description 'Opens a user interface dialog to request automa… [See Man Page]'

