# xcscontrol
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcscontrol.1
# using Type1
complete -c xcscontrol -s h -l help -l usage --description 'Prints basic usage information.'
complete -c xcscontrol -l start --description 'Starts Xcode Server.'
complete -c xcscontrol -l stop --description 'Stops Xcode Server.'
complete -c xcscontrol -l restart --description 'Restarts Xcode Server.'
complete -c xcscontrol -l startDatabase --description 'Starts the Xcode Server database process.'
complete -c xcscontrol -l stopDatabase --description 'Cleanly stops the Xcode Server database.'
complete -c xcscontrol -l resetDatabase --description 'Resets the database to an empty schema and starts the database.'
complete -c xcscontrol -l observeAvailableDevices --description 'Observes the current set of available devices a… [See Man Page]'
complete -c xcscontrol -l observeAndPersistAvailableDevices --description 'Observes the current set of available devices a… [See Man Page]'

