# xscertadmin
# Autogenerated from man page /usr/share/man/man8/xscertadmin.8
# using Darwin man parser
complete -c xscertadmin -o x/--xml --description 'Returns output to stdout in xml format.'
complete -c xscertadmin -o v/--version --description 'Print the version of the tool.'
complete -c xscertadmin -o d/--debug --description 'Sets the level of diagnostic message detail, 0 … [See Man Page]'
complete -c xscertadmin -o a/--all --description 'List all CRLs El ADD OPTIONS -tag -width stringtosetspacing12.'
complete -c xscertadmin -o f/--file --description 'A file containing names.'
complete -c xscertadmin -o i/--issuer --description 'The common name of the issuer of the certificate.'
complete -c xscertadmin -o r/--reason --description 'The revocation reason code.'
complete -c xscertadmin -o s/--serial --description 'The serial number of the certificate to revoke.'
complete -c xscertadmin -o t/--type --description 'The record type: user, device, computer or recordType.'

