# xssendevent
# Autogenerated from man page /usr/share/man/man8/xssendevent.8
# using Darwin man parser
complete -c xssendevent -s e --description 'Tells xssendevent to load a file of events in t… [See Man Page]'

