# ypbind
# Autogenerated from man page /usr/share/man/man8/ypbind.8
# using Darwin man parser
complete -c ypbind -o ypset --description 'ypset 8 may be used to change the server to whi… [See Man Page]'
complete -c ypbind -o ypsetme --description 'ypset 8 may be used only from this machine to c… [See Man Page]'
complete -c ypbind -o insecure --description 'permit binding to a ypserv 8 on a non-reserved port.'
complete -c ypbind -s d --description 'enable debugging output.'

