# ypcat
# Autogenerated from man page /usr/share/man/man1/ypcat.1
# using Darwin man parser
complete -c ypcat -s d --description 'Specify a domain other than the default domain.'
complete -c ypcat -s k --description 'Display map keys.'
complete -c ypcat -s t --description 'Inhibit translation of map nicknames to their c… [See Man Page]'
complete -c ypcat -s x --description 'Display the map nickname table.'

