# ypmatch
# Autogenerated from man page /usr/share/man/man1/ypmatch.1
# using Darwin man parser
complete -c ypmatch -s d --description 'Specify a domain other than the default domain.'
complete -c ypmatch -s k --description 'Display map keys.'
complete -c ypmatch -s t --description 'Inhibit translation of map nicknames to their c… [See Man Page]'
complete -c ypmatch -s x --description 'Display the map nickname table.'

