# yppoll
# Autogenerated from man page /usr/share/man/man8/yppoll.8
# using Darwin man parser
complete -c yppoll -s d --description 'Don\'t use default domain, use the specified domain.'
complete -c yppoll -s h --description 'Get map information from host instead of the default YP server.'

