# ypset
# Autogenerated from man page /usr/share/man/man8/ypset.8
# using Darwin man parser
complete -c ypset -s h --description 'Set the YP binding on host instead of the local machine.'
complete -c ypset -s d --description 'Use the YP domain domain instead of the default… [See Man Page]'

