# ypwhich
# Autogenerated from man page /usr/share/man/man1/ypwhich.1
# using Darwin man parser
complete -c ypwhich -s d --description 'Specify a domain other than the default domain.'
complete -c ypwhich -s t --description 'Inhibit translation of map nicknames to their c… [See Man Page]'
complete -c ypwhich -s m --description 'Find the master YP server for the named map.'
complete -c ypwhich -s x --description 'Display the map nickname table.'

