# zcat
# Autogenerated from man page /usr/share/man/man1/zcat.1
# using Darwin man parser
complete -c zcat -s 1 --description '.'
complete -c zcat -s 2 --description '.'
complete -c zcat -s 9 --description 'These options change the compression level used… [See Man Page]'
complete -c zcat -s c --description 'This option specifies that output will go to th… [See Man Page]'
complete -c zcat -s d --description 'This option selects decompression rather than compression.'
complete -c zcat -s f --description 'This option turns on force mode.'
complete -c zcat -s h --description 'This option prints a usage summary and exits.'
complete -c zcat -s k --description 'Keep (don\'t delete) input files during compress… [See Man Page]'
complete -c zcat -s L --description 'This option prints zcat license.'
complete -c zcat -s l --description 'This option displays information about the file… [See Man Page]'
complete -c zcat -s N --description 'This option causes the stored filename in the i… [See Man Page]'
complete -c zcat -s n --description 'This option stops the filename and timestamp fr… [See Man Page]'
complete -c zcat -s q --description 'With this option, no warnings or errors are printed.'
complete -c zcat -s r --description 'This option is used to zcat the files in a dire… [See Man Page]'
complete -c zcat -s S --description 'This option changes the default suffix from . gz to suffix.'
complete -c zcat -s t --description 'This option will test compressed files for integrity.'
complete -c zcat -s V --description 'This option prints the version of the zcat program.'
complete -c zcat -s v --description 'This option turns on verbose mode, which prints… [See Man Page]'

