# znew
# Autogenerated from man page /usr/share/man/man1/znew.1
# using Darwin man parser
complete -c znew -s f --description 'Overwrite existing . gz files.'
complete -c znew -s t --description 'Test integrity of the gzipped file before delet… [See Man Page]'
complete -c znew -s v --description 'Print a report specifying the achieved compression ratios.'
complete -c znew -s 9 --description 'Use the -9 mode of gzip 1, achieving better com… [See Man Page]'
complete -c znew -s K --description 'Keep the original .'

