# zprint
# Autogenerated from man page /usr/share/man/man1/zprint.1
# using Deroffing man parser
complete -c zprint -s c --description '(Default) zprint prints zone info in columns.'
complete -c zprint -s h --description '(Default) Shows headings for the columns printe… [See Man Page]'
complete -c zprint -s s --description 'zprint sorts the zones, showing the zone wastin… [See Man Page]'
complete -c zprint -s w --description 'For each zone, zprint calculates how much space… [See Man Page]'
complete -c zprint -s t --description 'For each zone, zprint calculates the total size… [See Man Page]'
complete -c zprint -s d --description 'Display deltas over time, showing any zones tha… [See Man Page]'
complete -c zprint -s p --description 'Display zone usage related to the specified process id.'

