#!/bin/bash

stamp=$(date +%s)
function dot_install()
{
  bkup="backup/home/$stamp"
  for dots in bash/home list/home vim; do
    for fil in $dots/*; do
      if [ -f "$HOME/.$(basename $fil)" ]; then
        mkdir -pv "$bkup" | sed 's/^/mkdir: /'
        mv -v "$HOME/.$(basename $fil)" "${bkup}/"
        echo rm "$HOME/.$(basename $fil)" >> uninstall.$stamp.sh
        echo mv -v "${bkup}/.$(basename $fil)" "$HOME/.$(basename $fil)" >> uninstall.$stamp.sh
      fi
      ln -s "$(pwd)/$fil" "$HOME/.$(basename $fil)"
    done
  done

  if [ -e "$HOME/hashrocket" ]; then
    mv $HOME/hashrocket $bkup/
    echo rm "$HOME/hashrocket" >> uninstall.$stamp.sh
    echo mv -v $bkup/hashrocket "$HOME/" >> uninstall.$stamp.sh
  fi
  ln -s "$(pwd)/hashrocket" $HOME/

  echo "Symlinking dotmatrix dotfiles"
  test -f $HOME/.bashrc && mv $HOME/.bashrc $bkup/
  test -f $HOME/.vim && mv $HOME/.vim $bkup/
  test -f $HOME/.vimrc && mv $HOME/.vimrc $bkup/
  ln -nfs $HOME/hashrocket/dotmatrix/.bashrc $HOME/
  ln -nfs $HOME/hashrocket/dotmatrix/.hashrc $HOME/
  ln -nfs $HOME/hashrocket/dotmatrix/.vim $HOME/
  ln -nfs $HOME/hashrocket/dotmatrix/.vimrc $HOME/
  sh $HOME/hashrocket/dotmatrix/bin/vimbundles.sh

  for bins in bin bin/empties bin/resources bin/tests; do
    mkdir -pv "${HOME}/$bins"
    for fil in $bins/*; do
      if [ -f "$fil" ]; then
        if [ -f "$HOME/$fil" ]; then
          mkdir -pv "$bkup/$bins" | sed 's/^/mkdir: /'
          mv -v "$HOME/$fil" "${bkup}/$fil"
          echo rm "$HOME/$fil" >> uninstall.$stamp.sh
          echo mv -v "${bkup}/$fil" "$HOME/$fil" >> uninstall.$stamp.sh
        fi
        ln -s "$(pwd)/$fil" "${HOME}/$fil"
      fi
    done
  done
}

function dot_uninstall()
{
  bkup="backup/home/$(date +%s)"
  for dots in bash/home list/home vim; do
    for fil in $dots/*; do
      if [ -f "$HOME/.$(basename $fil)" ]; then
        mkdir -pv "$bkup" | sed 's/^/mkdir: /'
        mv -v "$HOME/.$(basename $fil)" "${bkup}/"
      fi
    done
  done

  for bins in hashrocket bin bin/empties bin/resources bin/tests; do
    mkdir -pv "${HOME}/$bins"
    for fil in $bins/*; do
      if [ -f "$fil" ]; then
        if [ -f "$HOME/$fil" ]; then
          mkdir -pv "$bkup/$bins" | sed 's/^/mkdir: /'
          mv -v "$HOME/$fil" "${bkup}/$fil"
        fi
      fi
    done
  done
}

function dot_backup()
{
  bkup="backup/home/$stamp"
  for dots in bash/home list/home vim; do
    for fil in $dots/*; do
      if [ -f "$HOME/.$(basename $fil)" ]; then
        mkdir -pv "$bkup" | sed 's/^/mkdir: /'
        cp -v "$HOME/.$(basename $fil)" "${bkup}/"
      fi
    done
  done

  if [ -e "$HOME/hashrocket" ]; then cp $HOME/hashrocket $bkup/; fi

  for bins in bin bin/empties bin/resources bin/tests; do
    for fil in $bins/*; do
      if [ -f "$fil" ]; then
        if [ -f "$HOME/$fil" ]; then
          mkdir -pv "$bkup/$bins" | sed 's/^/mkdir: /'
          cp -v "$HOME/$fil" "${bkup}/$fil"
        fi
      fi
    done
  done
}

#dot_install
dot_backup

## # /etc/bashrc
## sudo mv /etc/bashrc $dot_dir/bash/etc/
## sudo ln -s $dot_dir/bash/etc/bashrc /etc/bashrc
##
## # /etc/profile
## sudo mv /etc/profile $dot_dir/bash/etc/
## sudo ln -s $dot_dir/bash/etc/profile /etc/profile

