#!/bin/bash

stamp=$(date +%s)

function undo_script() {
  backup_dir="backup/$stamp"
  cat <<UNDO >> $backup_dir/undo.sh
rm "$HOME/$1"
mv -v "$backup_dir/$1" "$HOME/$1"
UNDO
}

function backup_file()
{
  backup_dir="${3:-backup/$stamp}"
  if [ -a "$HOME/$1" -o -h "$HOME/$1" ]; then
    [ ! -d "$backup_dir" ] && mkdir -pv "$backup_dir"
    ${2:-mv} -v "$HOME/$1" "$backup_dir"/
    undo_script "$1" "$backup_dir"
  fi
}

function dot_install()
{
  bkup="backup/$stamp"
  for dots in bash/home list/home vim pure-zsh/home fish; do
    for fil in $dots/*; do
      backup_file ".$(basename $fil)"
      ln -s "$(pwd)/$fil" "$HOME/.$(basename $fil)"
    done
  done

  for dir in hashrocket bin logs
  do
    backup_file "$dir"
    ln -s "$(pwd)/$dir" $HOME/
  done

  if [ ! -e hashrocket/dotmatrix/.hashrc ]; then
    echo "Symlinking dotmatrix dotfiles"
    #rm -rf hashrocket/dotmatrix
    git clone git@github.com:hashrocket/dotmatrix.git hashrocket/dotmatrix
  fi

  for hr_file in .{bashrc,hashrc,vim,vimrc,vimbundle}
  do
    backup_file "$hr_file"
    ln -nfs "$HOME/hashrocket/dotmatrix/$hr_file" $HOME/
  done

  sh $HOME/hashrocket/dotmatrix/bin/vimbundles.sh
}

function dot_uninstall()
{
  bkup="backup/$stamp"
  mkdir -pv "$bkup" | sed 's/^/mkdir: /'

  for dots in bash/home list/home vim pure-zsh/home; do
    for fil in $dots/*; do
      backup_file ".$(basename $fil)"
    done
  done

  for bins in hashrocket bin logs .{bashrc,hashrc,vim,vimrc}; do
    backup_file "$bins"
  done
}

function dot_backup()
{
  bkup="backup/$stamp"

  for dots in bash/home list/home vim pure-zsh/home; do
    for fil in $dots/*; do
      backup_file ".$(basename $fil)" "rsync -avz"
    done
  done

  for dir in hashrocket/dotmatrix; do
    backup_file "$dir" "rsync -az" "$bkup/dotmatrix"
  done

  for bins in hashrocket bin logs .{bashrc,hashrc,vim,vimrc}; do
    backup_file "$bins" "rsync -avz"
  done
}

case ${1:-install} in
  (backup) dot_backup ;;
  (install) dot_install ;;
  (uninstall) dot_uninstall ;;
  (*)
    cat <<MSG

    ######################
    ## OPTION NOT FOUND ##
    ######################

    Option: "$1"

    ######################
    ## OPTION NOT FOUND ##
    ######################

MSG
  ;;
esac

