#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/init.zsh"
fi

# Customize to your needs...
