
## Setup "pure" zsh prompt
#
### fpath=( "$HOME/.zfunctions" $fpath )
### 
### autoload -U promptinit && promptinit
### 
### prompt pure

source ~/.bashrc.local

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="pure"
plugins=(git rbenv rails)

source $ZSH/oh-my-zsh.sh
#export PATH="/usr/local/bin:$PATH"



### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
