. "$HOME/.bashrc"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

##
# Your previous /Users/jearsh/.bash_profile file was backed up as /Users/jearsh/.bash_profile.macports-saved_2013-11-25_at_19:49:11
##

# MacPorts Installer addition on 2013-11-25_at_19:49:11: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/MacbookPro/.bash_profile file was backed up as /Users/MacbookPro/.bash_profile.macports-saved_2014-02-17_at_13:41:54
##

# MacPorts Installer addition on 2014-02-17_at_13:41:54: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
