
source ~/.bashrc.local

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$ZSH/custom
DISABLE_AUTO_TITLE="true"

# plugins and theme need to be set
# before this line:
####### source $ZSH/oh-my-zsh.sh
# Instead of sourcing oh-my-zsh ... only include what I want

function source_oh_my_zsh () {
  # OH MY ZSH libs
  for config_file ($ZSH/lib/*.zsh) source $config_file

  # Theme
  ZSH_THEME="unixsuperhero"
  source $ZSH/custom/themes/${ZSH_THEME}.zsh-theme

  # Load and run compinit
  autoload -U compinit
  compinit -i

  # Plugins
  # ~/.oh-my-zsh{,/custom}/plugins/*
  plugins=(git ruby rails rails3 rvm cut)
  for plugin ($plugins); do
    if [ -f $ZSH_CUSTOM/plugins/$plugin/$plugin.plugin.zsh ]; then
      source $ZSH_CUSTOM/plugins/$plugin/$plugin.plugin.zsh
    elif [ -f $ZSH/plugins/$plugin/$plugin.plugin.zsh ]; then
      source $ZSH/plugins/$plugin/$plugin.plugin.zsh
    fi
  done
}
source_oh_my_zsh

export PATH=./stubs:$HEROKU_BINSTUB_PATH:.git/safe/../../bin:/Users/jearsh/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Users/jtoyota/Sites/node_speed_rps/node_modules/js2coffee/node_modules/.bin:/Users/jtoyota/Sites/node_speed_rps/node_modules/js2coffee/bin:/Developer/usr/bin:/Users/jearsh/.rvm/bin

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

EDITOR=vim

remind ~/.reminders









# ZSH_THEME="apple"
# ZSH_THEME="afowler"
# ZSH_THEME="3den"
# ZSH_THEME="Soliah"
# ZSH_THEME="af-magic"
# ZSH_THEME="afowler"
# ZSH_THEME="agnoster"
# ZSH_THEME="alanpeabody"
# ZSH_THEME="apple"
# ZSH_THEME="arrow"
# ZSH_THEME="aussiegeek"
# ZSH_THEME="awesomepanda"
# ZSH_THEME="bira"
# ZSH_THEME="blinks"
# ZSH_THEME="candy"
# ZSH_THEME="clean"
# ZSH_THEME="cloud"
# ZSH_THEME="crunch"
# ZSH_THEME="cypher"
# ZSH_THEME="dallas"
# ZSH_THEME="darkblood"
# ZSH_THEME="daveverwer"
# ZSH_THEME="dieter"
# ZSH_THEME="dogenpunk"
# ZSH_THEME="dpoggi"
# ZSH_THEME="dst"
# ZSH_THEME="dstufft"
# ZSH_THEME="duellj"
# ZSH_THEME="eastwood"
# ZSH_THEME="edvardm"
# ZSH_THEME="evan"
# ZSH_THEME="example"
# ZSH_THEME="fino-time"
# ZSH_THEME="fino"
# ZSH_THEME="fishy"
# ZSH_THEME="flazz"
# ZSH_THEME="fletcherm"
# ZSH_THEME="fox"
# ZSH_THEME="frisk"
# ZSH_THEME="funky"
# ZSH_THEME="fwalch"
# ZSH_THEME="gallifrey"
# ZSH_THEME="gallois"
# ZSH_THEME="garyblessington"
# ZSH_THEME="gentoo"
# ZSH_THEME="geoffgarside"
# ZSH_THEME="gnzh"
# ZSH_THEME="gozilla"
# ZSH_THEME="humza"
# ZSH_THEME="imajes"
# ZSH_THEME="jbergantine"
# ZSH_THEME="jispwoso"
# ZSH_THEME="jnrowe"
# ZSH_THEME="jonathan"
# ZSH_THEME="josh"
# ZSH_THEME="jreese"
# ZSH_THEME="jtriley"
# ZSH_THEME="juanghurtado"
# ZSH_THEME="kardan"
# ZSH_THEME="kennethreitz"
# ZSH_THEME="kolo"
# ZSH_THEME="kphoen"
# ZSH_THEME="lambda"
# ZSH_THEME="linuxonly"
# ZSH_THEME="lukerandall"
# ZSH_THEME="macovsky-ruby"
# ZSH_THEME="macovsky"
# ZSH_THEME="maran"
# ZSH_THEME="mgutz"
# ZSH_THEME="mh"
# ZSH_THEME="mikeh"
# ZSH_THEME="miloshadzic"
# ZSH_THEME="minimal"
# ZSH_THEME="mortalscumbag"
# ZSH_THEME="mrtazz"
# ZSH_THEME="murilasso"
# ZSH_THEME="muse"
# ZSH_THEME="nanotech"
# ZSH_THEME="nebirhos"
# ZSH_THEME="nicoulaj"
# ZSH_THEME="norm"
# ZSH_THEME="obraun"
# ZSH_THEME="robbyrussell"
# ZSH_THEME="simple"
# ## simple and clean ZSH_THEME="philips"
# ## pretty ZSH_THEME="pygmalion"
# ## pretty ZSH_THEME="re5et"
# ## compact ZSH_THEME="risto"
# ## has time ZSH_THEME="rkj-repos"
# ##ZSH_THEME="skaro"
# ## colorful ZSH_THEME="sporty_256"
# ## simple ZSH_THEME="sunaku"
# #ZSH_THEME="sunrise"
#   ###ZSH_THEME="superjarin"
# ###ZSH_THEME="tonotdo"
# #ZSH_THEME="wuffers"
# ##ZSH_THEME="xiong-chiamiov-plus"
# #ZSH_THEME="xiong-chiamiov"
# #ZSH_THEME="zhann"
